# -------------------------------------------
# Creator: BORA Author
# Date: 06/04/2026
# Purpose: measure how densely the Microsoft Purview SIT keywords (harvested by
#          retrieve_ms_dlp.py into raw_data_records/) occur in the Enron email
#          corpus (data/samples/email_merged128k/).
#
#          Step 1: collect every keyword from raw_data_records/*.txt into one
#                  de-duplicated vocabulary.
#          Step 2: in parallel, scan each email file and, for every keyword,
#                  count how many times it occurs; from that derive, per file,
#                  the number of DISTINCT keywords present and the TOTAL keyword
#                  occurrences.
#          Step 3: summarize over the corpus -- file count, vocabulary size,
#                  distinct-keywords-per-file (avg/min/max) and
#                  total-occurrences-per-file (avg/min/max).
#
# MATCH SEMANTICS (documented so the numbers are reproducible):
#   - case-insensitive;
#   - a match may not be flanked by an alphanumeric char (so "aba" is NOT
#     counted inside "database"; punctuated keywords like "aba#" still match);
#   - internal whitespace in a keyword matches any whitespace run (\s+);
#   - matches are NON-OVERLAPPING, longest-keyword-first: a span is counted once,
#     as the longest keyword that matches it (so "routing number" is one hit, not
#     also a separate "routing").
#
# NOTE: code partly generated by Claude Code. Audited by author.
# -------------------------------------------

import os
import re
import sys
import glob
from concurrent.futures import ProcessPoolExecutor

# common.py lives beside this script (scripts/); import provenance helpers.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import gen_report_header  # noqa: E402

# --- configuration ---------------------------------------------------------
RECORDS_DIR = "raw_data_records"        # input: per-SIT keyword summaries
DOCS_DIR = "docs"
REPORT_FILE = os.path.join(DOCS_DIR, "measure_report.txt")
# email corpus, relative to this script (scripts/ -> ms_dlp -> src_sig -> data).
SAMPLES_DIR = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    os.pardir, os.pardir, os.pardir, "samples", "email_merged128k"))

N_WORKERS = os.cpu_count() or 8
CHUNKSIZE = 16                          # files per task dispatched to a worker

_WS = re.compile(r"\s+")


# --- step 1: collect the keyword vocabulary --------------------------------
# read every raw_data_records/*.txt, pull the lines under "--- keywords ... ---"
# (the last section of each record), normalize (lower + single-spaced) and
# de-duplicate into one vocabulary.
def collect_vocab(records_dir):
    vocab = set()      # distinct keywords (deduped across all SITs)
    total = 0          # total keyword entries (a keyword shared by N SITs counts N)
    for path in glob.glob(os.path.join(records_dir, "*.txt")):
        with open(path, encoding="utf-8", errors="replace") as f:
            grab = False
            for ln in f:
                if ln.startswith("--- keywords"):
                    grab = True
                    continue
                if grab:
                    kw = _WS.sub(" ", ln.strip().lower())
                    if kw:
                        total += 1
                        vocab.add(kw)
    return vocab, total


# build one case-insensitive regex matching any vocabulary keyword. Alternatives
# are ordered longest-first so the engine prefers the longest keyword at a given
# position; internal spaces become \s+; matches may not be flanked by an
# alphanumeric char (word-boundary-ish, but tolerant of punctuated keywords).
def build_pattern(vocab):
    kws = sorted(vocab, key=len, reverse=True)
    alts = []
    for kw in kws:
        esc = r"\s+".join(re.escape(tok) for tok in kw.split(" ") if tok)
        if esc:
            alts.append(esc)
    body = "|".join(alts)
    return re.compile(r"(?<![0-9A-Za-z])(?:" + body + r")(?![0-9A-Za-z])",
                      re.IGNORECASE)


# --- step 2: per-file scan (runs in worker processes) ----------------------
# the compiled pattern is large; compile it ONCE per worker via the pool
# initializer and stash it in a module global, rather than pickling it per task.
_PATTERN = None


def _init_worker(vocab_list):
    global _PATTERN
    _PATTERN = build_pattern(vocab_list)


# scan one email file. Returns (distinct_keywords_present, total_occurrences);
# returns None if the file cannot be read.
def _scan_file(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    counts = {}
    for m in _PATTERN.finditer(text):
        key = _WS.sub(" ", m.group(0).lower())
        counts[key] = counts.get(key, 0) + 1
    return len(counts), sum(counts.values())


# --- step 3: summary -------------------------------------------------------
def _stats(values):
    """(avg, min, max) for a non-empty list; (0,0,0) if empty."""
    if not values:
        return 0.0, 0, 0
    return sum(values) / len(values), min(values), max(values)


def write_report(n_files, vocab_size, vocab_total, distinct, total, files):
    # argmin/argmax (by total occurrences) for a little context in the report.
    lo_i = min(range(len(total)), key=lambda i: total[i]) if total else None
    hi_i = max(range(len(total)), key=lambda i: total[i]) if total else None
    d_avg, d_min, d_max = _stats(distinct)
    t_avg, t_min, t_max = _stats(total)

    lines = []
    lines.append(gen_report_header("ms_dlp keyword-density measurement"))
    lines.append("")
    lines.append("records_dir: %s/" % RECORDS_DIR)
    lines.append("samples_dir: %s" % SAMPLES_DIR)
    lines.append("")
    lines.append("match: case-insensitive, non-alphanumeric-flanked, "
                 "non-overlapping longest-first")
    lines.append("")
    lines.append("== SUMMARY ==")
    lines.append("(1) files scanned:                       %d" % n_files)
    lines.append("(2) keywords collected   total/distinct: %d / %d"
                 % (vocab_total, vocab_size))
    lines.append("(3) distinct keywords per file   avg/min/max: "
                 "%.2f / %d / %d" % (d_avg, d_min, d_max))
    lines.append("(4) total keyword occ. per file  avg/min/max: "
                 "%.2f / %d / %d" % (t_avg, t_min, t_max))
    if hi_i is not None:
        lines.append("")
        lines.append("    busiest file: %s (%d occ, %d distinct)"
                     % (os.path.basename(files[hi_i]), total[hi_i],
                        distinct[hi_i]))
        lines.append("    emptiest file: %s (%d occ, %d distinct)"
                     % (os.path.basename(files[lo_i]), total[lo_i],
                        distinct[lo_i]))
    report = "\n".join(lines)

    os.makedirs(DOCS_DIR, exist_ok=True)
    with open(REPORT_FILE, "w") as f:
        f.write(report + "\n")
    return report


# -------------------------------------------
# MAIN
# -------------------------------------------
def main():
    # anchor cwd to ms_dlp/ (parent of scripts/) so RECORDS_DIR / DOCS_DIR
    # resolve regardless of the invocation directory.
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))

    # step 1: vocabulary
    vocab, vocab_total = collect_vocab(RECORDS_DIR)
    vocab_list = sorted(vocab)
    print("[vocab] %d keywords (%d distinct) from %s/"
          % (vocab_total, len(vocab), RECORDS_DIR))
    if not vocab:
        raise SystemExit("[vocab] no keywords found; run retrieve_ms_dlp.py first")

    # enumerate the corpus
    files = sorted(glob.glob(os.path.join(SAMPLES_DIR, "*")))
    files = [p for p in files if os.path.isfile(p)]
    print("[corpus] %d files in %s" % (len(files), SAMPLES_DIR))
    if not files:
        raise SystemExit("[corpus] no sample files found at %s" % SAMPLES_DIR)

    # step 2: parallel per-file scan
    distinct, total = [], []
    kept_files = []
    done = 0
    with ProcessPoolExecutor(max_workers=N_WORKERS,
                             initializer=_init_worker,
                             initargs=(vocab_list,)) as ex:
        for path, res in zip(files, ex.map(_scan_file, files,
                                           chunksize=CHUNKSIZE)):
            done += 1
            if res is not None:
                d, t = res
                distinct.append(d)
                total.append(t)
                kept_files.append(path)
            if done % 1000 == 0 or done == len(files):
                print("[scan] %d/%d files" % (done, len(files)))

    # step 3: summarize
    report = write_report(len(kept_files), len(vocab), vocab_total, distinct,
                          total, kept_files)
    print()
    print(report)
    print()
    print("[report] written to %s" % REPORT_FILE)


if __name__ == "__main__":
    main()
