# -------------------------------------------
# Creator: BORA Author (measure_v2)
# Date: 06/13/2026
# Purpose: rank CLEAN (unflagged) Enron emails by the REAL per-chunk ZK
#          proving cost -- the aggressive-mode "needs" metric, i.e. a faithful
#          Python mirror of HexACDFA::get_max_needs (data_processor) -- so the
#          sample1/sample2/sample3 manifests pick the genuinely expensive files.
#
# WHY measure.py was wrong (and this replaces it):
#   measure.py ranked files by max_occ_per_chunk = the RAW number of keyword
#   occurrences in the densest 64KB window. That is the WRONG cost proxy:
#     (1) it counts the keyword side only, unweighted -- but in aggressive mode
#         each present SIT pulls its WHOLE fan-out family of SED subsigs into
#         the per-chunk universe. One present keyword costs N_sig (the SIT's
#         fan-out count, ~100), not 1.
#     (2) it counts raw repeats ("company" x132) -- but the cost set is by
#         DISTINCT SIT present, so a repeated word adds nothing.
#     (3) its 64KB window is 32x the real ~2KB folding step.
#   Net effect: measure.py's "10 worst" reached needs~600 while the true corpus
#   worst is needs~9880 (16x), in files measure.py ranked nowhere near the top.
#
# THE METRIC (faithful to get_max_needs / clamav.rs max_needs_subsigs):
#   For each ~2KB chunk: needs_chunk = SUM over the DISTINCT SITs whose keyword
#   appears in that chunk of N_sig, where N_sig = the SIT's SDE fan-out count
#   (product of the cardinalities of the digit/class positions select_slots
#   pins, under the fan-out budget). file_needs = MAX over the file's chunks.
#   Anchor identity: in both arms (PAT.{0,N}KWS and KWS.{0,N}PAT) the pm-bound
#   anchor lands on the keyword side, shared by all N_sig fan-out variants, so
#   mult[anchor] = N_sig -- a present keyword contributes the whole family.
#   (A SIT in a chunk is by construction crit-present, hence in the discharge
#   universe, so the universe gate is subsumed by per-chunk presence.)
#
# FAITHFULNESS CAVEATS (documented so the numbers are reproducible):
#   - a SIT contributes N_sig when ANY of its keywords appears in the chunk
#     (vs. the single specific pm-bound anchor keyword): right magnitude/cost
#     intuition, slight over-count.
#   - chunk_size_bytes (~2KB) mirrors chunk_len=64 words x 31 B/word; Rust
#     chunks the nibble path, negligible rank impact. CLI-tunable (argv[1]).
#   - keyword match semantics carried over from measure.py: case-insensitive,
#     non-alphanumeric-flanked, internal whitespace -> \s+, non-overlapping
#     longest-first.
#   - N_sig uses the case-sensitive fan-out cardinality (digits are caseless,
#     so igc is a no-op for these number SITs).
#   - a PAT the porter cannot size (parse failure / unknown class category)
#     floors to N_sig=1 and prints a [warn] naming the SIT.
#
# NOTE: code partly generated by Claude Code. Audited by author.
# -------------------------------------------

import os
import re
import sys
import collections
from concurrent.futures import ProcessPoolExecutor

try:                                    # Py>=3.11 moved the regex parser.
    from re import _parser as _sre_parse
    from re import _constants as _sre
except ImportError:                     # noqa
    import sre_parse as _sre_parse      # noqa
    import sre_constants as _sre        # noqa

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import (gen_report_header, get_ms_dlp_dir,  # noqa: E402
                    get_samples_dir)
import run_zombie as rz                 # noqa: E402

# --- configuration ---------------------------------------------------------
DOCS_DIR = "docs"
DATASETS = [
    ("email_merged128k", get_samples_dir() / "email_merged128k"),
    ("email",            get_samples_dir() / "email"),
]
RULESETS = ["regex_zombie", "regex_zombie_international"]

N_WORKERS = os.cpu_count() or 8
CHUNKSIZE = 16                          # files per task dispatched to a worker

# Aggressive-mode fan-out knobs (must mirror the Rust DB build for this set):
#  - FANOUT_CAP  = ClamavApproxConfig.sde_rep_fanout_cap base (run uses 100).
#  - FANOUT_BOOST/main_fanout.dat = per-SIT cap *= boost for sigs whose name
#    contains a main_fanout.dat line (the intl cfg dir has NO such file ->
#    boost inert).
#  - TIGHT = b_sde_rep_tight_first_leg (all DLP paths set it false).
FANOUT_CAP = 100
FANOUT_BOOST = 10
TIGHT = False
CHUNK_BYTES = 64 * 31                   # chunk_len(64 words) x 31 B/word ~2KB

SINGLE_FANOUT_MAX = 26                  # pcre.rs: skip legs above this card

_WS = re.compile(r"\s+")
WS_CLASS = r"[\x20\x09\x0A\x0D]"


def _decode_esc(s):
    """Decode \\xHH escapes in a regex literal back to characters."""
    return re.sub(r"\\x([0-9A-Fa-f]{2})",
                  lambda m: chr(int(m.group(1), 16)), s)


def _strip_ws_wrap(alt):
    """Strip the optional whitespace-delimiter class wrapping a keyword."""
    if alt.startswith(WS_CLASS):
        alt = alt[len(WS_CLASS):]
    if alt.endswith(WS_CLASS):
        alt = alt[:-len(WS_CLASS)]
    return alt


# --- fan-out N_sig: faithful port of find_class_runs + select_slots --------
# A class-run "leg": its matched byte set (for cardinality), its guaranteed
# count `min`, and whether it sits under an optional/alternation wrapper.
class _Leg:
    __slots__ = ("bytes", "min", "optional")

    def __init__(self, byteset, mn, optional):
        self.bytes = byteset
        self.min = mn
        self.optional = optional


# category -> matched byte count (byte domain; PATs use explicit ranges, so
# these are rare). Unknown categories warn and return a large count so
# select_slots skips them (sound under-fan-out, never an over-count).
_CAT_CARD = {
    getattr(_sre, "CATEGORY_DIGIT", None): 10,
    getattr(_sre, "CATEGORY_SPACE", None): 6,
    getattr(_sre, "CATEGORY_WORD", None): 63,
}


def _in_byteset(items, warns):
    """Byte set matched by an IN (character-class) node's item list."""
    neg = False
    bs = set()
    for op, av in items:
        if op == _sre.NEGATE:
            neg = True
        elif op == _sre.LITERAL:
            bs.add(av & 0xFF)
        elif op == _sre.RANGE:
            lo, hi = av
            bs.update(range(lo & 0xFF, (hi & 0xFF) + 1))
        elif op == _sre.CATEGORY:
            n = _CAT_CARD.get(av)
            if n is None:
                warns.append("unknown_category")
                n = 999                 # large -> skipped by select_slots
            bs.update(range(0, n))       # placeholder bytes, count only
    if neg:
        return set(range(256)) - bs
    return bs


def _fold_igc(byteset):
    """Collapse A-Z onto a-z (case-fold) -- size = igc cardinality."""
    out = set()
    for b in byteset:
        out.add(b + 0x20 if 0x41 <= b <= 0x5A else b)
    return out


def _collect_legs(seq, in_optional, legs, warns):
    """Walk a parsed SubPattern left-to-right collecting class-run legs,
    mirroring collect_class_runs over the Rust HIR."""
    for op, av in seq:
        if op == _sre.IN:
            legs.append(_Leg(_in_byteset(av, warns), 1, in_optional))
        elif op == _sre.ANY:
            legs.append(_Leg(set(range(256)), 1, in_optional))
        elif op in (_sre.MAX_REPEAT, _sre.MIN_REPEAT):
            mn, _mx, sub = av
            if len(sub) == 1 and sub[0][0] == _sre.IN:
                if mn >= 1:
                    legs.append(_Leg(_in_byteset(sub[0][1], warns), mn,
                                     in_optional))
                # mn==0: no guaranteed position -> skip.
            elif len(sub) == 1 and sub[0][0] == _sre.ANY:
                if mn >= 1:
                    legs.append(_Leg(set(range(256)), mn, in_optional))
            else:
                _collect_legs(sub, in_optional or mn == 0, legs, warns)
        elif op == _sre.BRANCH:
            _none, branches = av
            for br in branches:
                _collect_legs(br, True, legs, warns)
        elif op == _sre.SUBPATTERN:
            _collect_legs(av[-1], in_optional, legs, warns)
        # LITERAL / NOT_LITERAL / AT / etc. -> not a class run.


def _pos_priority(n):
    if n == 0:
        return []
    return [0] + list(range(n - 1, 0, -1))


def _pos_priority_last(n):
    if n < 2:
        return _pos_priority(n)
    target = n - 2
    return [target, 0] + [i for i in range(n - 1, 0, -1) if i != target]


def _card_igc(leg, b_igc):
    return len(_fold_igc(leg.bytes) if b_igc else leg.bytes)


def _select_product(legs, b, b_igc, tight):
    """Fan-out count = product of pinned-position cardinalities, faithful to
    select_slots (priority + budget). Only the product (N_sig) matters here,
    so the chosen positions themselves are not recorded."""
    m = len(legs)
    if m == 0:
        return 1
    if tight:
        prio = [0] if m == 1 else [0, m - 1]
    else:
        prio = [0] + list(range(m - 1, 0, -1))
    qs = []
    for idx, l in enumerate(legs):
        if idx == m - 1:
            qs.append(_pos_priority_last(l.min))
        elif tight and idx == 0:
            qs.append(list(range(l.min)))
        else:
            qs.append(_pos_priority(l.min))
    max_n = max((l.min for l in legs), default=0)
    product = 1
    for want_optional in (False, True):
        for rnd in range(max_n):
            for leg in prio:
                if legs[leg].optional != want_optional:
                    continue
                if rnd >= len(qs[leg]):
                    continue
                c = _card_igc(legs[leg], b_igc)
                if c > SINGLE_FANOUT_MAX:
                    continue
                if product * c <= b:
                    product *= c
    return product


def n_sig_from_pat(pat, cap, b_igc=False, tight=TIGHT):
    """(N_sig, warns) for one SIT's number pattern. Parse failure or an
    unsizable construct floors N_sig=1 and records a warn reason."""
    try:
        seq = _sre_parse.parse(pat)
    except Exception:
        return 1, ["parse_fail"]
    legs, warns = [], []
    _collect_legs(seq, False, legs, warns)
    if not legs:
        return 1, warns
    return _select_product(legs, cap, b_igc, tight), warns


# --- step 1: per-SIT keywords + fan-out count ------------------------------
def _load_boost_subs(regex_dir):
    """main_fanout.dat (co-located with the ruleset) -> set of name
    substrings to boost. Absent file -> empty -> no boost (intl set)."""
    cand = os.path.join(os.path.dirname(regex_dir.rstrip("/")),
                        "main_fanout.dat")
    if not os.path.isfile(cand):
        return set()
    subs = set()
    with open(cand, encoding="utf-8") as f:
        for ln in f:
            ln = ln.strip()
            if ln and not ln.startswith("#"):
                subs.add(ln)
    return subs


def collect_sits(regex_dir):
    """One entry per SIT: (name, n_sig, [keywords]). Keywords are the KWS
    alternatives (ws-wrappers stripped, \\xHH decoded, lower, single-spaced);
    n_sig from the PAT fan-out with the per-SIT boosted cap."""
    boost_subs = _load_boost_subs(regex_dir)
    sits = []
    for name in rz.list_sit_reps(regex_dir):
        full = open(os.path.join(regex_dir, name + ".regex"),
                    encoding="utf-8").read().strip()
        try:
            pat, kws, _prox = rz.extract_parts(full)
        except Exception:
            continue                       # non-standard structure -> skip
        cap = FANOUT_CAP
        if boost_subs and any(s in name for s in boost_subs):
            cap *= FANOUT_BOOST
        nsig, warns = n_sig_from_pat(pat, cap)
        if warns:
            print("[warn] SIT %s: %s (N_sig=%d, may be under-weighted)"
                  % (name, ",".join(sorted(set(warns))), nsig))
        kw_set = set()
        for alt in kws[1:-1].split("|"):   # strip outer parens, split alts
            kw = _WS.sub(" ",
                         _decode_esc(_strip_ws_wrap(alt)).strip().lower())
            if kw:
                kw_set.add(kw)
        if kw_set:
            sits.append((name, nsig, sorted(kw_set)))
    return sits


def read_clean_list(clean_list, samples_dir):
    if not os.path.isfile(clean_list):
        raise SystemExit("[corpus] %s not found; run eval_dlp.py first"
                         % clean_list)
    files = []
    with open(clean_list, encoding="utf-8") as f:
        for ln in f:
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            p = os.path.join(samples_dir, ln)
            if os.path.isfile(p):
                files.append(p)
    return sorted(files)


def build_pattern(keywords):
    """One case-insensitive regex over all keywords, longest-first, internal
    spaces -> \\s+, non-alphanumeric-flanked. Same semantics as measure.py."""
    alts = []
    for kw in sorted(keywords, key=len, reverse=True):
        esc = r"\s+".join(re.escape(tok) for tok in kw.split(" ") if tok)
        if esc:
            alts.append(esc)
    body = "|".join(alts)
    return re.compile(r"(?<![0-9A-Za-z])(?:" + body + r")(?![0-9A-Za-z])",
                      re.IGNORECASE)


# --- step 2: per-file scan (worker processes) ------------------------------
_PATTERN = None
_KW2SITS = None         # normalized keyword -> tuple(sit ids)
_NSIG = None            # sit id -> N_sig
_NAMES = None           # sit id -> name
_CB = None              # chunk size in bytes


def _init_worker(keywords, kw2sits, nsig, names, chunk_bytes):
    global _PATTERN, _KW2SITS, _NSIG, _NAMES, _CB
    _PATTERN = build_pattern(keywords)
    _KW2SITS, _NSIG, _NAMES, _CB = kw2sits, nsig, names, chunk_bytes


def _scan_file(path):
    """needs = max over chunks of SUM N_sig over DISTINCT SITs whose keyword
    starts in that chunk. Returns (file_needs, distinct_sits_in_file,
    densest_chunk_top_sits) or None on read error."""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    chunk_sits = {}                  # chunk idx -> set(sit ids)
    seen_file = set()
    for m in _PATTERN.finditer(text):
        key = _WS.sub(" ", m.group(0).lower())
        sids = _KW2SITS.get(key)
        if not sids:
            continue
        ci = m.start() // _CB
        s = chunk_sits.get(ci)
        if s is None:
            s = chunk_sits[ci] = set()
        s.update(sids)
        seen_file.update(sids)
    if not chunk_sits:
        return 0, 0, []
    best_ci, best = 0, -1
    for ci, sids in chunk_sits.items():
        tot = sum(_NSIG[i] for i in sids)
        if tot > best:
            best, best_ci = tot, ci
    top = sorted(chunk_sits[best_ci], key=lambda i: _NSIG[i],
                 reverse=True)[:5]
    top_sits = [(_NAMES[i], _NSIG[i]) for i in top]
    return best, len(seen_file), top_sits


# --- step 3: summary -------------------------------------------------------
def format_distribution(values, max_exact=10):
    n = len(values)
    if not n:
        return ["  (no files)"]
    c = collections.Counter(values)
    out = ["  %8s  %8s  %8s  %10s"
           % ("needs", "files", "share", "cum.share")]
    cum = 0
    for v in range(0, max_exact + 1):
        if v not in c:
            continue
        cum += c[v]
        out.append("  %8d  %8d  %7.1f%%  %9.1f%%"
                   % (v, c[v], 100.0 * c[v] / n, 100.0 * cum / n))
    tail = sorted(v for v in c if v > max_exact)
    if tail:
        tc = sum(c[v] for v in tail); cum += tc
        out.append("  %8s  %8d  %7.1f%%  %9.1f%%   (range %d..%d)"
                   % (">%d" % max_exact, tc, 100.0 * tc / n,
                      100.0 * cum / n, tail[0], tail[-1]))
    s = sorted(values)

    def pct(p):
        return s[min(n - 1, int(p * n))]
    out.append("")
    out.append("  median=%d  p90=%d  p99=%d  max=%d   (0 needs: %d files, "
               "%.1f%%)" % (pct(0.50), pct(0.90), pct(0.99), s[-1],
                            c[0], 100.0 * c[0] / n))
    return out


def format_worst(needs, distinct, topsits, files, n=10):
    order = sorted(range(len(needs)),
                   key=lambda i: (needs[i], distinct[i]),
                   reverse=True)[:n]
    out = ["  %4s  %10s  %9s  %s" % ("rank", "needs", "distinct", "file")]
    for r, i in enumerate(order, 1):
        out.append("  %4d  %10d  %9d  %s"
                   % (r, needs[i], distinct[i],
                      os.path.basename(files[i])))
    out.append("")
    out.append("  densest-chunk SIT breakdown (name x N_sig):")
    for r, i in enumerate(order, 1):
        br = (", ".join("%s (%d)" % (nm, ns) for nm, ns in topsits[i])
              if topsits[i] else "(none)")
        out.append("  %4d  %s: %s" % (r, os.path.basename(files[i]), br))
    return out


def write_report(report_file, ruleset_dir, dataset_dir, clean_list, sits,
                 needs, distinct, topsits, files, chunk_bytes):
    lines = [gen_report_header("ms_dlp aggressive-needs measurement (v2)"),
             ""]
    lines.append("metric:      needs = max over %dB chunks of SUM N_sig over"
                 % chunk_bytes)
    lines.append("             distinct SITs whose keyword is in the chunk")
    lines.append("keywords:    %s/ KWS groups (post-filter)" % ruleset_dir)
    lines.append("dataset:     %s" % dataset_dir)
    lines.append("corpus:      clean (unflagged) subset -- %s" % clean_list)
    lines.append("fan-out:     base cap=%d boost=%dx tight=%s"
                 % (FANOUT_CAP, FANOUT_BOOST, TIGHT))
    n_avg = (sum(s[1] for s in sits) / len(sits)) if sits else 0
    n_max = max((s[1] for s in sits), default=0)
    lines.append("SITs:        %d  (N_sig avg/max = %.1f / %d)"
                 % (len(sits), n_avg, n_max))
    lines.append("")
    lines.append("== needs DISTRIBUTION (%dB chunks) ==" % chunk_bytes)
    lines.extend(format_distribution(needs))
    lines.append("")
    lines.append("== 10 WORST FILES by needs ==")
    lines.extend(format_worst(needs, distinct, topsits, files))
    lines.append("")
    lines.append("== top SITs by N_sig (fan-out cost) ==")
    for nm, ns, _kw in sorted(sits, key=lambda x: x[1], reverse=True)[:15]:
        lines.append("  %8d  %s" % (ns, nm))
    report = "\n".join(lines)
    os.makedirs(DOCS_DIR, exist_ok=True)
    with open(report_file, "w") as f:
        f.write(report + "\n")
    return report


# -------------------------------------------
# MAIN
# -------------------------------------------
def measure_combo(tag, ds_name, ds_dir, rs_dir, chunk_bytes):
    if not os.path.isdir(rs_dir):
        print("[measure_v2] ruleset %s/ absent -- skip %s" % (rs_dir, tag))
        return None
    clean_list = os.path.join(DOCS_DIR, "clean_email_list_%s.txt" % tag)
    report_file = os.path.join(DOCS_DIR, "measure_v2_report_%s.txt" % tag)

    sits = collect_sits(rs_dir)
    print("[sits] %s : %d SITs, N_sig max=%d from %s/"
          % (tag, len(sits), max((s[1] for s in sits), default=0), rs_dir))
    if not sits:
        print("[measure_v2] no SITs in %s/ -- run gen_zombie_regex.py"
              % rs_dir)
        return None

    # flatten SITs -> keyword vocab + maps for the workers.
    nsig = [s[1] for s in sits]
    names = [s[0] for s in sits]
    kw2sits = {}
    for sid, (_nm, _ns, kws) in enumerate(sits):
        for kw in kws:
            kw2sits.setdefault(kw, []).append(sid)
    kw2sits = {k: tuple(v) for k, v in kw2sits.items()}
    keywords = sorted(kw2sits)

    files = read_clean_list(clean_list, str(ds_dir))
    print("[corpus] %s : %d clean files" % (tag, len(files)))
    if not files:
        print("[measure_v2] no clean files -- run eval_dlp.py first")
        return None

    needs, distinct, topsits, kept, done = [], [], [], [], 0
    with ProcessPoolExecutor(max_workers=N_WORKERS,
                             initializer=_init_worker,
                             initargs=(keywords, kw2sits, nsig, names,
                                       chunk_bytes)) as ex:
        for path, res in zip(files, ex.map(_scan_file, files,
                                           chunksize=CHUNKSIZE)):
            done += 1
            if res is not None:
                nd, ds, tk = res
                needs.append(nd); distinct.append(ds); topsits.append(tk)
                kept.append(path)
            if done % 5000 == 0 or done == len(files):
                print("[scan] %s : %d/%d" % (tag, done, len(files)))

    write_report(report_file, rs_dir, ds_dir, clean_list, sits, needs,
                 distinct, topsits, kept, chunk_bytes)
    print("[report] %s -> %s" % (tag, report_file))
    return {"tag": tag, "files": len(kept),
            "needs_max": max(needs) if needs else 0,
            "needs_avg": (sum(needs) / len(needs)) if needs else 0}


def main():
    os.chdir(get_ms_dlp_dir())          # resolve relative paths
    chunk_bytes = CHUNK_BYTES
    if len(sys.argv) > 1:               # optional chunk-size override (bytes)
        chunk_bytes = int(sys.argv[1])

    summaries = []
    for ds_name, ds_dir in DATASETS:
        for rs_dir in RULESETS:
            tag = "%s_%s" % (ds_name, rs_dir)
            print("\n=== measure_v2 %s (chunk=%dB) ==="
                  % (tag, chunk_bytes))
            s = measure_combo(tag, ds_name, ds_dir, rs_dir, chunk_bytes)
            if s:
                summaries.append(s)

    print("\n=== measure_v2 matrix summary ===")
    for s in summaries:
        print("  %-48s files=%d needs avg/max=%.1f/%d"
              % (s["tag"], s["files"], s["needs_avg"], s["needs_max"]))


if __name__ == "__main__":
    main()
