# -------------------------------------------
# Creator: BORA Author. Implementation mostly done using
#		Claude Code 4.7. Reviewed and output sampled/tested by BORA author.
# Date: 06/04/2026
# Purpose: enumerate every Microsoft Purview "sensitive information type" (SIT)
#          entity definition published on Microsoft Learn, and keep only the
#          ones that are reproducible as a Zombie/BORA-style proximity policy:
#
#            (a) a PATTERN the SIT page describes well enough to build a regex,
#            (b) a PROXIMITY spec (patternsProximity, e.g. 300 characters),
#            (c) a non-empty KEYWORD list,
#            (d) NOT an ML / named-entity / dictionary classifier (i.e. the
#                pattern cannot be translated into regex), and
#            (e) ENGLISH-ONLY keywords.
#
#        REJECTION REASONS: a SIT is rejected (never written to raw_data_records/)
#        for ANY of the following; each is recorded verbatim per-SIT in
#        docs/retrieve_record.log, and the criterion (g) list is also printed
#        there under "HARDCODED REMOVE LIST":
#          (a) "no pattern section"      -- no usable Pattern prose (>= 15 chars)
#          (b) "no proximity spec"       -- no patternsProximity / "within N characters"
#          (c) "no keyword list"         -- no positive keyword bullet
#          (d) "ML/named-entity (not regex-translatable)" -- trainable classifier,
#                                           named-entity, or exact-data-match SIT
#          (e) "non-English keyword(s): ..." -- at least one non-ASCII keyword
#          (f) "pattern defined by a Purview Func_* classifier function" -- the
#                                           Pattern names a Func_* (e.g. Func_ssn)
#                                           instead of giving a literal format
#          (g) "verified to not match real samples via web crawling" -- the
#                                           hardcoded VERIFIED_NONMATCHING_SITS
#                                           remove list: the Pattern is regex-shaped
#                                           but the generated regex matched NONE of
#                                           the real web-crawled samples (positional
#                                           encodings, checksum-only specs, or a
#                                           spec/reality divergence). See
#                                           docs/reg_pat_samples.log.
#
#		Note: this script is only used for downloading the raw spec
#			regex will be generated by other Python files.
# -------------------------------------------

import os
import re
import sys
import time
import shutil
import datetime
import urllib.request
import urllib.error
from html.parser import HTMLParser
from concurrent.futures import ThreadPoolExecutor, as_completed

# common.py lives beside this script (scripts/); import provenance helpers.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import gen_report_header  # noqa: E402

# --- configuration ---------------------------------------------------------
LEARN_BASE = "https://learn.microsoft.com/en-us/purview"
INDEX_URL = LEARN_BASE + "/sit-sensitive-information-type-entity-definitions"
USER_AGENT = "bora-ms-dlp-retriever/1.0 (research; stdlib urllib)"

DOCS_DIR = "docs"
RECORDS_DIR = "raw_data_records"
LOG_FILE = os.path.join(DOCS_DIR, "retrieve_record.log")

N_WORKERS = 4           # concurrent SIT page fetches (Learn 429s above ~8)
HTTP_TIMEOUT = 60       # seconds per request
HTTP_RETRIES = 6        # attempts per URL before giving up
BACKOFF_CAP = 30        # max seconds to sleep between retries

# proximity: Purview's machine-readable attribute, else the prose fallback.
RE_PROX_ATTR = re.compile(r'patternsProximity\s*=\s*"(\d+)"')
RE_PROX_TEXT = re.compile(r'within\s+(\d+)\s+character', re.IGNORECASE)
# index page links to each SIT definition page in its left-nav TOC. The hrefs
# are usually relative (href="sit-defn-<name>") but may be absolute; match the
# slug under either form, anchored to the href so we don't catch prose mentions.
RE_SIT_SLUG = re.compile(
    r'href="(?:[^"]*?/)?(sit-defn-[a-z0-9][a-z0-9-]*)"', re.IGNORECASE)

# (d) markers that mean "not a regex" -- ML classifiers, named-entity and
# dictionary-backed SITs. Scanned ONLY against the SIT's own Pattern/Format
# prose (NOT the whole page: the left-nav links "Trainable classifiers" etc.
RE_NON_REGEX = re.compile(
    r'(named\s*entit|trainable\s+classifier|machine\s+learning|'
    r'exact\s+data\s+match)', re.IGNORECASE)

# (g) hand-verified exclusions: these SITs have a regex-SHAPED Pattern, so they
# pass criteria (a)-(f), but the generated regex was verified during sample
# testing -- web-crawled real samples, see docs/reg_pat_samples.log -- to match
# NONE of the real-world values. The prose cannot be faithfully translated
# (positional encodings, checksum-only specs, or a spec/reality format
# divergence), so we exclude them rather than ship a regex that never fires.
VERIFIED_NONMATCHING_SITS = {
    "sit-defn-australia-medical-account-number",   # positional (1st/9th/10th/11th digit)
    "sit-defn-italy-fiscal-code",                  # encodes name consonants/dates
    "sit-defn-sweden-tax-identification-number",   # county/gender/check prose, not a shape
    "sit-defn-uk-drivers-license-number",          # 16-char DOB-encoded, female +50 rule
    "sit-defn-malaysia-identification-card-number",  # spec "two-letter" code; real is digits
    "sit-defn-azure-service-bus-connection-string",  # spec literal "EndPoint"; real is "Endpoint"
}

# normalize a run of HTML-extracted text to single-spaced, stripped.
_WS = re.compile(r"\s+")
def norm(s):
    return _WS.sub(" ", s).strip()


# --- SIT page parser -------------------------------------------------------
# Walk the rendered Learn HTML and recover the structured fields we need:
#   - section text keyed by its <h2> title (lower-cased), e.g. "pattern"
#   - every <li> bullet that appears under the "keywords" <h2> (the actual
#     keyword values, across all the ### Keyword_* sublists)
# convert_charrefs is True by default, so handle_data already receives
# entity-decoded text.
class SITParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.sections = {}        # h2 title (lower) -> [text chunks]
        self.keyword_items = []   # <li> texts collected under the keywords h2
        self.pattern_items = []   # <li> texts collected under the pattern h2
        self.pattern_groups = []  # one sub-list of <li> texts per <ul>/<ol>
                                  # under the Pattern h2; >1 group => the page
                                  # gave OR-delimited alternative formats, kept
                                  # here as separate groups (not flattened)
        self._cur = None          # current h2 title (lower) or None
        self._h = 0               # heading level if inside h1..h4, else 0
        self._hbuf = []
        self._li = 0              # <li> nesting depth
        self._libuf = []

    def handle_starttag(self, tag, attrs):
        if tag in ("h1", "h2", "h3", "h4"):
            self._h = int(tag[1])
            self._hbuf = []
        elif tag in ("ul", "ol") and self._cur == "pattern":
            # each list under Pattern is one OR-delimited "format" alternative
            # (the page separates them with <p>OR</p>, which we don't render).
            # Start a fresh group so the alternation is preserved, not merged
            # into one ambiguous sequence.
            self.pattern_groups.append([])
        elif tag == "li":
            self._li += 1
            self._libuf = []

    def handle_endtag(self, tag):
        if tag in ("h1", "h2", "h3", "h4") and self._h:
            text = norm(" ".join(self._hbuf))
            if self._h == 2:
                self._cur = text.lower()
                self.sections.setdefault(self._cur, [])
            self._h = 0
            self._hbuf = []
        elif tag == "li" and self._li:
            text = norm(" ".join(self._libuf))
            if text and self._cur and self._cur.startswith("keyword"):
                self.keyword_items.append(text)
            elif text and self._cur == "pattern":
                self.pattern_items.append(text)
                # route into the current format group (create one if a stray
                # <li> precedes its list) so groups stay aligned with the flat
                # list.
                if not self.pattern_groups:
                    self.pattern_groups.append([])
                self.pattern_groups[-1].append(text)
            self._li -= 1
            self._libuf = []

    def handle_data(self, data):
        if self._h:
            self._hbuf.append(data)
            return
        if self._li:
            self._libuf.append(data)
        if self._cur is not None:
            self.sections[self._cur].append(data)

    # joined, normalized text of one <h2> section (empty string if absent).
    def section_text(self, title):
        return norm(" ".join(self.sections.get(title, [])))


# --- networking ------------------------------------------------------------
# fetch one URL, returning (body_text, headers). Sends a User-Agent (Learn
# rejects header-less clients) and backs off on rate-limiting: 429/503 are
# retried, honoring Retry-After when present, else exponential backoff capped
# at BACKOFF_CAP. HTTPError is a URLError subclass, so it is caught first.
def fetch_url(url):
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    last_err = None
    for attempt in range(1, HTTP_RETRIES + 1):
        try:
            with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT) as resp:
                charset = resp.headers.get_content_charset() or "utf-8"
                body = resp.read().decode(charset, errors="replace")
                return body, resp.headers
        except urllib.error.HTTPError as e:
            last_err = e
            if e.code in (429, 503) and attempt < HTTP_RETRIES:
                ra = e.headers.get("Retry-After", "")
                delay = float(ra) if ra.isdigit() else min(2 ** attempt, BACKOFF_CAP)
                time.sleep(delay)
            elif attempt < HTTP_RETRIES:
                time.sleep(min(2 ** attempt, BACKOFF_CAP))
        except (urllib.error.URLError, OSError) as e:
            last_err = e
            if attempt < HTTP_RETRIES:
                time.sleep(min(2 ** attempt, BACKOFF_CAP))
    raise RuntimeError("fetch failed after %d tries: %s (%s)"
                       % (HTTP_RETRIES, url, last_err))


# --- pipeline steps --------------------------------------------------------
# fetch the index page and return the sorted, de-duplicated list of SIT slugs.
def list_sit_slugs():
    print("[index] fetching %s" % INDEX_URL)
    html, _ = fetch_url(INDEX_URL)
    slugs = sorted(set(m.group(1).lower() for m in RE_SIT_SLUG.finditer(html)))
    # the index links to itself; drop that so it is not classified as a SIT.
    slugs = [s for s in slugs
             if s != "sit-sensitive-information-type-entity-definitions"]
    print("[index] %d SIT definition pages found" % len(slugs))
    return slugs


# classify one SIT page against criteria (a)-(d).
# Returns a dict: slug, url, accepted, reasons, proximity, pattern, keywords,
# representative_keyword, last_modified, etag.
def classify_sit(slug):
    url = "%s/%s" % (LEARN_BASE, slug)
    html, headers = fetch_url(url)

    p = SITParser()
    p.feed(html)

    pattern_text = p.section_text("pattern")
    pattern_items = list(p.pattern_items)
    pattern_groups = [g for g in p.pattern_groups if g]
    format_text = p.section_text("format")
    keywords = list(p.keyword_items)

    # (b) proximity: prefer the machine-readable attribute, else prose.
    m = RE_PROX_ATTR.search(html) or RE_PROX_TEXT.search(html)
    proximity = int(m.group(1)) if m else None

    # (a) pattern: a Pattern section with real prose (a few words, not a stub).
    has_pattern = len(pattern_text) >= 15
    # (c) keywords: at least one positive keyword bullet.
    has_keywords = len(keywords) >= 1
    # (d) regex-translatable: not an ML / named-entity / EDM classifier, judged
    # from the SIT's own pattern/format prose.
    non_regex = bool(RE_NON_REGEX.search(pattern_text)
                     or RE_NON_REGEX.search(format_text))
    # (f) function-defined: the Pattern is expressed through Purview Func_*
    # classifier functions (e.g. Func_ssn) instead of a literal format, so there
    # is no shape to translate. Scoped to the Pattern section -- some SITs (e.g.
    # US/UK passport) name a Func_* only in prose/keywords while still giving a
    # real Pattern, and those must not be dropped.
    func_defined = bool(re.search(r"\bFunc_\w+", pattern_text))
    # (e) English-only: every keyword is ASCII. Any non-ASCII keyword (CJK,
    # Cyrillic, accented Latin) marks a non-English SIT, which we drop.
    non_english = [kw for kw in keywords if not kw.isascii()]

    reasons = []
    if not has_pattern:
        reasons.append("no pattern section")
    if proximity is None:
        reasons.append("no proximity spec")
    if not has_keywords:
        reasons.append("no keyword list")
    if non_regex:
        reasons.append("ML/named-entity (not regex-translatable)")
    if func_defined:
        reasons.append("pattern defined by a Purview Func_* classifier function "
                       "(not a literal format; not regex-translatable)")
    if slug in VERIFIED_NONMATCHING_SITS:
        reasons.append("verified to not match real samples via web crawling "
                       "(regex translation cannot represent the real-world format; "
                       "see docs/reg_pat_samples.log)")
    if non_english:
        reasons.append("non-English keyword(s): %s"
                       % ", ".join(non_english[:3]))

    return {
        "slug": slug,
        "url": url,
        "accepted": not reasons,
        "reasons": reasons,
        "proximity": proximity,
        "pattern": pattern_text,
        "pattern_items": pattern_items,
        "pattern_groups": pattern_groups,
        "keywords": keywords,
        "representative_keyword": keywords[0] if keywords else "",
        "last_modified": headers.get("Last-Modified", ""),
        "etag": headers.get("ETag", ""),
    }


# write one accepted SIT summary to raw_data_records/<slug>.txt. Holds the three
# public fields requested -- proximity, pattern list, keywords -- plus minimal
# provenance (slug, url, the representative keyword, server Last-Modified/ETag).
def write_record(rec):
    path = os.path.join(RECORDS_DIR, rec["slug"] + ".txt")
    with open(path, "w") as f:
        f.write("slug:                   %s\n" % rec["slug"])
        f.write("source_url:             %s\n" % rec["url"])
        f.write("retrieved:              %s\n"
                % datetime.date.today().isoformat())
        f.write("last_modified:          %s\n" % rec["last_modified"])
        f.write("etag:                   %s\n" % rec["etag"])
        f.write("proximity:              %d characters\n" % rec["proximity"])
        f.write("representative_keyword: %s\n" % rec["representative_keyword"])
        # the Pattern section is usually a bulleted list of format elements;
        # preserve one element per line. When the page gave several alternative
        # formats (separate lists), they are written as groups joined by a lone
        # "OR" line so a downstream parser can recover the alternation. Fall back
        # to the prose if there were no list items at all.
        f.write("\n--- pattern ---\n")
        groups = rec.get("pattern_groups") or (
            [rec["pattern_items"]] if rec["pattern_items"] else [])
        if groups:
            for gi, grp in enumerate(groups):
                if gi:
                    f.write("OR\n")   # alternative-format boundary
                for it in grp:
                    f.write(it + "\n")
        else:
            f.write(rec["pattern"] + "\n")
        f.write("\n--- keywords (%d) ---\n" % len(rec["keywords"]))
        for kw in rec["keywords"]:
            f.write(kw + "\n")
    return path


# fetch + classify every slug in parallel, preserving slug order in the result.
def classify_all(slugs):
    results = {}
    with ThreadPoolExecutor(max_workers=N_WORKERS) as ex:
        futures = {ex.submit(classify_sit, s): s for s in slugs}
        done = 0
        for fut in as_completed(futures):
            slug = futures[fut]
            done += 1
            try:
                results[slug] = fut.result()
            except Exception as e:  # keep going; record the failure in the log
                results[slug] = {
                    "slug": slug, "url": "%s/%s" % (LEARN_BASE, slug),
                    "accepted": False, "reasons": ["fetch/parse error: %s" % e],
                    "proximity": None, "pattern": "", "pattern_items": [],
                    "pattern_groups": [],
                    "keywords": [],
                    "representative_keyword": "", "last_modified": "", "etag": "",
                }
            if done % 25 == 0 or done == len(slugs):
                print("[scan] %d/%d pages classified" % (done, len(slugs)))
    return [results[s] for s in slugs]


# write docs/retrieve_record.log: provenance header, then one line per SIT,
# then a summary count. Returns (accepted, rejected) counts.
def write_log(results):
    accepted = [r for r in results if r["accepted"]]
    rejected = [r for r in results if not r["accepted"]]
    with open(LOG_FILE, "w") as f:
        f.write(gen_report_header("ms_dlp SIT retrieval log"))
        f.write("\n\n")
        f.write("index_url:  %s\n" % INDEX_URL)
        f.write("records_in: %s/\n\n" % RECORDS_DIR)
        # document the hardcoded remove list (criterion g): SITs whose Pattern is
        # regex-shaped but whose generated regex was verified, via web-crawled
        # real samples (docs/reg_pat_samples.log), to not match real values.
        f.write("== HARDCODED REMOVE LIST (verified non-matching; criterion g) ==\n")
        f.write("These SITs are force-excluded regardless of criteria (a)-(f); "
                "see docs/reg_pat_samples.log.\n")
        for slug in sorted(VERIFIED_NONMATCHING_SITS):
            f.write("  - %s\n" % slug)
        f.write("\n== PER-SIT RESULTS ==\n")
        for r in results:
            if r["accepted"]:
                f.write("[ACCEPT] %s  ->  %s/%s.txt\n"
                        % (r["url"], RECORDS_DIR, r["slug"]))
            else:
                f.write("[REJECT] %s  (%s)\n"
                        % (r["url"], "; ".join(r["reasons"])))
        f.write("\n== SUMMARY ==\n")
        f.write("scanned:  %d\n" % len(results))
        f.write("accepted: %d\n" % len(accepted))
        f.write("rejected: %d\n" % len(rejected))
    return len(accepted), len(rejected)


# -------------------------------------------
# MAIN
# -------------------------------------------
def main():
    # this script lives in scripts/, one level below ms_dlp/ where docs/ and
    # raw_data_records/ live; anchor cwd there so the relative paths resolve
    # regardless of where the script is invoked from.
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))
    os.makedirs(DOCS_DIR, exist_ok=True)
    # start from a clean records dir: if it already exists, remove its contents
    # (so SITs excluded or rejected since a prior run never linger as stale
    # files); create it fresh if it does not exist.
    if os.path.isdir(RECORDS_DIR):
        shutil.rmtree(RECORDS_DIR)
    os.makedirs(RECORDS_DIR)

    # 1. enumerate every SIT definition page from the index.
    slugs = list_sit_slugs()

    # 2. fetch + classify all pages in parallel.
    results = classify_all(slugs)

    # 3. write a summary record for every accepted SIT.
    n_written = 0
    for r in results:
        if r["accepted"]:
            write_record(r)
            n_written += 1
    print("[records] wrote %d summaries to %s/" % (n_written, RECORDS_DIR))

    # 4. write the provenance + per-SIT decision log.
    accepted, rejected = write_log(results)
    print("[log] %s : scanned=%d accepted=%d rejected=%d"
          % (LOG_FILE, len(results), accepted, rejected))


if __name__ == "__main__":
    main()
