import os
import sys

# given the rel_path, list all files and their file length in bytes
# arrange all records in descending order.
# it returns a 2-d array of the structure [ [fpath1, size1],...,[fpath_k,sizek]]
def get_file_list(rel_path):
	files = []
	for entry in os.scandir(rel_path):
		if entry.is_file():
			path = os.path.join(rel_path, entry.name)
			path = path.replace('\\', '/')
			size = entry.stat().st_size
			files.append([path, size])
	files.sort(key=lambda x: (-x[1], x[0]))
	return files

# given a file list returned by get_file_list(). compute the total size.
def get_total_size(file_list):
	return sum(item[1] for item in file_list)

# compute the intersection of the two file list.
# two items are regarded as equal if their filename is equal
# the structure of each file list is like the output of get_file_list().
def get_intersection(file_list1, file_list2):
	set1 = {item[0] for item in file_list1}
	set2 = {item[0] for item in file_list2}
	return list(set1.intersection(set2))

# partition the file list generated by get_file_list() into
# n parts.  We assume the file list is in descending order of file size
# Algorithm: first compute the total size of the file list and
#  then compute the target size for each partition.
#  go through the list of files one by one, and distribute them
#  to the partition. Once each partition is filled (total size
#  greater than the target size), we do not feed files into it anymore.
# Return a 3D array where each element is a file list.
def partition_file_list(file_list, n):
	partitions = [[] for _ in range(n)]
	partition_sizes = [0] * n
	for file_item in file_list:
		min_index = min(range(n), key=lambda i: partition_sizes[i])
		partitions[min_index].append(file_item)
		partition_sizes[min_index] += file_item[1]
	return partitions

# verify the computed partitions are ok.
# 1. verify each pair of partition list are disjoint (by calling
#    get_intersection
# 2. compute the UINION of all entries of partitions and
#    then sort them by descending order of file size
#    check if it's equal to file_list.
def check_partition_result(file_list, partitions):
	n = len(partitions)
	for i in range(n):
		for j in range(i + 1, n):
			intersect = get_intersection(partitions[i], partitions[j])
			if len(intersect) > 0:
				print(f"ERROR: Partitions {i} and {j} overlap! Intersection: {intersect}")
				sys.exit(1)
	union_list = []
	for p in partitions:
		union_list.extend(p)
	union_list.sort(key=lambda x: (-x[1], x[0]))
	if union_list != file_list:
		print("ERROR: The union of all partitions does not equal the original file list!")
		sys.exit(1)
	print("Partition check passed successfully.")

# partition is structured as the output of get_file_list
# write the list of files into "binexec_p_id.dat".
# Note that you need to chop off all "../" so the
# first word in each file path is prefix given: "binexec_merged128k".
def write_partition(partition, id, prefix):
	filename = f"binexec_p{id}.dat"
	with open(filename, 'w') as f:
		for file_item in partition:
			path = file_item[0]
			# Continue to chop off parts until we see the prefix
			while not path.startswith(prefix):
				idx = path.find('/')
				if idx == -1:
					print(f"ERROR: Could not find prefix '{prefix}' in path '{file_item[0]}'")
					sys.exit(1)
				path = path[idx + 1:]
			f.write("data/samples/" + path + "\n")

# given the relative path (to the current directory)
# compute the total size of all files in that rel_path
# partition the list of files into n files with
# the best efforts to make each partition has
# the roughly the same total size of files
# name the partition files "binexec_p1", ..., "bin_exec_pn"
def gen_parts(n, rel_path, prefix):
	#1. retrive the file list from rel_path
	file_list = get_file_list(rel_path)
	
	#2. call partition_file_list to partition
	partitions = partition_file_list(file_list, n)
	
	#3. call check_partition_result to verify correctness
	check_partition_result(file_list, partitions)
	
	#4. print the statistics such as total number of files and total size
	total_size = get_total_size(file_list)
	print(f"Total files: {len(file_list)}, Total size: {total_size} bytes")
	
	#5. print the stats of each partition: total number of files and total size
	for i in range(n):
		p_size = get_total_size(partitions[i])
		print(f"Partition {i}: {len(partitions[i])} files, {p_size} bytes")
		write_partition(partitions[i], i, prefix)

# -------- MAIN ---------------
n_parts = 8
gen_parts(n_parts, "../../../samples/binexec_merged128k", "binexec_merged128k")
