/* Created 06/11/2025
*/
//! This gadget is used for computing discharged signatures from
//! the step queue generated by discharge_adv.rs.
//! It should be only included in the LAST STEP of discharing a word.
//! Main workflow: 
//! (1) check the step queue of the subsigs, an empty step implies
//!     subsig discharged (for most sub-sigs). Details to handle
//!     on subsigs-groups, counter constraints etc. Need to apply
//!     tri-logic rules on different kinds of subsigs.
//! (2) Given the evaluation order (dnf) in advice, retrieve subsig
//!     tri-logic values and compute their composition. Which is
//!     the tri-logic value of the discharge state of subsig. 
//!     Only those with a definite "no" are labled as discharged.
//!     -> output is the list of discharged sigs.

use std::{rc::{Rc}, cell::{RefCell},
//	collections::{HashMap,HashSet}
	marker::{PhantomData},
	any::Any,
};
use ark_ff::{PrimeField};

use crate::gadgets::{
//	commons::{gen_m_table,check_arr_eq,encode_cols,decode_cols
//		,new_const_var, check_imply, encode_2col_var, encode_2col_var_adv,
//		encode_2col, encode_cols_var, check_arr_eq_arr, encode_cols_var_adv, 
//		check_eq},
//	db::{assert_logup, verify_encoded_table, assert_well_formed_sorted},
	traits::{
		Container, ComponentAdvice,
	//	Col,
		IDX_WORD, IDX_INP,IDX_DATA,
		IDX_OUP, 
		//IDX_SI_INP, IDX_SI_OUP,
		IDX_SI_DATA,
	},
	discharge_adv::{StepQueue,DischargeAdvCapacity},
};
use folding_schemes::folding::foldpot::{
	sigma_ir1cs::{
		SigmaGadget,
		WitnessSigmaIR1CSVar,WitnessSigmaIR1CSConfig, 
		NdAdvice,
		Capacity
	},
	container_config::{ContainerConfig},
	//circuits_super::field_to_usize,
};
use ark_r1cs_std::{
	fields::{ 
		fp::FpVar, 
		//FieldVar
	},
	//alloc::AllocVar,
	//eq::EqGadget,
	//R1CSVar,
};
use ark_relations::r1cs::{SynthesisError,ConstraintSystemRef};
// -----------------------------------------------
//		Structs
// -----------------------------------------------
/// Capacity of the gadget
#[derive(Clone,Debug,PartialEq)]
pub struct ComputeSigAdvCapacity{
	/// how many subsigs 
	pub subsigs: usize,

	/// how many sigs 
	pub sigs: usize,

	/// max_nibble_len, used to determine inp_step_queue_obj
	pub max_nibble_len: usize,

	/// perc_pats_in_trace (used to be compatibile for the
	/// step_queue_res). It determines the related lookup argument size. 
	pub perc_pats_in_trace: usize, 
}

/// Advice for the Compute Sig Gadget.
#[derive(Clone,Debug)]
pub struct ComputeSigAdvAdvice<F:PrimeField>{
	/// the statement container object which is serialized to a vector
	/// of statement
	pub stmt_container: Rc<RefCell<Container<F>>>,

	/// capacity
	pub capacity: ComputeSigAdvCapacity,

}

#[allow(dead_code)]
/// This gadget is responsible for computing the discharged
/// SIGS from Subsigs. Note that this gadget should be ONLY included
/// in the last step of discharging a word for saving cost.
#[derive(Clone,Debug)]
pub struct ComputeSigAdvGadget<F:PrimeField>{ 
	/// the capacity
	pub capacity: ComputeSigAdvCapacity,

	// will be set when set_container_cfg is called
	pub cfgs_context: Option<Rc<Vec<ContainerConfig>>>,
	// dummy_cfg is used when cfgs_context is not ready yet
	pub dummy_cfg: ContainerConfig,
	pub my_idx_in_context: Option<usize>,
	_f: PhantomData<F>,
}

// ---------------------------------------------
//            Implementations
// ---------------------------------------------

impl Capacity for ComputeSigAdvCapacity{
	fn can_satisfy(&self, r_other: &Rc<dyn Capacity>) -> bool{
		let other = r_other.as_any().downcast_ref::<ComputeSigAdvCapacity>()
			.expect("downcast err"); 

		self.subsigs >= other.subsigs &&
		self.sigs >= other.sigs
	}

	/// to get around the requirement on Clone trait which require Sized
	/// (which cause trouble why use dyn Capacity in Rc),
	fn clone(&self) -> Rc<dyn Capacity>{
		Rc::new(ComputeSigAdvCapacity{
			subsigs: self.subsigs,
			sigs: self.sigs,
			perc_pats_in_trace: self.perc_pats_in_trace,
			max_nibble_len: self.max_nibble_len,
		})
	}

	/// needed for downcasting for composite gadget mapper
	fn as_any(&self) -> &dyn Any { self }
}

impl <F: PrimeField> NdAdvice for ComputeSigAdvAdvice<F>{
	fn as_any(&self) -> &dyn Any {self}
}

impl <F: PrimeField> ComponentAdvice<F> for ComputeSigAdvAdvice<F>{
	fn get_container(&self)->Rc<RefCell<Container<F>>>{
		self.stmt_container.clone()
	}
}

impl <F: PrimeField> ComputeSigAdvAdvice<F>{
	/// Given the StepQueue (result of bwd_prf) from the DischargeAdvGadget
	/// Generate the list of signatures that are discharged.
	pub fn new(
		_inp_sigs: &Vec<F>,
		_inp_subsigs: &Vec<F>,
		_inp_step_queue: &StepQueue<F>, // the steps_queue from input
		capacity: &ComputeSigAdvCapacity,
	) ->Self{
		let stmt_container = Container::<F>::new("compute_sig_adv_stmt");

		//1. construct subsig_res by checking step_queue

		//2. based on non-deterministic advice of eval order
		// compute sig_res

		//3. allocates the discharged_sigs buffer
		Self{capacity: Clone::clone(capacity), stmt_container}
	}
}

impl <F:PrimeField> ComputeSigAdvGadget<F>{
	pub fn new(
		capacity: &ComputeSigAdvCapacity,
		prev_cfgs: &Vec<ContainerConfig>,
	)
	-> Self{
		//1. create the dummy input and dummy container config.
		let pats_len = capacity. perc_pats_in_trace 
			* capacity.max_nibble_len/100;
		let zero = F::zero();	
		let subsigs = vec![zero; capacity.subsigs];
		let sigs = vec![zero; capacity.sigs];
		let inp_steps_queue = vec![zero; pats_len*2];
		let dis_cap = DischargeAdvCapacity{
			max_nibble_len: capacity.max_nibble_len,
			subsigs: capacity.subsigs,
			avg_pats_per_subsig: 4, //it's ok to put a sample value here
			perc_pats_in_trace: capacity.perc_pats_in_trace
		};
		let inp_steps_queue_obj = StepQueue::parse_from(&inp_steps_queue,
			&dis_cap);
		let dummy_adv = ComputeSigAdvAdvice::new(
			&sigs, &subsigs, &inp_steps_queue_obj, Clone::clone(&capacity) 
		);
		let mut vec_cfg = prev_cfgs.clone();
		vec_cfg.push(dummy_adv.stmt_container.borrow().get_cfg());
		ContainerConfig::adjust_locations(&mut vec_cfg);
		//even it's false, it's good enough for generating statement_structure
		let dummy_cfg = vec_cfg[vec_cfg.len()-1].clone(); //it's the last one

		Self{_f: PhantomData, capacity: Clone::clone(capacity), 
			cfgs_context: None,
			my_idx_in_context: None, dummy_cfg
		}
	}

	/// return None if not set yet.
	pub fn get_container_cfg(&self)->Option<ContainerConfig>{
		if self.my_idx_in_context.is_some(){
			let idx = self.my_idx_in_context.unwrap();
			let cfg = self.cfgs_context.as_ref().unwrap().as_ref()[idx].clone();
			Some(cfg)
		}else{
			Some(self.dummy_cfg.clone())
		}
	}

}

impl <F:PrimeField> SigmaGadget<F> for ComputeSigAdvGadget<F>{
	/// set the container cfg. This is only needed for those gadgets
	/// in SED approach
	fn set_container_cfg(&mut self, cfgs_context: Rc<Vec<ContainerConfig>>, idx: usize){
		self.cfgs_context = Some(cfgs_context);
		self.my_idx_in_context = Some(idx);
	}
	/// Get the instructions for build its statement.
	/// NOTE: this is only needed for those used in SedGadgetMapper.
	/// Others are handled by legacy code in their gadget mapper.
	fn get_stmt_map_instructions(&self)->Vec<(i32, usize, usize, usize)>{
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let res = cfg.gen_stmt_map_instructions();
		res
	}

	/// return the sizes of inp/oup/data to append to the
	/// buffer of GadgetMapper.
	fn get_to_add_size(&self)->(usize, usize, usize){
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let to_add = cfg.get_to_add_size();
		for i in 0..3 {assert!(to_add[i+1] == to_add[4+i]);}

		(to_add[IDX_INP], to_add[IDX_OUP], to_add[IDX_DATA])
	}

	fn est_cost(&self)->usize{
		//TODO: refine formula in real data later
		let est = self.capacity.get_pat_loc_len() * 1000;

		est
	}

	fn get_msg_size(&self) -> (usize, usize, usize, usize){
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let to_add = cfg.get_to_add_size();
		let stat_len = (IDX_WORD..IDX_SI_DATA+1).collect::<Vec<usize>>()
			.iter().map(|i| to_add[*i]).sum();
		//TODO: needs a separate container for msg3, and need to
		//determine msg2 then.
		(stat_len, 0, 2, 0)
	}

	fn gen_msg1(&self, _stmt_vec: &Vec<F>, _v_idx: &Vec<(usize,usize)>) 
		-> Vec<F>{
		vec![] // dummy
	}

	fn gen_msg3(&self, _stmt_vec: &Vec<F>, _stmt_idx: 
		&Vec<(usize,usize)>, 
		_msg1_vec: &Vec<F>, _idx_msg1: usize, _len_msg1: usize,
		_msg2_vec: &Vec<F>, _idx_msg2: usize, _len_msg2: usize) -> Vec<F>{
		vec![]
	}

	fn assert_msg3(&self, i: usize, cs: ConstraintSystemRef<F>, 
		wtns: &WitnessSigmaIR1CSVar<F>, wtns_cfg: &WitnessSigmaIR1CSConfig) 
		-> Result<(), SynthesisError>{
		//REMOVE LATER -----------
		let n1 = cs.num_constraints(); 
		//REMOVE LATER ----------- ABOVE
		//1. retrive the statement instance and get all parts
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let _stmt = Container::<FpVar<F>>::load_from(i, wtns_cfg, wtns, &cfg)?;
		let _r1 = wtns.msg2[0].clone();
		let _r2 = wtns.msg2[1].clone();

		//REMOVE LATER -----------
		println!("DEBUG USE 9999: num_cons: {}", cs.num_constraints()-n1);
		//REMOVE LATER ----------- ABOVE

		Ok(())
	}


}

impl ComputeSigAdvCapacity{
	/// same as the function of DischargeAdvCapacity - looks like
	/// no better way of refactoring. Just dupplicate it here.
	pub fn get_pat_loc_len(&self)->usize{
		let pats_len = self.perc_pats_in_trace 
			* self.max_nibble_len/100;
		pats_len
	}
}



