/* Created 06/11/2025. 
   Implementation resumed 06/27/2025.
   Complete: 07/16/2025
   Revised: 08/11/2025 to take two subsig list from prior gadgets
   one for case sensitive and one for ignore case.
*/
//! This gadget is used for computing discharged signatures from
//! the step queue generated by discharge_adv.rs.
//! Main workflow: 
//! (1) check the step queue of the subsigs, an empty step implies
//!     subsig discharged (for most sub-sigs). Details to handle
//!     on subsigs-groups, counter constraints etc. Need to apply
//!     tri-logic rules on different kinds of subsigs.
//! (2) Given the evaluation order (dnf) in advice, retrieve subsig
//!     tri-logic values and compute their composition. Which is
//!     the tri-logic value of the discharge state of subsig. 
//!     Only those with a definite "no" are labled as discharged.
//!     -> output is the list of discharged sigs.

use rayon::iter::{
	IntoParallelRefIterator,
	ParallelIterator,IntoParallelIterator
//	, IndexedParallelIterator
};
use std::{rc::{Rc}, cell::{RefCell}, sync::{Arc},
	collections::{HashMap},
	marker::{PhantomData},
	any::Any,
};
use ark_ff::{PrimeField};

use crate::gadgets::{
	commons::{encode_cols_better, gen_m_table, encode_cols_var_adv_better,
		new_const_var, check_eq, new_var},
	db::{assert_logup, 
		//verify_encoded_table, assert_well_formed_sorted
	},
	traits::{
		Container, ComponentAdvice,
		Col,
		IDX_WORD, IDX_INP,IDX_DATA, 
		IDX_DISCHARGED_SIGS,
		IDX_OUP, 
		//IDX_SI_INP, IDX_SI_OUP,
		IDX_SI_DATA,
	},
	discharge_adv::{StepQueue,DischargeAdvCapacity,StepQueueType},
};
use data_processor::{
	type_def::{SubsigStepStore,TriVal,SubsigInfoStore,CompOp,SubSigType,
		ClamavSig},
	clam_db::{RANGE2,ID_ENCODED_NORMAL_STEP, ID_ENCODED_LAST_STEP,RANGE2_BIT,
		ID_COMP_OP, ID_COMP_NUM, ID_COMP_SUBSIG,ID_MIN_REQUIRED,
		ID_SUBSIG_TYPE, ID_SUBSIG_IGC},
	hex_acdfa::HexACDFA,
};
use folding_schemes::folding::foldpot::{
	sigma_ir1cs::{
		SigmaGadget,
		WitnessSigmaIR1CSVar,WitnessSigmaIR1CSConfig, 
		NdAdvice,
		Capacity,
		DischargeSigInfo,
	},
	container_config::{ContainerConfig},
	circuits_super::field_to_usize,
};
use ark_r1cs_std::{
	fields::{ 
		fp::FpVar, 
		FieldVar
	},
	//alloc::AllocVar,
	eq::EqGadget,
	R1CSVar,
	boolean::Boolean,
};
use ark_relations::r1cs::{SynthesisError,ConstraintSystemRef};
// -----------------------------------------------
//		Structs
// -----------------------------------------------
/// Capacity of the gadget
#[derive(Clone,Debug,PartialEq)]
pub struct ComputeSigAdvCapacity{
	/// how many subsigs 
	pub subsigs: usize,

	/// how many sigs 
	pub sigs: usize,

	/// max_nibble_len, used to determine inp_step_queue_obj
	pub max_nibble_len: usize,

	/// basis_pats_in_trace (used to be compatibile for the
	/// step_queue_res). It determines the related lookup argument size. 
	pub basis_pats_in_trace: usize, 

	/// percentage of subsigs that are components of SubsigCounterConstraint
	/// e.g. (1|2|3)>4,2 requires that there are at least 5 matches
	/// of either 1,2,3 (some with multiple matches) and there are
	/// at least 2 distinct matches (e.g., 5 matches of just subsig 1 is not ok).
	/// Real data for linux binexec dataset: 
	/// max_subsigs (for discharging a file):  1026, max_ratio 16.666668
	/// avg_subsigs:  401.2398676592225 avg_ratio 7.11235321401159
	/// It's the max value needed for perc_comp_subsigs is 17 for binexec data set.
	pub perc_comp_subsigs: usize,
}

/// Advice for the Compute Sig Gadget.
#[derive(Clone,Debug)]
pub struct ComputeSigAdvAdvice<F:PrimeField>{
	/// the statement container object which is serialized to a vector
	/// of statement
	pub stmt_container: Rc<RefCell<Container<F>>>,

	/// capacity
	pub capacity: ComputeSigAdvCapacity,
}

#[allow(dead_code)]
/// This gadget is responsible for computing the discharged
/// SIGS from Subsigs. Note that this gadget should be ONLY included
/// in the last step of discharging a word for saving cost.
#[derive(Clone,Debug)]
pub struct ComputeSigAdvGadget<F:PrimeField>{ 
	/// the capacity
	pub capacity: ComputeSigAdvCapacity,

	// will be set when set_container_cfg is called
	pub cfgs_context: Option<Rc<Vec<ContainerConfig>>>,
	// dummy_cfg is used when cfgs_context is not ready yet
	pub dummy_cfg: ContainerConfig,
	pub my_idx_in_context: Option<usize>,
	_f: PhantomData<F>,
}

// ---------------------------------------------
//            Implementations
// ---------------------------------------------

impl Capacity for ComputeSigAdvCapacity{
	fn can_satisfy(&self, r_other: &Rc<dyn Capacity>) -> bool{
		let other = r_other.as_any().downcast_ref::<ComputeSigAdvCapacity>()
			.expect("downcast err"); 

		self.subsigs >= other.subsigs &&
		self.sigs >= other.sigs &&
		self.max_nibble_len>= other.max_nibble_len &&
		self.basis_pats_in_trace>= other.basis_pats_in_trace &&
		self.perc_comp_subsigs >= other.perc_comp_subsigs
	}

	/// to get around the requirement on Clone trait which require Sized
	/// (which cause trouble why use dyn Capacity in Rc),
	fn clone(&self) -> Rc<dyn Capacity>{
		Rc::new(ComputeSigAdvCapacity{
			subsigs: self.subsigs,
			sigs: self.sigs,
			basis_pats_in_trace: self.basis_pats_in_trace,
			max_nibble_len: self.max_nibble_len,
			perc_comp_subsigs: self.perc_comp_subsigs,
		})
	}

	/// needed for downcasting for composite gadget mapper
	fn as_any(&self) -> &dyn Any { self }
}

impl <F: PrimeField> NdAdvice for ComputeSigAdvAdvice<F>{
	fn as_any(&self) -> &dyn Any {self}
}

impl <F: PrimeField> ComponentAdvice<F> for ComputeSigAdvAdvice<F>{
	fn get_container(&self)->Rc<RefCell<Container<F>>>{
		self.stmt_container.clone()
	}
}

impl <F: PrimeField> ComputeSigAdvAdvice<F>{
	/// Given the StepQueue (result of bwd_prf) from the DischargeAdvGadget
	/// Generate the list of signatures that are discharged.
	pub fn new(
		acdfa_id_cs: u32,
		acdfa_id_igc: u32,
		inp_sigs: &Vec<F>,
		inp_subsigs_cs: &Vec<F>,
		inp_subsigs_igc: &Vec<F>,
		discharge_infos: &Vec<DischargeSigInfo>, //must match inp_sigs
					//extracting the dnf to the concat of inp_subsigs
		sq_res_cs: &Rc<RefCell<Container<F>>>, // the steps_queue from the DischargeAdv
		sq_res_igc: &Rc<RefCell<Container<F>>>, // the steps_queue from the DischargeAdv
		capacity: &ComputeSigAdvCapacity,
		subsig_store_info_cs: &SubsigStepStore,
		subsig_store_info_igc: &SubsigStepStore,
		subsig_extra_info_cs: &SubsigInfoStore,
		subsig_extra_info_igc: &SubsigInfoStore,
		v_sig_obj: &Vec<Arc<ClamavSig>>, //needs to cover all inp_sigs
		sig_to_id: &HashMap<String,usize>,
	) ->Self{
		let stmt_container = Container::<F>::new("compute_sig_adv_stmt");

		//1. evaluate "atomic" subsigs based on sq_res 
		println!("DEBUG USE 301: inp_subsigs_cs.len: {}, inp_subsigs_igc.len: {}", inp_subsigs_cs.len(), inp_subsigs_igc.len());
		assert!(inp_subsigs_cs.len()==inp_subsigs_igc.len());
		assert!(inp_subsigs_cs.len()<=capacity.subsigs, 
			"inp_subsigs_cs.len: {} should be <= capacity.subsigs: {}",
			inp_subsigs_cs.len(), capacity.subsigs);
		assert!(inp_sigs.len()<=capacity.sigs);
		let pad = vec![F::zero(); capacity.subsigs-inp_subsigs_cs.len()];
		let pad2 = vec![F::zero(); capacity.sigs-inp_sigs.len()];
		let dummy_di = DischargeSigInfo{
				sig_name: "none".to_string(),
				b_success: false,
				min_cost: 0,
				min_dnf_id: 0,
				subsig_ids: vec![0],
				subsig_igc: vec![false]
			}; 
		let discharge_info = [ &vec![dummy_di ;pad2.len()][..], 
			&discharge_infos[..]].concat();
		assert!(discharge_info.len()==capacity.sigs);

		//1.1 case sensitive 
		let inp_subsigs_cs = [&pad[..], &inp_subsigs_cs[..]].concat();
		let inp_sigs = [&pad2[..], &inp_sigs[..]].concat();
		let (eval_res_combo_cs, raw_res_cs) = 
			Self::gen_eval_subsig_by_sq_combo(false, -2, //case sensitive
			&inp_subsigs_cs, sq_res_cs, &capacity, subsig_store_info_cs);
		stmt_container.borrow_mut().add_container(eval_res_combo_cs);

		//1.2 ignore case
		let inp_subsigs_igc = [&pad[..], &inp_subsigs_igc[..]].concat();
		let (eval_res_combo_igc, raw_res_igc) = 
			Self::gen_eval_subsig_by_sq_combo(true, -1, //case sensitive
			&inp_subsigs_igc, sq_res_igc, &capacity, subsig_store_info_igc);
		stmt_container.borrow_mut().add_container(eval_res_combo_igc);


		//2. based on non-deterministic advice of eval order
		let (synthesis_res_combo, subsig_res) = 
			Self::gen_synthesis_subsig_combo(
			acdfa_id_cs, acdfa_id_igc,
			&inp_subsigs_cs, 
			&raw_res_cs, &raw_res_igc,
			&capacity, 
			subsig_store_info_cs, 
			subsig_extra_info_cs, subsig_extra_info_igc);
		stmt_container.borrow_mut().add_container(synthesis_res_combo);

		//3. based on the sysntehsis resout of subsigs
		let sig_res_combo = Self::gen_discharge_sig_combo(
			&inp_sigs, 
			&inp_subsigs_cs, 
			&subsig_res, 
			&capacity, 
			v_sig_obj,
			&discharge_info, 
			sig_to_id,
		);
		stmt_container.borrow_mut().add_container(sig_res_combo);

		//3. allocates the discharged_sigs buffer
		Self{capacity: Clone::clone(capacity), stmt_container}
	}

	/// generate the evaluation results for atomic subsigs using
	/// step queue. The basic idea is to examin the last step reached
	/// for a subsig. If it is the max step as defined (and there are
	/// valid locations), the result is Maybe, otherwise the result is
	/// False.
	/// Return (res_combo, raw_eval_result)
	/// -- see the paper definition or approx_eval_pm_ bounds_subsig in clamav.rs.
	fn gen_eval_subsig_by_sq_combo(
		b_igc: bool,
		offset_discharge: i32,
		inp_subsigs: &Vec<F>,
		sq_res: &Rc<RefCell<Container<F>>>, //already sorted on subsig_step
		capacity: &ComputeSigAdvCapacity,
		subsig_store_info: &SubsigStepStore,
	)->(Rc<RefCell<Container<F>>>,Vec<F>){
		//0. init data
		let (zero,one) = (F::zero(), F::one());
		let tname = if b_igc {"eval_res_combo_igc"} 
			else {"eval_res_combo_cs"};
		let res = Container::<F>::new(tname);
		assert!(inp_subsigs.len()==capacity.subsigs);
		let sname = if b_igc {"discharge_adv_stmt_igc"}
			else {"discharge_adv_stmt_cs"};
		let sq_res = sq_res.borrow().duplicate_as_external_adv(
			offset_discharge,
			Some(format!("{} bwd_steps_queue sq_res2",sname)),
			Some("sq_res".to_string())); //so later we do not have to create copy
										 //in validate.

		//1. extract subsig, and its last step from sq_res
		let vec_subsig = sq_res.get_container("subsig").unwrap().borrow().to_vec();
		let vec_step = sq_res.get_container("step").unwrap().borrow().to_vec();
		let vec_encoded= sq_res.get_container("encoded").unwrap().borrow().to_vec();
		let vec_sid_step= sq_res.get_container("si_step").unwrap().borrow().to_vec();
		assert!(vec_subsig.len()==vec_step.len());
		assert!(inp_subsigs.len()==capacity.subsigs);
	
		//the following loop are based on the assumption that
		//sq_res is already sorted on (subsig-step), and
		//its subsig is exactly the inp_subsigs
		let (n,n2) = (inp_subsigs.len(), vec_subsig.len());
		let mut vec_last_step= vec![zero;n];
		let mut inp_subsig_encoded = vec![zero;n]; //corresponds to inp_subsig 
		vec_last_step[n-1] = vec_step[n2-1];
		assert!(inp_subsigs[n-1]==vec_subsig[n2-1]);
		inp_subsig_encoded[n-1]=vec_encoded[n2-1];
		assert!(inp_subsigs.contains(&zero), 
			"inp_subigs needs one dummy 0 entry");
		let mut cur_idx = n-2;
		let mut v_idx = n2-1;
		for j in 1..n2{//from last to first
			v_idx = n2-j;
			if vec_subsig[v_idx]!=vec_subsig[v_idx-1]{
				assert!(inp_subsigs[cur_idx]==vec_subsig[v_idx-1]);
				vec_last_step[cur_idx]=vec_step[v_idx-1];
				inp_subsig_encoded[cur_idx]=vec_encoded[v_idx-1];
				cur_idx -=1;
			}
			if cur_idx==0 {break;}
		}
		for j in 0..v_idx{//verify the rest are zero
			assert!(vec_subsig[j].is_zero() || vec_subsig[j]==inp_subsigs[cur_idx+1]);	
		}
		//now set the zero entries
		while cur_idx>0{
			assert!(inp_subsigs[cur_idx]==zero);
			inp_subsig_encoded[cur_idx]=vec_encoded[0];
			cur_idx-=1;
		}

		//2. extract the max_step for subsig
		let v_false = F::from(TriVal::False as u8);
		let v_maybe = F::from(TriVal::Maybe as u8);
		let mut vec_res = vec![v_false; n];
		let mut sid_last_step= vec![zero; n];
		for i in 0..n{
			if inp_subsigs[i]==zero{
				//vec_res[i] = F::from(TriVal::False as u8);
				vec_res[i] = F::zero();
			}else{
				let info = subsig_store_info.subsig_to_steps
					.get(&field_to_usize(&inp_subsigs[i])).expect(
					&format!("cannot find info for subsig: {}", inp_subsigs[i]));
				let max_step = F::from(info.vec_pm_bounds.len() as u64);
				assert!(max_step>=vec_last_step[i]);
				let b_last_step = max_step==vec_last_step[i];
				vec_res[i] = if b_last_step {v_maybe} else {v_false};
				let tag = if b_last_step {ID_ENCODED_LAST_STEP} else
					{ID_ENCODED_NORMAL_STEP};
				let sid = SubsigStepStore::gen_step_tbl_id(
					inp_subsig_encoded[i], tag);
	
				sid_last_step[i] = sid;
			}
		}

		//3. proof step1: assert that (encoded,subsig, last_step,sid_last_step) 
		// is the valid
		//from sq_res. only need one-direction lookup, since if there
		//are subsigs missed from sq_res, they won't show up in the
		//final evaluation result anyway (and cannot be discharged).
		//it's the loss of prover,and cannot affect soundness (but likley
		//raise false alarm). So it's ok to do 1-direction lookup.
		//We actually do tuple (inp_subsig_encoded, inp_subsig, last_step)
		//to futher bind inp_subsig with inp_subsig_encoded.
		assert!(vec_subsig[0]==zero, "need to have at least one dummy");
		let src= encode_cols_better( vec![&inp_subsig_encoded[..],
			&inp_subsigs[..], &vec_last_step[..], &sid_last_step[..]],
			vec![0,1,2,3]);
		let dst_sel = (0..n2).into_par_iter().map(|i|{
			if i==n2-1{one} else{
				if vec_subsig[i]==vec_subsig[i+1] {zero} else {one}
			}
		}).collect::<Vec<F>>();
		let dst_combined = encode_cols_better(vec![&vec_encoded[..],
			&vec_subsig[..], &vec_step[..], &vec_sid_step[..]], vec![0,1,2,3]);
		let dst = dst_combined.iter().zip(dst_sel.iter()).map(|(a,b)|
			*a * *b).collect::<Vec<F>>();
		let mtbl_last_step = gen_m_table(&src, &dst);
		let sid_m_tbl_last_step = vec![zero; mtbl_last_step.len()];

		//4. proof step2: assert that res is correct regarding that
		//sid_last_step == sid_max_step. This does not need any proof
		//generated. on the validator side, use encoded info to do the
		//verification.

		//5. add the columns (last_step, res)
		assert!(vec_res.len()==n);
		let frg = F::from(RANGE2);
		res.borrow_mut().add_container(Rc::new(RefCell::new(sq_res)));
		res.borrow_mut().add_col(Col::new(inp_subsigs.clone(), 
			"inp_subsig", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec![frg;n], "sid_inp_subsig", 
			IDX_SI_DATA));
		res.borrow_mut().add_col(Col::new(inp_subsig_encoded, 
			"inp_subsig_encoded", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec![zero;n], "sid_inp_subsig_encoded", 
			IDX_SI_DATA));
		res.borrow_mut().add_col(Col::new(vec_last_step, "last_step", IDX_DATA));
		res.borrow_mut().add_col(Col::new(sid_last_step, "sid_last_step", 
			IDX_SI_DATA));
		res.borrow_mut().add_col(Col::new(vec_res.clone(), 
			"subsig_raw_eval", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec![frg;n], "sid_subsig_raw_eval", IDX_SI_DATA));
		res.borrow_mut().add_col(Col::new(mtbl_last_step, "mtbl_last_step", 
			IDX_DATA));
		res.borrow_mut().add_col(Col::new(sid_m_tbl_last_step, 
			"sid_mtbl_last_step", IDX_SI_DATA));
		(res, vec_res)
	}

	/// Given the raw evaluation result for each subsig,
	/// return the synthesis result, based on subsig type.
	/// It evaluates all 3 possible outcomes: (1) regular subsig -
	///    which is the raw result, (2) counter constraint
	///    (3) result for component subsigs.
	/// then pick the final result from the three.
	/// the column "subsig_final_result" is the real evaluation result
	/// for a subsig.
	/// see accpets_approx_pm_bounds() in clamav.rs for the processing logic
	/// Return (ProofCombo, FinalEvalResult for the inp_subsigs padded)
	///
	/// Note that raw_result has two versions: (1) context sensitive (cs)
	/// and (2) IGC (ignore case). First, we have to pick up the
	/// value based on b_igc of each subsig and merge the raw_result_cs
	/// and raw_result_igc into one raw_result, and then the synthesis 
	/// can be done.
	fn gen_synthesis_subsig_combo(
		acdfa_id_cs: u32, 
		acdfa_id_igc: u32, 
		inp_subsigs: &Vec<F>,
		raw_result_cs: &Vec<F>, //one to one corresponding to inp_subsig, TriVal
		raw_result_igc: &Vec<F>, 
		capacity: &ComputeSigAdvCapacity,
		subsig_store_info: &SubsigStepStore,
		subsig_store_extra_info_cs: &SubsigInfoStore,
		subsig_store_extra_info_igc: &SubsigInfoStore,
	)->(Rc<RefCell<Container<F>>>,Vec<F>){
		//0. retrieve data 
		let n1 = inp_subsigs.len(); //capacity num_subsigs
		assert!(n1==capacity.subsigs);
		let (zero,one) = (F::zero(), F::one());
        let max_val:usize = (1<<RANGE2_BIT) - 1;
        let max = F::from(max_val as u64);
		let res = Container::<F>::new("synthesis_res_combo");

		//0.5 - added step - merge raw_result_cs and raw_result_igc
		let tbl_id_start = F::from(1u64<<32) * F::from(ID_SUBSIG_IGC);
		let (v_igc, v_sid_igc): (Vec<F>, Vec<F>) = inp_subsigs
			.par_iter().map(|f_subsig_id|{
			let subsig_id = field_to_usize(f_subsig_id); 
			if subsig_id==0{ //subsig dummy 0, treated as case sensitive
							//when later generating ID or retrieve info
				(zero, zero)
			} else{
				let info = subsig_store_info.subsig_to_steps
					.get(&subsig_id)
					.expect(&format!("cannot locate rec: {}", subsig_id));

				let tbl_id = tbl_id_start + F::from(subsig_id as u64);	
				let igc = if info.igc {one} else {zero};
				(igc, tbl_id)
			}
		}).unzip();
		assert!(raw_result_cs.len()==raw_result_igc.len());
		assert!(raw_result_cs.len()==v_igc.len());
		assert!(v_igc.len()==n1);
		let raw_result = (0..raw_result_cs.len()).collect::<Vec<usize>>()
			.into_iter().map(|i|{
			if v_igc[i].is_one() {raw_result_igc[i]} else {raw_result_cs[i]}
		}).collect::<Vec<F>>();

		//1. prepare the result of general_regex
		let gen_regex_res = raw_result;
		assert!(gen_regex_res.len()==inp_subsigs.len());
		let map_gen_regex_res = inp_subsigs.iter()
			.zip(gen_regex_res.iter()).map(|(sig,res)|{
			let u_sig = field_to_usize(sig);
			(u_sig, *res)
		}).collect::<HashMap<usize, F>>();

		//2. prepare the result for counter_constraint 
		// the structure for each subsig is
		// (num, op, counter_res) where counter_res is defined using
		// logic: case op
		// NONE => Maybe (this is actually don't care value)
		// LT => !raw_res
		// EQ => if num!=0 {res} else {!res}
		// GT => res
		// We need to tab num and op appropriate usingly ID_COMP_OP
		//  and ID_COMP_NUM so that we can check them in lookup table
		let mut vec_type = vec![zero; n1]; 
		let mut vec_op = vec![zero; n1];
		let mut vec_num = vec![zero; n1];
		let mut vec_counter_res = vec![zero; n1]; //result for counter constraint 
		let mut vec_sid_op = vec![zero; n1];
		let mut vec_sid_num = vec![zero; n1];
		let vec_sid_counter_res = vec![zero; n1]; //no need to check 
												  //as res is generated in circ
		let mut vec_sid_type = vec![zero; n1];
		//we use simple for loop here as subsig num is small
		for i in 0..n1{
			let subsig = inp_subsigs[i];
			let f_subsig = field_to_usize(&subsig);
			let (op, num, subsig_type, acdfa_id) = if subsig.is_zero(){
				//NOTE: subsig 0 is treated as context sensitive
				//Maybe value
				(CompOp::NONE as u8, 0, 0, acdfa_id_cs)
			}else{
				let b_igc = v_igc[i].is_one();
				let subsig_store_extra_info = 
					if b_igc {subsig_store_extra_info_igc}
					else {subsig_store_extra_info_cs};
				let info = subsig_store_extra_info
					.subsig_to_rec.get(&field_to_usize(&subsig))
					.expect(&format!("cannot find step info for: {}", subsig));
				let acdfa_id = if b_igc {acdfa_id_igc} else {acdfa_id_cs};
				(info.comp_op, info.comp_num, info.subsig_type, acdfa_id)
			};
			let c_op = CompOp::from(op);
			//for input_subsig 0, dummy value for raw_res is 0
			//treat it like Maybe
			let raw_res = if gen_regex_res[i].is_zero() {TriVal::Maybe}
				else {TriVal::from(field_to_usize(&gen_regex_res[i]) as u8)};
			let count_res = match c_op{
				CompOp::NONE => raw_res,
				CompOp::LT => !raw_res,
				CompOp::EQ => if num!=0 {raw_res} else {!raw_res},
				CompOp::GT => raw_res,
			};
			let sid_op: F = SubsigInfoStore::gen_info_tbl_id(acdfa_id, 
				f_subsig, ID_COMP_OP);  
			let sid_num: F = SubsigInfoStore::gen_info_tbl_id(acdfa_id, 
				f_subsig, ID_COMP_NUM);  
			vec_op[i] = F::from(c_op as u8);
			vec_num[i] = F::from(num as u32);
			vec_counter_res[i] = F::from(count_res as u8);
			vec_sid_op[i] = sid_op;
			vec_sid_num[i] = sid_num;
			vec_type[i] = F::from(subsig_type as u8);
			vec_sid_type[i] = SubsigInfoStore::gen_info_tbl_id(acdfa_id,
				f_subsig, ID_SUBSIG_TYPE);
		}

		//3. prepare the result for the subsig_count_constraint
		// see accepts_approx_pm_bounds() handling of SubsigCountConstraint
		// collect the res of true, maybe, false on subcomponents
		// res = Ture if cnt_tru>min_required, 
		// False if cnt_true+cnt_maybe<min_required
		//
		// Idea: since the vec_components is not fixed, construct the
		// following tables:
		// (1) ssc_prf_tbl of the following structure. It COVERS ONLY
		//   those subsigs which has the SubsigCounterConstraint tag
		//   (subsig, comp_subsig_encoded, comp_subsig,
		//			raw_res, cnt_true, cnt_false, ssc_res)
		//   Here each subsig has at least 1 entry of comp_subsig_encoded
		//   the last is the MAX entry which ensures the "full retrieval"
		//   of its comp_subsig from database
		// We could have another table for last row for each subsig
		// to compute ssc_res, but given that the table is already
		// very small, we'll skip that second table and wasite a bit constraints
		// here, because  REAL DATA shows that: 
		// max_ratio is the ratio of those components being a part of another 
		// SubsigCountConstraint.
		// max_subsigs (for discharging a file):  1026, max_ratio 16.666668
		// avg_subsigs:  401.2398676592225 avg_ratio 7.11235321401159
		//
		// (2) ssc_res table which has the following structure, skip the
		// subsig column (as it's already there in combo)
		//  (subsig, ssc_type, ssc_res)
		//  the res is set to don't care if it's type is not SubsigCountConstraint
		// otherwise, we lookup the ssc_es in the ssc_prf_tbl

		// 3.1 construct the ssc_prf_tbl (for SubsigCounterConstraint ONLY!) 
		let factor = F::from(1u32 << RANGE2_BIT);
        let max_val:usize = (1<<RANGE2_BIT) - 1;
        let _max = F::from(max_val as u64);
		let frg = F::from(RANGE2);

		let mut scc_prf_subsig = vec![]; //scc_prf stands for subsig_count_constraint
		let mut scc_prf_comp_subsig_encode = vec![];  //encoded version with id 
		let mut scc_prf_comp_subsig = vec![];  //encoded version with id 
		let mut scc_prf_min_req = vec![];
		let mut scc_prf_raw = vec![]; //raw eval result for comp_subsig
		let mut scc_prf_cnt_true = vec![]; //current count for subsig
		let mut scc_prf_cnt_maybe = vec![]; //current count for subsig
		let mut scc_prf_row_res = vec![]; //current res at each row (take the one at max)
		let mut scc_prf_abs_diff1 = vec![]; //absolute value of cnt_true-min_req
		let mut scc_prf_abs_diff2 = vec![]; //absolute value of 
					//min_req - (cnt_true + cnt_maybe) - 1
				

		let mut sid_scc_prf_subsig = vec![]; 
		let mut sid_scc_prf_comp_subsig_encode = vec![];  
		let mut sid_scc_prf_comp_subsig = vec![];  
		let mut sid_scc_prf_min_req = vec![];
		let mut sid_scc_prf_raw = vec![]; 
		let mut sid_scc_prf_cnt_true = vec![]; 
		let mut sid_scc_prf_cnt_maybe = vec![]; 
		let mut sid_scc_prf_row_res = vec![]; 
		let mut sid_scc_prf_abs_diff1 = vec![];
		let mut sid_scc_prf_abs_diff2 = vec![];

		let mut vec_scc_res = vec![zero;n1]; //will be updated 
		let vec_sid_scc_res = vec![zero;n1]; //don't care because
									//vec_scc_res is computed.

		for i in 0..n1{
			//3.1.1 retrieve extra info
			let subsig = inp_subsigs[i];
			if subsig.is_zero(){
				vec_scc_res[i] = F::from(TriVal::Maybe as u8);
				continue;
			}
			let igc = v_igc[i].is_one();
			let acdfa_id = if igc {acdfa_id_igc} else {acdfa_id_cs};
			let subsig_store_extra_info = 
				if igc {subsig_store_extra_info_igc}
				else {subsig_store_extra_info_cs};
			let extra_info = subsig_store_extra_info
					.subsig_to_rec.get(&field_to_usize(&subsig))
					.expect(&format!("Can't find info for subsig: {}", subsig));
			if extra_info.subsig_type
				!=SubSigType::SubsigCountConstraint as u8{continue;}

			//3.1.2 insert entries
			let mut vec_comps = extra_info.component_subsigs.clone();
			vec_comps.push(max_val as usize);
			let min_req = extra_info.min_required;
			let mut cnt_true =0;
			let mut cnt_maybe = 0;
			for j in 0..vec_comps.len(){
				scc_prf_subsig.push(subsig);
				sid_scc_prf_subsig.push(zero); //don't care as it will be looked up

				let f1 = F::from((j+1) as u32); //starts from 1
                let f2 = F::from(vec_comps[j] as u64);
                let encoded = f1 + f2*factor;
				scc_prf_comp_subsig_encode.push(encoded);
				let tbl_id = SubsigInfoStore::gen_info_tbl_id::<F>(acdfa_id, 
					field_to_usize(&subsig), ID_COMP_SUBSIG); //comp_subsig BELONGS 
															 //to vec_comp of subsig
				sid_scc_prf_comp_subsig_encode.push(tbl_id);

				scc_prf_comp_subsig.push(f2);
				sid_scc_prf_comp_subsig.push(frg);

				scc_prf_min_req.push(F::from(min_req as u64));
				let tbl_id = SubsigInfoStore::gen_info_tbl_id::<F>(acdfa_id, 
					field_to_usize(&subsig), ID_MIN_REQUIRED); 
				sid_scc_prf_min_req.push(tbl_id); 
			
				let raw_res = if j<vec_comps.len()-1{
					*map_gen_regex_res.get(&vec_comps[j]).unwrap()
				}else{//for max: it's 0 - don't care
					F::zero()
				};
				// if dummy value set tri_raw_res as Maybe (don't care)
				// but here we do need its in-table value to be 0
				// so that later when we do lookup, we can save some
				// boolean cond var cost. because set selector to 0 (in mul)
				// make things easier. note for max it will not impact
				// cnt_true and cnt_maybe.
				let tri_raw_res = if raw_res.is_zero() {TriVal::False}
					else {TriVal::from(field_to_usize(&raw_res) as u8)};

				if tri_raw_res==TriVal::True{cnt_true+=1}
				else if tri_raw_res==TriVal::Maybe{cnt_maybe+=1};
				//do nothing for false as our logic does not need it

				//this corresonds to the logic in data_processor/src/clama.rs
				//accepts_approx_pm_bounds()
				let res = if cnt_true>=min_req{
					TriVal::True //for sure
				} else if cnt_true + cnt_maybe < min_req{
					TriVal::False //for sure
				} else {
					TriVal::Maybe //not for sure
				};
				let res = if j<vec_comps.len()-1{F::from(res as u8)} else {
					//copy from last
					scc_prf_row_res[scc_prf_row_res.len()-1]
				};

				let abs_diff1 = if cnt_true >= min_req {cnt_true - min_req}
					else {min_req - cnt_true};
				let abs_diff2 = if cnt_true + cnt_maybe < min_req {
					min_req - (cnt_true + cnt_maybe + 1)
				}else { cnt_true + cnt_maybe + 1 - min_req};
					

				scc_prf_raw.push(raw_res);
				sid_scc_prf_raw.push(zero); //don't care as it will be looked up
				scc_prf_cnt_true.push(F::from(cnt_true as u64));
				sid_scc_prf_cnt_true.push(zero); //don't care as it is computed
				scc_prf_cnt_maybe.push(F::from(cnt_maybe as u64));
				sid_scc_prf_cnt_maybe.push(zero); //don't care as it is computed
				scc_prf_row_res.push(res);
				sid_scc_prf_row_res.push(zero); //don't care as it is computed

				scc_prf_abs_diff1.push(F::from(abs_diff1 as u64));
				sid_scc_prf_abs_diff1.push(frg);
				scc_prf_abs_diff2.push(F::from(abs_diff2 as u64));
				sid_scc_prf_abs_diff2.push(frg);
				
				vec_scc_res[i] = res; //only the last row is valid
			}
		}

		let n2 = capacity.get_scc_prf_size();
		assert!(scc_prf_subsig.len()<=n2, "Adjust perc_comp_subsig in Config! Needed scc_prf len: {} < current_tuples: {}", n2, scc_prf_subsig.len());
		let pad = vec![F::zero(); n2-scc_prf_subsig.len()];
		let pad2 = vec![frg; n2-scc_prf_subsig.len()];
		scc_prf_subsig = [&pad[..], &scc_prf_subsig[..]].concat();
		scc_prf_comp_subsig_encode = [&pad[..], &scc_prf_comp_subsig_encode[..]].concat();
		scc_prf_comp_subsig = [&pad[..], &scc_prf_comp_subsig[..]].concat();
		scc_prf_min_req = [&pad[..], &scc_prf_min_req[..]].concat();
		scc_prf_raw = [&pad[..], &scc_prf_raw[..]].concat(); //it's padding value will be 1
		scc_prf_cnt_true = [&pad[..], &scc_prf_cnt_true[..]].concat();
		scc_prf_cnt_maybe = [&pad[..], &scc_prf_cnt_maybe[..]].concat();
		scc_prf_row_res = [&pad[..], &scc_prf_row_res[..]].concat();
		scc_prf_abs_diff1 = [&pad[..], &scc_prf_abs_diff1[..]].concat();
		scc_prf_abs_diff2 = [&pad[..], &scc_prf_abs_diff2[..]].concat();

		sid_scc_prf_subsig = [&pad[..], &sid_scc_prf_subsig[..]].concat();
		sid_scc_prf_comp_subsig_encode = [&pad[..], &sid_scc_prf_comp_subsig_encode[..]]
			.concat();
		sid_scc_prf_comp_subsig = [&pad[..], &sid_scc_prf_comp_subsig[..]].concat();
		sid_scc_prf_min_req = [&pad[..], &sid_scc_prf_min_req[..]].concat();
		sid_scc_prf_raw = [&pad[..], &sid_scc_prf_raw[..]].concat();
		sid_scc_prf_cnt_true = [&pad[..], &sid_scc_prf_cnt_true[..]].concat();
		sid_scc_prf_cnt_maybe = [&pad[..], &sid_scc_prf_cnt_maybe[..]].concat();
		sid_scc_prf_row_res = [&pad[..], &sid_scc_prf_row_res[..]].concat();
		sid_scc_prf_abs_diff1= [&pad2[..], &sid_scc_prf_abs_diff1[..]].concat();
		sid_scc_prf_abs_diff2= [&pad2[..], &sid_scc_prf_abs_diff2[..]].concat();
		assert!(vec_scc_res.len()==n1);
		assert!(vec_sid_scc_res.len()==n1);

		let col2d = [
			&scc_prf_subsig, &scc_prf_comp_subsig_encode, &scc_prf_comp_subsig,
			&scc_prf_min_req, &scc_prf_raw, &scc_prf_cnt_true, 
			&scc_prf_cnt_maybe, &scc_prf_row_res,
			&scc_prf_abs_diff1, &scc_prf_abs_diff2];
		let sid_col2d = [ 
			&sid_scc_prf_subsig, &sid_scc_prf_comp_subsig_encode, &sid_scc_prf_comp_subsig,
			&sid_scc_prf_min_req, &sid_scc_prf_raw, &sid_scc_prf_cnt_true,
			&sid_scc_prf_cnt_maybe, &sid_scc_prf_row_res,
			&sid_scc_prf_abs_diff1, &sid_scc_prf_abs_diff2
		];
		for c in col2d {assert!(c.len()==n2);}
		for c in sid_col2d {assert!(c.len()==n2);}

		//3.2 lookup (comp_subsig, raw_res) in the gen_regex_res
		// to prove the validity of raw_res for the comp_subsig
		// ignore the max entries
		let src_s_r = encode_cols_better(
			vec![&scc_prf_comp_subsig[..],&scc_prf_raw[..]],
			vec![0,1]
		);
		let src_sel = scc_prf_comp_subsig.iter().map(|s|
			if *s==max {zero} else {one}
		).collect::<Vec<F>>();
		let src_s_r = src_s_r.iter().zip(src_sel.iter()).map(|(a,b)|
			*a * *b).collect::<Vec<F>>();
		assert!(inp_subsigs[0].is_zero(), "we need one dummy subsig entry. Increase config.subsigs"); //so that we can save the selector
		let dest_s_r = encode_cols_better(
			vec![&inp_subsigs[..], &gen_regex_res[..]],
			vec![0,1]
		);
		let mtbl_comp_score = gen_m_table(&src_s_r, &dest_s_r);

		//3.3 and 3.4 which builds the log up and verify abs_diff
		//no need to build any additional (their SID cols already build
		//earlier

		//3.5 build vec_scc_res and perform logup
		//vec_scc_res has the same length of inp_subsigs
		//if its type is the SubsigCounterConstraint, then its value
		//is available in scc_prf_row_res (last row with comp_subsig=max).
		//otherwise we set its value to be don't care (Maybe), because
		//it will not be retrieved anyway.
		//and generate the corresponding logsups (based on vec_type)
		let var_scc = F::from(SubSigType::SubsigCountConstraint as u8); // 2
		let src_sel = vec_type.iter().map(|t|
			if *t==var_scc {one} else {zero}
		).collect::<Vec<F>>();

		assert!(vec_scc_res.len()==n1 && src_sel.len()==n1);
		let src = encode_cols_better(
			vec![&inp_subsigs[..], &vec_scc_res[..]],
			vec![0,1]
		);
		let src = src.iter().zip(src_sel.iter()).map(|(a,b)|
			*a * *b).collect::<Vec<F>>();

		let dst = encode_cols_better(
			vec![&scc_prf_subsig[..], &scc_prf_row_res[..]],
			vec![0,1]
		);
		let dst_sel = scc_prf_comp_subsig.iter().map(|c| 
			if *c==max {one} else {zero}
		).collect::<Vec<F>>();
		let dst = dst.iter().zip(dst_sel.iter()).map(|(a,b)|
			*a * *b).collect::<Vec<F>>();
		let mtbl_find_scc_res = gen_m_table(&src, &dst);

		//4. build the final table. idea is simple: we
		// use conditional selection to determine based on type
		let var_regular = F::from(SubSigType::GeneralRegex as u8); // 0
		let is_scc= src_sel; //saving cost
		let is_reg = vec_type.iter().map(|t|
			if *t==var_regular {one} else {zero}
		).collect::<Vec<F>>();
		let mut vec_subsig_final_res = vec![zero; n1];
		assert!(vec_scc_res.len()==n1);
		assert!(gen_regex_res.len()==n1);
		assert!(vec_counter_res.len()==n1);
		for i in 0..n1{//since it's small about 1k entries, just single thread
			vec_subsig_final_res[i] = if is_scc[i].is_one() {vec_scc_res[i]}
			else{
				if is_reg[i].is_one() {gen_regex_res[i]} 
				else {vec_counter_res[i]}
			}
		}
		let vec_sid_subsig_final_res = vec![zero; n1];//no need to check

		//5. construct container
		//5.1 the counter constraint part
		res.borrow_mut().add_col(Col::new(vec_op, "vec_op", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec_sid_op, "sid_op", IDX_SI_DATA));
		res.borrow_mut().add_col(Col::new(vec_num, "vec_num", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec_sid_num, "sid_num", IDX_SI_DATA));
		res.borrow_mut().add_col(Col::new(vec_counter_res, 
			"vec_counter_res", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec_sid_counter_res, 
			"sid_counter_res", IDX_SI_DATA));
		res.borrow_mut().add_col(Col::new(vec_type, "vec_type", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec_sid_type, "vec_sid_type", 
			IDX_SI_DATA));

		//5.2 the subsig counter constraint part
		let names = vec![
				"scc_prf_subsig",
				"scc_prf_comp_subsig_encode",
				"scc_prf_comp_subsig",
				"scc_prf_min_req",
				"scc_prf_raw",
				"scc_prf_cnt_true",
				"scc_prf_cnt_maybe",
				"scc_prf_row_res",
				"scc_prf_abs_diff1",
				"scc_prf_abs_diff2",
		];
		for i in 0..col2d.len(){
			res.borrow_mut().add_col(Col::new(col2d[i].clone(), names[i], IDX_DATA));
			res.borrow_mut().add_col(Col::new(sid_col2d[i].clone(), 
				&format!("sid_{}",names[i]), IDX_SI_DATA));
		}
		assert!(mtbl_comp_score.len()==n1);
		res.borrow_mut().add_col(Col::new(mtbl_comp_score, 
			"mtbl_comp_score", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec![frg; n1], 
			"sid_mtbl_comp_score", IDX_SI_DATA));

		assert!(mtbl_find_scc_res.len()==n2);
		res.borrow_mut().add_col(Col::new(mtbl_find_scc_res, 
			"mtbl_find_scc_res", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec![frg; n2], 
			"sid_mtbl_find_scc_res", IDX_SI_DATA));

		assert!(vec_scc_res.len()==vec_sid_scc_res.len());
		res.borrow_mut().add_col(Col::new(vec_scc_res, 
			"vec_scc_res", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec_sid_scc_res, 
			"vec_sid_scc_res", IDX_SI_DATA));

		//5.3 add the final result
		res.borrow_mut().add_col(Col::new(vec_subsig_final_res.clone(), 
			"vec_subsig_final_res", IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec_sid_subsig_final_res, 
			"vec_sid_subsig_final_res", IDX_SI_DATA));

		//5.3.5 add the v_igc and v_sid_igc
		res.borrow_mut().add_col(Col::new(v_igc, "v_igc", IDX_DATA));
		res.borrow_mut().add_col(Col::new(v_sid_igc, "v_sid_igc", 
			IDX_SI_DATA));

		(res, vec_subsig_final_res)
	}

	/// Given the final result of subsig,
	/// use the EvalDNF information to discharge sig.
	/// Basic idea: each sig has a collection of EvalDNF (see type_def.rs)
	/// E.g., (1|2) & (3|4)
	/// It has two DNFs: (1|2) and (3|4)
	/// the Word Discharge Info has already pointed which one has
	/// lower cst to discharge, e.g., let it be (1|2).
	/// the combo needs to show that both subsigs 1 and 2 are 
	/// discharged (as False).
	/// 
	/// Proof Structure (table)
	/// sig - eval_dnf_id - step - count - subsig - res
	/// where the (subsig,res) is from the gen_synsis_subsig_combo.
	/// HERE: all sigs need to be discharged (they will be
	///   the list of sigs to be reported as "discharged").
	fn gen_discharge_sig_combo(
		inp_sigs: &Vec<F>,
		inp_subsigs: &Vec<F>,
		subsig_result: &Vec<F>,
		capacity: &ComputeSigAdvCapacity,
		v_sigs: &Vec<Arc<ClamavSig>>, //required to COVER inp_sigs
		discharge_infos: &Vec<DischargeSigInfo>, //must match inp_sigs
					//extracting the dnf to the concat of inp_subsigs
		sig_to_id: &HashMap<String,usize>,
	)->Rc<RefCell<Container<F>>>{
		let zero = F::zero();
		let frg = F::from(RANGE2);
		let res = Container::<F>::new("sig_res_combo");
		let n = capacity.subsigs;
		assert!(inp_subsigs.len()==n);
		assert!(subsig_result.len()==n); 
		assert!(inp_sigs.len()==capacity.sigs);

		//1. from the discharge info, build the proof table
		// sig - eval_dnf_id - step - count - subsig (expect res to be
		// TriVal::False)
		// Special note: the subsig/res in this talbe is DIFFERENT
		// from the subsig/res in the gen_synthesis_subsig_res (because
		// here, we do NOT include the sub-components of a subsig (thus
		// resulting a shorter list of subsigs and with different structure)
		// we have to run a LOOKUP to retrieve the result values from
		// the previous combo in step 2.
		// NOTE: we pad the size to #subsigs because in real data
		// vast majority are regular_regex 
		// (not Counterh of SubsigCounterConstraint)
		let pad_len = capacity.sigs - discharge_infos.len();
		let dummy_di = DischargeSigInfo{
				sig_name: "none".to_string(),
				b_success: false,
				min_cost: 0,
				min_dnf_id: 0,
				subsig_ids: vec![0],
				subsig_igc: vec![false]
			}; 
		let discharge_infos = [ 
			&vec![dummy_di ;pad_len][..], 
			&discharge_infos[..]
		].concat();
		assert!(discharge_infos.len()==inp_sigs.len());
		for i in 0..discharge_infos.len() {
			let name = &discharge_infos[i].sig_name;
			let sig_id = if name =="none" {zero} else {
				F::from(*sig_to_id.get(name)
					.expect(&format!("cannot find sig: {}", name)) as u64)
			};
			assert!(sig_id == inp_sigs[i]);
		}
		let info_ts = discharge_infos.par_iter().map(|info|{
			let (sig_id, vec_ssid) = if info.sig_name=="none" {//dummy case 
				//don't genreate [1] instead generate 0
				(zero, vec![])
			}else{
				let sig_objs = v_sigs.iter().filter(|s| s.name==info.sig_name)
					.map(|s| s.clone())//low cost of Arc clone
					.collect::<Vec<Arc<ClamavSig>>>();
				assert!(sig_objs.len()==1, "cannot find or duplicate entries for {}", info.sig_name);
				let sig_obj = &sig_objs[0];
				let sig_id = sig_to_id.get(&info.sig_name)
					.expect(&format!("cannot find sig: {}", info.sig_name));
				let sig_id = F::from(*sig_id as u64);
				let dnf_id = info.min_dnf_id;
				let vssid = sig_obj.eval_dnf.vec_disjunc[dnf_id].iter().map(
					|x| F::from((*x+1) as u64)).collect::<Vec<F>>();
				(sig_id, vssid)
			};
			let eval_dnf_id = F::from(info.min_dnf_id as u64);
			let eval_count = F::from(vec_ssid.len() as u64);
			vec_ssid.iter().enumerate().map(|(i,ssid)|
				(eval_dnf_id, F::from(i as u64), eval_count, *ssid, sig_id)
			).collect::<Vec<(F,F,F,F,F)>>()
		}).flatten().collect::<Vec<(F,F,F,F,F)>>();
		let pad = vec![(zero,zero,zero,zero,zero); n-info_ts.len()];
		let info_ts = [&pad[..], &info_ts[..]].concat();
		assert!(info_ts.len()==n);
		let v_dnf_id = info_ts.iter().map(|t| t.0).collect::<Vec<F>>();
		let v_dnf_step = info_ts.iter().map(|t| t.1).collect::<Vec<F>>();
		let v_dnf_count = info_ts.iter().map(|t| t.2).collect::<Vec<F>>();
		let v_real_subsigs = info_ts.iter().map(|t| t.3).collect::<Vec<F>>();
		let v_sigs = info_ts.iter().map(|t| t.4).collect::<Vec<F>>();

		let info_id:u32 = 0x98882405; 
		let f1 = F::from(info_id);
		let factor = F::from(0x100000000 as u64); //32-bit 
		let v_sid_dnf_id = vec![frg; n];
		let v_sid_dnf_step = vec![frg; n];
		let v_sid_dnf_count= (0..n).collect::<Vec<usize>>().into_iter().map(|i|{
			let dnf_id = v_dnf_id[i];
			let sig_id = v_sigs[i];
			let tbl_id = f1*factor*factor*factor + sig_id * factor * factor
				+ dnf_id * factor;

			tbl_id
		}).collect::<Vec<F>>();

		let info_id:u32 = 0x99992405; 
		let f1 = F::from(info_id);
		let v_sid_real_subsigs= (0..n).collect::<Vec<usize>>()
			.into_iter().map(|i|{
			let dnf_id = v_dnf_id[i];
			let sig_id = v_sigs[i];
			let tbl_id = f1*factor*factor*factor + sig_id * factor * factor
				+ dnf_id * factor + v_dnf_step[i];

			tbl_id
		}).collect::<Vec<F>>();
		let v_sid_sigs = vec![frg; n];

		//2. Now prove that each sig in v_sigs is discharged as false
		//2.1 check that all subsig of a sig is well covered, i.e.,
		// the dnf_step is increasing, it starts from 0 and its
		// last step is equal to dnf_count
		// we do not have to generate the proof for it.
		// note that there is NO need to prove v_sigs is sorted,
		// the well formedness already proves the full coverage
		// of the related dnf_subsig for one sig. If there is one sig
		// shows up multiple times, it's costing more on prover but
		// does not affect soundness of proof.

		//2.2 build subsigs from (sig_id, real_subsig) and lookup
		// (subsig, False) in the (vec_subsig, vec_result) from the
		// previous gen_sytneshsis_subsig_result(). This is needed
		// as the structure of subsigs are different between the 
		// two components.
		let mut map = inp_subsigs.into_iter().zip(subsig_result.into_iter()).
			map(|(x,y)| (*x,*y)).collect::<HashMap<F,F>>();
		let f_false = F::from(TriVal::False as u8);
		map.insert(zero, f_false); //for dummy entry
		let mut v_computed_subsig = vec![zero; n];
		for i in 0..n{
			let subsig_id = F::from(HexACDFA::gen_subsig_id_worker(
						field_to_usize(&v_sigs[i]), 
						field_to_usize(&v_real_subsigs[i])
					) as u64);
			let res = map.get(&subsig_id)
				.expect(&format!("cannot find subsig_id: {}", &subsig_id));
			assert!(*res == f_false);
			v_computed_subsig[i] = subsig_id;
		}
		let src = encode_cols_better(
			vec![&v_computed_subsig[..], &vec![f_false; n][..]],
			vec![0,1]
		);
		//pad (0,1) for dummy entry
		let pad_subsigs = [&inp_subsigs[..], &vec![zero][..]].concat();
		let pad_res = [&subsig_result[..], &vec![f_false][..]].concat();
		let dst = encode_cols_better(
			vec![&pad_subsigs[..], &pad_res[..]],
			vec![0,1]
		);
		let mtbl_lk_res = gen_m_table(&src, &dst);

		//3. show that inp_sigs is a subset of v_sigs (covered)
		// where we have proved all v_sigs are discharged
		//note: v_sigs is required to have at least one dummy entry at beginning
		let mtbl_sigs= gen_m_table(&inp_sigs, &v_sigs);


		//4. add data columns into containers
		let names = vec![
				"v_sigs", 
				"v_dnf_id", 
				"v_dnf_step", 
				"v_dnf_count", 
				"v_real_subsigs"
				];
		let col2d = vec![
			v_sigs, 
			v_dnf_id, 
			v_dnf_step, 
			v_dnf_count, 
			v_real_subsigs
		];
		col2d.into_iter().zip(names.iter()).for_each(|(c, n)|{
			res.borrow_mut().add_col(Col::new(c, n, IDX_DATA));
		});
		let col2d_sid = vec![
			v_sid_sigs, 
			v_sid_dnf_id, 
			v_sid_dnf_step, 
			v_sid_dnf_count, 
			v_sid_real_subsigs
		];
		col2d_sid.into_iter().zip(names.iter()).for_each(|(c, n)|{
			res.borrow_mut().add_col(Col::new(c, &format!("sid_{}",n),
				IDX_SI_DATA));
		});
		assert!(mtbl_lk_res.len()==n+1);
		res.borrow_mut().add_col(Col::new(mtbl_lk_res,"mtbl_lk_res",IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec![frg;n+1],"sid_mtbl_lk_res",
			IDX_SI_DATA));
		
		assert!(mtbl_sigs.len()==n);
		res.borrow_mut().add_col(Col::new(mtbl_sigs,"mtbl_sigs",IDX_DATA));
		res.borrow_mut().add_col(Col::new(vec![frg;n],"sid_mtbl_sigs",
			IDX_SI_DATA));
		assert!(inp_sigs.len()==capacity.sigs);
		res.borrow_mut().add_col(Col::new(inp_sigs.clone(),
	 		"discharged_sigs",IDX_DISCHARGED_SIGS)); //no si needed


		res
	}


}

impl <F:PrimeField> ComputeSigAdvGadget<F>{
	pub fn new(
		fsm_id_cs: u32, //determines which combo to retrieve info
		fsm_id_igc: u32, //determines which combo to retrieve info
		capacity: &ComputeSigAdvCapacity,
		prev_cfgs: &Vec<ContainerConfig>,
		store_steps_cs: &SubsigStepStore,
		store_steps_igc: &SubsigStepStore,
		store_extra_info_cs: &SubsigInfoStore,
		store_extra_info_igc: &SubsigInfoStore,
	)
	-> Self{
		//1. create the dummy input and dummy container config.
		let zero = F::zero();	
		let subsigs_cs = vec![zero; capacity.subsigs];
		let subsigs_igc = vec![zero; capacity.subsigs];
		let sigs = vec![zero; capacity.sigs];
		let v_sig_obj: Vec<Arc<ClamavSig>> = vec![]; //empty one
		//make a dummy one
		let discharge_infos = vec![
			DischargeSigInfo{
				sig_name: "none".to_string(),
				b_success: false,
				min_cost: 0,
				min_dnf_id: 0,
				subsig_ids: vec![0],
				subsig_igc: vec![false]
			}; capacity.sigs];

		//2. create the dummy sq_res
		let dis_cap = DischargeAdvCapacity{
			max_nibble_len: capacity.max_nibble_len,
			subsigs: capacity.subsigs,
			avg_active_pats_per_subsig: 2, //it's ok, coz it's not affecting
										  //parse_from
			basis_pats_in_trace: capacity.basis_pats_in_trace,
		};
		let step_q_size = StepQueue::<F>::vec_size(&StepQueueType::Res,
			&dis_cap);
		let sq_res_vec = vec![zero; step_q_size*2];
		let sq_res_obj= StepQueue::parse_from(&sq_res_vec, &dis_cap);
		let sq_res_cs = sq_res_obj.to_container(
			"sq_res2_cs", false, true, true, true,
			&store_steps_cs);
		let sq_res_igc = sq_res_obj.to_container(
			"sq_res2_igc ", false, true, true, true,
			&store_steps_igc);
		let mut sigs_to_id = HashMap::<String,usize>::new();
		sigs_to_id.insert("none".to_string(), 0);


		//3. create advice
		let dummy_adv = ComputeSigAdvAdvice::new(
			fsm_id_cs, 
			fsm_id_igc, 
			&sigs, 
			&subsigs_cs, 
			&subsigs_igc, 
			&discharge_infos,
			&sq_res_cs, 
			&sq_res_igc, 
			Clone::clone(&capacity), 
			store_steps_cs, 
			store_steps_igc, 
			store_extra_info_cs, 
			store_extra_info_igc, 
			&v_sig_obj, 
			&sigs_to_id 
		);
		let mut vec_cfg = prev_cfgs.clone();
		vec_cfg.push(dummy_adv.stmt_container.borrow().get_cfg());

		//4. other routine ops to set up config vec
		ContainerConfig::adjust_locations(&mut vec_cfg);
		//even it's false, it's good enough for generating statement_structure
		let dummy_cfg = vec_cfg[vec_cfg.len()-1].clone(); //it's the last one

		Self{
			_f: PhantomData, 
			capacity: Clone::clone(capacity), 
			cfgs_context: None,
			my_idx_in_context: None, dummy_cfg
		}
	}

	/// return None if not set yet.
	pub fn get_container_cfg(&self)->Option<ContainerConfig>{
		if self.my_idx_in_context.is_some(){
			let idx = self.my_idx_in_context.unwrap();
			let cfg = self.cfgs_context.as_ref().unwrap().as_ref()[idx].clone();
			Some(cfg)
		}else{
			Some(self.dummy_cfg.clone())
		}
	}

	/// validate raw_eval result based on step queue is correct for
	/// each subsig.
	/// COST: 10n1 + 8n2 (n1: num of subsigs, n2: sq_res len which
	///    is determined by discharge_adv::StepQueue::vec_size (perc_pat_in_trace)
	fn validate_eval_subsig_by_sq_combo(&self, 
		eval_res_combo: &Container<FpVar<F>>, 
		r1: FpVar<F>,
		_r2: FpVar<F>,
		cs: ConstraintSystemRef<F>
	) ->Result<(), SynthesisError>{
		//0. retrieve data from combo
		let (zero,one)=(new_const_var(&cs,F::zero()),new_const_var(&cs,F::one()));
		let names = ["inp_subsig", "last_step", "subsig_raw_eval", 
			"inp_subsig_encoded"];
		let cols = names.iter().map(|n|
			eval_res_combo.get_container(n).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let (inp_subsig, last_step, subsig_raw_eval, inp_subsig_encoded) = 
			(&cols[0],&cols[1],&cols[2], &cols[3]);
		let sid_cols = names.iter().map(|n|
			eval_res_combo.get_container(&format!("sid_{}",n))
				.unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let sid_last_step = &sid_cols[1]; //only need to check this
			
		//1. extract subsig, last_step from sq_res 
		let sq_res=eval_res_combo.get_container("sq_res")
			.expect("err get sq_res"); //it's actually 
						//externally refered copy (do not take space)
		let names = ["subsig", "step", "encoded"];
		let cols = names.iter().map(|n| 
			sq_res.borrow().get_container(n).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let (sq_subsig, sq_step, sq_encoded) = (&cols[0], &cols[1], &cols[2]);
		let sq_sid_step = sq_res.borrow().get_container("si_step")
			.unwrap().borrow().to_vec();
		let n2 = cols[0].len();

		//2. proof step1: assert that (encoded, subsig, last_step, sid_last_step) 
		// is the valid
		//from sq_res. only need one-direction lookup, since if there
		//are subsigs missed from sq_res, they won't show up in the
		//final evaluation result anyway (and cannot be discharged).
		//it's the loss of prover,and cannot affect soundness (but likley
		//raise false alarm). So it's ok to do 1-direction lookup
		// COST: 5n1 + 8n2 (where n1 is subsigs, n2 is sq_res length)
		let src= encode_cols_var_adv_better(&vec![&inp_subsig_encoded[..],
			&inp_subsig[..], &last_step[..], &sid_last_step], &vec![0,1,2,3], &r1);
		let dst_sel = (0..n2).into_iter().map(|i|{
			if i==n2-1{one.clone()} else{ 
				sq_subsig[i].is_neq(&sq_subsig[i+1]).unwrap().into() 
			}
		}).collect::<Vec<FpVar<F>>>();
		let dst_combined = encode_cols_var_adv_better(
			&vec![&sq_encoded[..], &sq_subsig[..], &sq_step[..], &sq_sid_step[..]], 
			&vec![0,1,2,3], &r1);
		let dst = dst_combined.iter().zip(dst_sel.iter()).map(|(a,b)|
			a * b).collect::<Vec<FpVar<F>>>();
		let mtbl_last_step = eval_res_combo.get_container("mtbl_last_step")
			.unwrap().borrow().to_vec();
		assert_logup(cs.clone(), &src, &dst, &mtbl_last_step, &r1)?;

		//3. proof step2: verify that eval_res is correct.
		//to save cost: assert eval_res is boolean (either 1 or 0)
		//and then use it to enforce sid_last_step == sid for MAX_STEP
		//COST: 5n1  where n1 is the number of subsigs

		let info_id= F::from(0x23001101u32); //tag to avoid collision
		let f1 = F::from(1u64<<RANGE2_BIT);
        let factor1 = f1*f1*f1*f1*f1; //models encoded
        let factor2 = F::from(1u64<<32); //32-bit
		let part1 = info_id*factor1*factor2 + 
			F::from(ID_ENCODED_NORMAL_STEP)*factor1;
		let part1_alt = info_id*factor1*factor2 + 
			F::from(ID_ENCODED_LAST_STEP)*factor1;
		let part1_normal_var = new_const_var(&cs, part1);
		let part1_last_var = new_const_var(&cs, part1_alt);
		#[cfg(test)]{ assert!(TriVal::False as u8==1u8 && TriVal::Maybe as u8==3);}

		for i in 0..subsig_raw_eval.len(){
			//3.1 NOTE eval has two possible values:
			// subsig_raw_val is ALREADY PROVED to be either ONE of
			// TriVal::False (1), or Trival::Maybe (3)
			// b_last_step should be true when v is 3 (Maybe) and false if v=1.
			let b_last_step = subsig_raw_eval[i].is_neq(&one)?;

			//3.3 retrieve existing tag (note that we've already proved
			//that it is projected from sq_res, and also sq_res has already
			//proved the validity of sid_step - thus it's the VALID step ID
			//already proved).
			let valid_sid = &sid_last_step[i];

			//3.2 build the ACTUAL sid_tag  from subsig_raw_eval
			//as a nondeterministic advice. We'll verify its correctness
			let part1 = b_last_step.select(&part1_last_var, &part1_normal_var)?;
			let sid_act = &part1 + &inp_subsig_encoded[i];
			let diff = &inp_subsig[i]*&(&sid_act - valid_sid);
			check_eq(&diff, &zero, "sid check failed")?; //only required for 
													//non-zero "real" entries
		}


		Ok( () )
	}

	/// validate syntesis of subsig is correct.
	/// COST:  let n = number of subsigs, n2 = scc table size (20% of n at most
	///				in practice)
	/// 29*n + 69*n2 (given n2<20%*n) ==> 43n (number of subsigs)
	///   + additional cs/igc cost 6n = 49n.
	/// in practice: this is 1000 *49 = 49k R1CS
	fn validate_synthesis_subsig_combo(&self, 
		eval_res_combo_cs: &Container<FpVar<F>>, 
		eval_res_combo_igc: &Container<FpVar<F>>, 
		synthesis_res_combo: &Container<FpVar<F>>, 
		r1: FpVar<F>,
		r2: FpVar<F>,
		cs: ConstraintSystemRef<F>
	) ->Result<(), SynthesisError>{
		//0. retrieve data from combo
		let b_debug = true;
		let (zero,one)=(new_const_var(&cs,F::zero()),new_const_var(&cs,F::one()));
        let max_val:usize = (1<<RANGE2_BIT) - 1;
		let max=new_const_var(&cs,F::from(max_val as u64));
		let frg = new_const_var(&cs, F::from(RANGE2));
		let names = ["vec_op", "vec_num", "vec_counter_res", "vec_type"];
		let cols = names.iter().map(|n|
			synthesis_res_combo.get_container(n).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let (vec_op, vec_num, vec_counter_res, vec_type) = (&cols[0], 
			&cols[1], &cols[2], &cols[3]);
		let names = ["sid_op", "sid_num", "vec_sid_type"];
		let sid_cols = names.iter().map(|n|
			synthesis_res_combo.get_container(n).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let (vec_sid_op, vec_sid_num, vec_sid_type) = 
			(&sid_cols[0], &sid_cols[1], &sid_cols[2]); // no need
						//to check sid_counter_res as it's computed in circ
		let v_igc = synthesis_res_combo.get_container("v_igc")
			.unwrap().borrow().to_vec();
		let v_sid_igc = synthesis_res_combo.get_container("v_sid_igc")
			.unwrap().borrow().to_vec();
		let inp_subsigs = eval_res_combo_cs.get_container("inp_subsig")
			.unwrap().borrow().to_vec();
		let n = vec_op.len();
		assert!(vec_num.len()==n && vec_counter_res.len()==n);

		//1 (correspond to gen_synthesis_subsig_combo 0.5)
		//  Validate v_sid_sig and conditional select the value of gen_reg_rex
		//COST: 6n 
		assert!(v_igc.len()==v_sid_igc.len() && v_igc.len()==n);
		assert!(inp_subsigs.len()==n);
		let tbl_id_start = new_const_var(&cs,
			F::from(1u64<<32) * F::from(ID_SUBSIG_IGC));
		for i in 0..n{
			let exp_sid_igc = &tbl_id_start + &inp_subsigs[i];
			let diff = &exp_sid_igc - &v_sid_igc[i];
			let prod = &diff * &inp_subsigs[i];
			check_eq(&prod, &zero, &format!("failed sid_igc at i: {}", i))?;
		}
		let gen_regex_res_cs = eval_res_combo_cs
			.get_container("subsig_raw_eval").unwrap().borrow().to_vec();
		let gen_regex_res_igc = eval_res_combo_igc
			.get_container("subsig_raw_eval").unwrap().borrow().to_vec();
		assert!(gen_regex_res_cs.len()==n && gen_regex_res_igc.len()==n);
		let gen_regex_res = (0..n).collect::<Vec<usize>>().into_iter().map(|i|{
			let b_cs = v_igc[i].is_zero().unwrap();
			b_cs.select(&gen_regex_res_cs[i], &gen_regex_res_igc[i]).unwrap()
		}).collect::<Vec<FpVar<F>>>();

		if b_debug{
			println!("DEBUG USE 6901: compute_sig_gadget: ==== subsig (raw) info ====");
			for i in 0..n{
				println!(" -- i: {}, subsig: {}, res_cs: {}, res_igc: {}, igc: {} => {}", i, inp_subsigs[i].value()?,
					gen_regex_res_cs[i].value()?,
					gen_regex_res_igc[i].value()?,
					v_igc[i].value()?,
					gen_regex_res[i].value()?
				);
			}
		}

		//2. verify the result of counter constraint 
		// the structure for each subsig is
		// (num, op, counter_res) where counter_res is defined using
		// logic: case op
		// NONE => raw_res (note: this is like don't care value anyway) 
		// LT => !raw_res
		// EQ => if num!=0 {raw_res} else {!raw_res}
		// GT => raw_res
		// ------ simplifying the above, we have
		// ct_res = if op==LT || (op=EQ && num==0) {!raw_res}
		//			else {raw_res}
		// consider how to express the if condition:
		// op==EQ && num==0 can be checked using random factor r1 like
		//   (op-EQ) + r1*num == 0 [only when both op==EQ and num==0
		//   it has large probability of equal to zero.
		// So the if condition is:
		//  (op-LT) * ( (op-EQ) + r1 * num ) == 0
		// this costs: 2 + is_eq: 3 = 5 constraints. This looks like
		// the least costly solution. Otherwise raw encoding using Boolean
		// directly costs: 3 is_eq: 6 + one and: 1 + one or: 3 = 10 constraints

		//2.1 verify the validity of vec_op and vec_num (the op is retrieved from
		// the database for the subsig. Mainly we are recomputing
		// their SID using the algorithm of 
		// SubsigInfoStore::gen_info_tbl_id() in clam_db.rs
		// COST: 3n (where n is the number of subsigs)
		let info_id:u32 = 0x13752405; //just random tag to avoid collision
		let f1 = F::from(info_id);
		let factor = F::from(0x100000000 as u64); //32-bit 
		let f1_var = new_const_var(&cs, f1);
		let factor_var = new_const_var(&cs, factor);
		let part1 = &(&f1_var * &factor_var) * &factor_var;
		let piece_op = new_const_var(&cs, F::from(ID_COMP_OP as u32)); 
		let piece_num = new_const_var(&cs, F::from(ID_COMP_NUM as u32)); 
		let piece_type= new_const_var(&cs, F::from(ID_SUBSIG_TYPE as u32)); 
		for i in 0..n{
			let f3 = &inp_subsigs[i];
			let f3_fac = f3 * &factor_var; 
			let prefix = &part1 + &f3_fac;
			let exp_sid_op = &prefix + &piece_op;
			let exp_sid_num = &prefix + &piece_num;
			let exp_sid_type= &prefix + &piece_type;
			check_eq(&exp_sid_op, &vec_sid_op[i], "sid_op check fails")?;
			check_eq(&exp_sid_num, &vec_sid_num[i], "sid_num check fails")?;
			check_eq(&exp_sid_type, &vec_sid_type[i], "sid_type check fails")?;
		}

		//2.2 verify the calculation of counter_res is correct.
		// cost: 9n
		let eq_var = new_const_var(&cs, F::from(CompOp::EQ as u8));
		let lt_var = new_const_var(&cs, F::from(CompOp::LT as u8));
		let three_var = new_const_var(&cs, F::from(3u8));
		let six_var = new_const_var(&cs, F::from(6u8));
		for i in 0..n{
			//2.2.1 compute the condition
			// cost: 5n
			let cond = &(&vec_op[i] - &lt_var) * 
				&(&(&vec_op[i]-&eq_var) + &(&r1 * &vec_num[i]));
			let b_cond = cond.is_zero()?;

			//2.2.2 compute the neg_res
			//we create the using as non-deterministic advice
			//then verify that it's correct. This saves 1 constraint.
			//idea: raw_res is already proved (so we are ensured that
			//  it is either False (1) or Maybe (3).
			// Consider all combinations of two value added up.
			//  False + True = 3, True + False = 3
			//  Maybe + Maybe = 6.
			// These are the ONLY VALID combinations.
			// cost: 2n
			let res_val = gen_regex_res[i].value()?;
			//handle special 0 dummy value for dummy subsig 0
			let tri_res_val = if res_val.is_zero() {TriVal::Maybe}
			else {TriVal::from(field_to_usize(&res_val) as u8)};
			let neg_res_val = (!tri_res_val) as u8;
			let raw_res = &gen_regex_res[i];
			let neg_raw_res = new_var(&cs, F::from(neg_res_val));
			check_eq(&(&(raw_res+&neg_raw_res-&three_var)*
				&(raw_res+&neg_raw_res-&six_var)), &zero, "error checking neg")?;

			//2.2.3 enforce the conditional assignment
			// counter_res = if i_condition {!raw_res} else {raw_res}
			// cost: 3n
			let exp_res = b_cond.select(&neg_raw_res, raw_res)?;
			// ignore subsig 0 case as it's dummy
			check_eq(&(&inp_subsigs[i]*&(&exp_res- &vec_counter_res[i])), 
				&zero, "err counter_res")?;
		}

		//3. the SubsigCountConstraint part
		//n2 is up to 20% of n (subsigs) in practice
		//3.1 retrieve the cols and sid cols, and check validity
		//of sid columns, so that we are checking the validity of comp_subsigs
		//and their min_req by leveraging the database saved in external lkup
		//
		//-- 3.1.0 retrieve data
		//COST: 13*n2 
		let n2 = self.capacity.get_scc_prf_size();
		let names = vec![
			"scc_prf_subsig", "scc_prf_comp_subsig_encode", 
			"scc_prf_comp_subsig",
			"scc_prf_min_req", "scc_prf_raw", "scc_prf_cnt_true",
			"scc_prf_cnt_maybe", "scc_prf_row_res",
			"scc_prf_abs_diff1", "scc_prf_abs_diff2",
		];
		let col2d = names.iter().map(|n|
			synthesis_res_combo.get_container(n).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let sid_names = vec![ "sid_scc_prf_comp_subsig_encode", 
			"sid_scc_prf_comp_subsig", "sid_scc_prf_min_req",
			"sid_scc_prf_abs_diff1", "sid_scc_prf_abs_diff2"
		];
		let sid_col2d = sid_names.iter().map(|n|
			synthesis_res_combo.get_container(n).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let (sid_scc_prf_comp_subsig_encode, sid_scc_prf_comp_subsig, 
			sid_scc_prf_min_req, sid_scc_prf_abs_diff1, sid_scc_prf_abs_diff2)
		= (&sid_col2d[0], &sid_col2d[1], &sid_col2d[2], 
			&sid_col2d[3], &sid_col2d[4]);

		//-- 3.1.1 check the sid columns
		//COST: 8*n2
		let piece_comp = new_const_var(&cs, F::from(ID_COMP_SUBSIG as u32)); 
		let piece_min = new_const_var(&cs, F::from(ID_MIN_REQUIRED as u32)); 

		for i in 0..n2{
			//3.1.1.1 check sid_comp_encode (simulating the computation of gen_info_tbl_id)
			// also the sid_comp_min_required
			let f3 = &col2d[0][i]; //the subsig
			let f3_fac = f3* &factor_var; //factor_var from 2.1 
			let prefix = &part1 + &f3_fac;
			let exp_sid_comp = &prefix + &piece_comp;
			let exp_sid_min = &prefix + &piece_min;
			check_eq(&(f3*&(&exp_sid_comp-&sid_scc_prf_comp_subsig_encode[i])), &zero,
				"sid_comp_encoded err")?;
			check_eq(&(f3*&(exp_sid_min-&sid_scc_prf_min_req[i])), &zero,"sid_min err")?;
			check_eq(&(f3*&(&sid_scc_prf_comp_subsig[i]-&frg)),&zero,"sid_comp_subsig err")?;
			check_eq(&sid_scc_prf_abs_diff1[i], &frg, "sid_abs_diff1 err")?;
			check_eq(&sid_scc_prf_abs_diff2[i], &frg, "sid_abs_diff2 err")?;
		}

		//-- 3.1.2 check the validity of sid_comp_count
		// count is computed from comp_subsit_encode and comp_subsig (which
		// already have range prf).
		// verify count increase by 1 if subsig is the same and 
		// starts from 1 for a new_subsig in the sequence, and 
		// ends with max. This guarantees
		// that the vec_comp are FULLY coverd in scc_prf
		//
		// COST: 15*n2
		let fa_var = new_const_var(&cs, F::from(1u32 << RANGE2_BIT));
		let vec_cnt = col2d[1].iter().zip(col2d[2].iter()).map(|(c1,c2)|{
			c1 - &(c2 * &fa_var)
		}).collect::<Vec<FpVar<F>>>();
		assert!(col2d[0][0].value()?.is_zero(), "scc_prf too small, need 1st entry to be null entry. adjust perc_comp_subsigs in Config!");
		let tri_true:FpVar<F> = 
			new_const_var(&cs, F::from(TriVal::True as u8)).into();
		let tri_maybe:FpVar<F> = 
			new_const_var(&cs, F::from(TriVal::Maybe as u8)).into();
		let tri_false:FpVar<F> = 
			new_const_var(&cs, F::from(TriVal::False as u8)).into();
		let r3 = &r1 * &r1; //it's ok treat the random combination like
							//using r1 as var in a poly.
		for i in 1..n2{
			let subsig = &col2d[0][i];
			let prev_subsig = &col2d[0][i-1];
			let diff = &vec_cnt[i]-&vec_cnt[i-1];
			let diff_sid = subsig-prev_subsig;
			let same_subsig:FpVar<F> = diff_sid.is_zero()?.into(); //1 or 0
			let is_raw_true:FpVar<F> = col2d[4][i].is_eq(&tri_true)?.into();
			let is_raw_maybe:FpVar<F> = col2d[4][i].is_eq(&tri_maybe)?.into();
			//(1) if same_sid needs to enforce diff is one, otherwise don't care
			//(2) requires count to start from 1, if it's not the same_id
			//(3) requires that vec_comp is MAX when it's the last row
			//(4) if last_row, requires cnt_true be set to is_raw_true
			//      and cnt_maybe be set is_raw_maybe
			let eq = 
				&(&same_subsig * &(
					//eq1 part
					&(subsig * &(&diff-&one))  + 
					//eq4 part: it's the prev one + is_raw_true (maye)
					&(&r1*( &col2d[5][i] - &is_raw_true - &col2d[5][i-1])) + 
					&(&r2*( &col2d[6][i] - &is_raw_maybe - &col2d[6][i-1]))
				)) + 
				&(&(&one-&same_subsig) * 
					&(prev_subsig *
					   &(//eq2 part
							&(&vec_cnt[i-1]-&one) +
						//eq 3 part: last row has max in scc_prf_comp_subsig 
						//row 0 should be automatically ok as we checked
						//it's dummy entry subsig #0, which has all 0's.
							&r1*(&(&col2d[2][i-1]-&max)) + 
						//eq 4 part
							&r2*(&(&col2d[5][i]-&is_raw_true))+
							&r3*(&(&col2d[6][i]-&is_raw_maybe))
						)
					) 
				);
			check_eq(&eq, &zero, "failed on count (2 cases: inc by 1 and start from 1), or the check of cnt_true/cnt_maybe ")?;
		}
		//does need to check the very last row for vec_comp is max (well formed)
		//note: guard with with subsig value (if it's 0 - pass check)
		check_eq(&(&col2d[0][n2-1]*&(&col2d[2][n2-1]- &max)), 
			&zero, "check last row on max")?;

		//3.2 lookup (comp_subsig, raw_res) in the gen_regex_res
		// to prove the validity of raw_res for the comp_subsig
		// ignore the max entries
		//
		// COST: n2 +  3*n2 + n2 + n + 2n2 + 3n
		// = 7*n2 + 4*n (where n2 is scc_prf_size and n is subsigs) 
		// in practice n2 is at most 20% of n1.
		let src_s_r = encode_cols_var_adv_better(
			&vec![&col2d[2][..],&col2d[4][..]], //comp_subsig and raw
			&vec![0,1],
			&r1
		);
		let src_sel = col2d[2].iter().map(|s|{//comp_subsig
			let b_eq = s.is_eq(&max).unwrap();
			&one - &(b_eq.into())
		}).collect::<Vec<FpVar<F>>>();
		let src_s_r = src_s_r.iter().zip(src_sel.iter()).map(|(a,b)|
			a * b).collect::<Vec<FpVar<F>>>();
		let dest_s_r = encode_cols_var_adv_better(
			&vec![&inp_subsigs[..], &gen_regex_res[..]],
			&vec![0,1],
			&r1
		);
		let mtbl_comp_score = synthesis_res_combo.get_container("mtbl_comp_score").unwrap().borrow().to_vec();
		assert_logup(cs.clone(), &src_s_r, &dest_s_r, &mtbl_comp_score, &r1)?;


		//3.3. check abs_diff is ok: idea: do the real diff and check
		//their square equal. Note that the sid of abs_diff is already
		//checked earlier.
		//
		//COST: 8*n2
		for i in 0..n2{
			let subsig = &col2d[0][i];
			let diff1 = &col2d[5][i] - &col2d[3][i]; //cnt_true - min_req
			let abs_diff1 = &col2d[8][i];
			let res1 = &diff1*&diff1 - abs_diff1*abs_diff1;
			//enforce those for real entries, i.e., subsig!=0
			check_eq(&(subsig*(&res1-&zero)), &zero, "err on abs_diff1")?;

			//diff2 = min_req - (cnt_maybe + cnt_true + 1)
			let diff2 = &col2d[3][i] - &one - &col2d[5][i] - &col2d[6][i];
			let abs_diff2 = &col2d[9][i];
			let res2 = &diff2*&diff2 - abs_diff2*abs_diff2;
			check_eq(&(subsig*(&res2-&zero)), &zero, "err on abs_diff2")?;
		}


		//3.4 validate the row_res
		//Logic: three cases: 
		//(1) cnt_true - min_req>=0, i.e., abs_diff1 = cnt_true-min_req
		//  <==> True
		//(2) cnt_true + cnt_maybe < min_req, i.e.,
		//     abs_diff2 = min_req - cnt_true - cnt_maybe - 1
		//  <==> False
		//(3) O.t. Maybe
		//Given that n2 is small (in practice up to 20% of 1000 subsigs) = 200
		//we didn't optimize just use boolean selector
		//
		// COST: 9*n2
		for i in 0..n2{
			let b_case1 = (&col2d[5][i] - &col2d[3][i]).is_eq(&col2d[8][i])?;
			let b_case2 = (&col2d[3][i] - &col2d[5][i] - &col2d[6][i] - &one)
				.is_eq(&col2d[9][i])?;
			let exp_res = b_case1.select(&tri_true,
				&b_case2.select(&tri_false, &tri_maybe)?)?;
			let row_res = &col2d[7][i];
			let subsig = &col2d[0][i];
			check_eq(&(subsig*(row_res-exp_res)), &zero, "err on row_res")?;
		}

		//3.5 check the validity of vec_scc_res, leveraging vec_type	
		//COST: n: subsigs, n2: scc_table (which is usually up to 20% of n)
		//  6n + 9*n2
		let vec_scc_res= synthesis_res_combo.get_container("vec_scc_res")
			.unwrap().borrow().to_vec();
		let mtbl_find_scc_res= synthesis_res_combo
			.get_container("mtbl_find_scc_res").unwrap().borrow().to_vec();
		let var_scc = new_const_var(&cs, 
			F::from(SubSigType::SubsigCountConstraint as u8)); //it's 2
		let is_scc= vec_type.iter().map(|t|
			t.is_eq(&var_scc).unwrap()
		).collect::<Vec<Boolean<F>>>();
		let src_sel = is_scc.iter().map(|t| 
			t.clone().into()).collect::<Vec<FpVar<F>>>();
		assert!(vec_scc_res.len()==n && src_sel.len()==n);
		let src = encode_cols_var_adv_better(
			&vec![&inp_subsigs[..], &vec_scc_res[..]],
			&vec![0,1],
			&r1
		);
		let src = src.iter().zip(src_sel.iter()).map(|(a,b)|
			a * b).collect::<Vec<FpVar<F>>>();

		let dst= encode_cols_var_adv_better(//scc_prf_subisg and scc_prf_row_res
			&vec![&col2d[0][..], &col2d[7][..]],
			&vec![0,1],
			&r1
		);
		let dst_sel = col2d[2].iter().map(|c|   
			c.is_eq(&max).unwrap().into() //if comp_subsig eq to max
		).collect::<Vec<FpVar<F>>>();
		let dst = dst.iter().zip(dst_sel.iter()).map(|(a,b)|
			a * b).collect::<Vec<FpVar<F>>>();

		assert_logup(cs.clone(), &src, &dst, &mtbl_find_scc_res, &r1)?;

		//4. VERIFY the final table. idea is simple: we
		// use conditional selection to determine based on type
		//
		// COST: 7n 
		let var_regular = new_const_var(&cs,
			F::from(SubSigType::GeneralRegex as u8)); // 0
		let is_reg = vec_type.iter().map(|t|
			t.is_eq(&var_regular).unwrap()
		).collect::<Vec<Boolean<F>>>();
		assert!(vec_scc_res.len()==n);
		assert!(gen_regex_res.len()==n);
		assert!(vec_counter_res.len()==n);
		let vec_subsig_final_res = synthesis_res_combo
			.get_container("vec_subsig_final_res").unwrap().borrow().to_vec();
		for i in 0..n{//since it's small about 1k entries, just single thread
			let subsig = &inp_subsigs[i];
			let res = is_scc[i].select(&vec_scc_res[i],
				&is_reg[i].select(&gen_regex_res[i],
					&vec_counter_res[i]).unwrap()
			).unwrap();
			check_eq(&(subsig*&(&res-&vec_subsig_final_res[i])),
				&zero, "fail final subsig")?;
		}

		//REMOVE LATER ------------------------
		println!("DEBUG USE 6803 === final result in validate ===");
		for i in 0..n{
			println!(" --i: {}, subsig: {}, res: {}", 
				i, 
				inp_subsigs[i].value()?,
				vec_subsig_final_res[i].value()?);
		}
		//REMOVE LATER ------------------------ ABOVE
		Ok( () )
	}

	/// validate syntesis of subsig is correct.
	///
	/// COST: 2*n1 +  22*n
	/// where (n1 = num of sigs, n = num of subsigs)
	/// in real data: worst case n1 = 300, n = 1000 (=> worst case: 23k)
	fn validate_discharge_sig_combo(&self, 
		eval_res_combo: &Rc<RefCell<Container<FpVar<F>>>>, 
		synthesis_res_combo: &Rc<RefCell<Container<FpVar<F>>>>, 
		discharge_sig_combo: &Rc<RefCell<Container<FpVar<F>>>>, 
		r1: FpVar<F>,
		_r2: FpVar<F>,
		cs: ConstraintSystemRef<F>
	) ->Result<(), SynthesisError>{
		//0. retrieve data from combo
		let b_debug = true;
		let (zero,one)=(new_const_var(&cs,F::zero()),
			new_const_var(&cs,F::one()));
        let max_val:usize = (1<<RANGE2_BIT) - 1;
		let _max=new_const_var(&cs,F::from(max_val as u64));
		let frg = new_const_var(&cs, F::from(RANGE2));
		let names = vec![ "v_sigs", "v_dnf_id", "v_dnf_step", 
			"v_dnf_count", "v_real_subsigs"];
		let cols = names.iter().map(|n|
			discharge_sig_combo.borrow()
				.get_container(n).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let (v_sigs, v_dnf_id, v_dnf_step, v_dnf_count, v_real_subsigs) = (
			&cols[0], &cols[1], &cols[2], &cols[3], &cols[4]);
		let sid_cols = names.iter().map(|n|
			discharge_sig_combo.borrow()
				.get_container(&format!("sid_{}",n)).unwrap().borrow().to_vec()
		).collect::<Vec<Vec<FpVar<F>>>>();
		let (v_sid_sigs, v_sid_dnf_id, v_sid_dnf_step, v_sid_dnf_count, 
			v_sid_real_subsigs) = (&sid_cols[0], &sid_cols[1], &sid_cols[2], 
				&sid_cols[3], &sid_cols[4]);
		let n = v_sigs.len();
		for i in 0..cols.len(){assert!(cols[i].len()==n);}
		for i in 0..cols.len(){assert!(sid_cols[i].len()==n);}

		//1. check the validity of sid cols (sequential as circ does not
		//allow parallelism)
		//
		// Cost: 5n
		let info_id:u32 = 0x98882405; 
		let f1_val = F::from(info_id);
		let factor_val = F::from(0x100000000 as u64); //32-bit 
		let factor = new_const_var(&cs, factor_val);
		let factor2 = &factor * &factor;
		let factor3 = &factor * &factor2;
		let f1 = new_const_var(&cs, f1_val);
		let part1 = &f1 * &factor3;

		let info_id:u32 = 0x99992405; 
		let f1_2 = new_const_var(&cs, F::from(info_id));
		let part1_2 = &f1_2 * &factor3;

		for i in 0..n{
			check_eq(&v_sid_dnf_id[i], &frg, "err sid dnf_id")?;
			check_eq(&v_sid_dnf_step[i], &frg, "erro sid_dnf_step")?;
			check_eq(&v_sid_sigs[i], &frg, "err id_sig")?;

			let sig_prod = &v_sigs[i] * &factor2;
			let dnf_id_prod = &v_dnf_id[i] * &factor;
			let exp_sid_dnf_count = &part1 + &sig_prod + &dnf_id_prod;
			check_eq(&exp_sid_dnf_count, &v_sid_dnf_count[i], 
				"err sid_dnf_cnt")?;

			let exp_sid_real_subsig = &part1_2 + &sig_prod + &dnf_id_prod
				+ &v_dnf_step[i];
			check_eq(&exp_sid_real_subsig, &v_sid_real_subsigs[i],
				"err sid_real_subsig")?;
		}

		//2. Now prove that each sig in v_sigs is discharged as false
		//2.1 check that all subsig of a sig is well covered, i.e.,
		// the dnf_step is increasing, it starts from 0 and its
		// last step is equal to dnf_count.
		// NOTE that the validity of v_dnf_step, ... columns are proved
		// already via v_sid columns in step 1.
		//
		// COST: 6n + 3
		check_eq(&v_sigs[0], &zero, "we require one dummy entry at begin")?;
		for i in 1..n{
			let b_new_row = v_sigs[i].is_neq(&v_sigs[i-1])?;
			let i_new_row: FpVar<F> = b_new_row.into();
			let res = (&i_new_row-&one) * &(//if this is NOT new row then:
				//(a) id_increase by one
				//ignore the case for v_sigs[i]==0
				&(&v_dnf_step[i] - &v_dnf_step[i-1] - &one) * &v_sigs[i]
			) + &i_new_row * &(//if this is NEW row
				//(b) starts from 0
				&(&r1 * &v_dnf_step[i]) + 
				//(c) previous row_step equals to count (for previs sig)
				// note we added one here becaues row_step starts from 0
				// ignore the rule when v_sigs[i-1] is zero
				&(&(&v_dnf_step[i-1] +&one - &v_dnf_count[i-1]) * &v_sigs[i-1])
			);

			check_eq(&res, &zero, "fails well-formed check")?;
		}


		//2.2 build subsigs from (sig_id, real_subsig) and lookup
		// (subsig, False) in the (vec_subsig, vec_result) from the
		// previous gen_sytneshsis_subsig_result(). This is needed
		// as the structure of subsigs are different between the 
		// two components.
		//
		// COST: 8n 
		let bits = RANGE2_BIT;
		let bit_part1 = bits*2/3; //16 for accomodating 64k sigs for bits 24
		let bit_part2 = bits - bit_part1;
		let fac2 = new_const_var(&cs, F::from(1u64<<bit_part2) );
		let f_false = new_const_var(&cs, F::from(TriVal::False as u8));

		let v_computed_subsig = v_sigs.iter().zip(v_real_subsigs.iter())
			.map(|(sig_id, real_subsig_id)| {
				sig_id*&fac2 + real_subsig_id
		}).collect::<Vec<FpVar<F>>>();

		let src = encode_cols_var_adv_better(
			&vec![&v_computed_subsig[..], &vec![f_false.clone(); n][..]],
			&vec![0,1], &r1
		);
		//pad (0,1) for dummy entry
		let inp_subsigs = eval_res_combo.borrow()
			.get_container("inp_subsig").unwrap().borrow().to_vec();
		let subsig_result = synthesis_res_combo.borrow()
			.get_container("vec_subsig_final_res").unwrap()
			.borrow().to_vec();
		let pad_subsigs = [&inp_subsigs[..], &vec![zero][..]].concat();
		let pad_res = [&subsig_result[..], &vec![f_false][..]].concat();
		let dst = encode_cols_var_adv_better(
			&vec![&pad_subsigs[..], &pad_res[..]],
			&vec![0,1], &r1
		);
		let mtbl_lkup_res = discharge_sig_combo.borrow()
			.get_container("mtbl_lk_res").unwrap().borrow().to_vec();
		assert_logup(cs.clone(), &src, &dst, &mtbl_lkup_res, &r1)?;

		//3. show that inp_sigs is a subset of v_sigs (covered)
		// where we have proved all v_sigs are discharged
		//note: v_sigs is shown earlier
		// to have at least one dummy entry at beginning so that just in
		// case inp_sigs has 0 entry.
		//
		//COST: let n1 = num of sigs, n = num of subsigs
		// 2n1 + 3n
		let discharged_sigs = discharge_sig_combo.borrow()
			.get_container("discharged_sigs").unwrap().borrow().to_vec();
		let mtbl_sigs= discharge_sig_combo.borrow()
			.get_container("mtbl_sigs").unwrap().borrow().to_vec();
		assert_logup(cs.clone(), &discharged_sigs, &v_sigs, &mtbl_sigs, &r1)?;

		if b_debug{
			println!("DEBUG USE 6902 === discharged sigs by SED ===");
			for i in 0..discharged_sigs.len(){
				println!(" --i: {}, sig: {}", i, discharged_sigs[i].value()?);
			}
		}
		Ok( () )

	}

}

impl <F:PrimeField> SigmaGadget<F> for ComputeSigAdvGadget<F>{
	fn get_name(&self)->&str {"ComputeSigAdvGadget"}

	/// set the container cfg. This is only needed for those gadgets
	/// in SED approach
	fn set_container_cfg(&mut self, cfgs_context: Rc<Vec<ContainerConfig>>, idx: usize){
		self.cfgs_context = Some(cfgs_context);
		self.my_idx_in_context = Some(idx);
	}
	/// Get the instructions for build its statement.
	/// NOTE: this is only needed for those used in SedGadgetMapper.
	/// Others are handled by legacy code in their gadget mapper.
	fn get_stmt_map_instructions(&self)->Vec<(i32, usize, usize, usize)>{
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let res = cfg.gen_stmt_map_instructions();
		res
	}

	/// return the sizes of inp/oup/data/failed_sigs/discharged_sigs
	/// to append to the
	/// buffer of GadgetMapper.
	fn get_to_add_size(&self)->(usize, usize, usize, usize, usize){
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let to_add = cfg.get_to_add_size();
		for i in 0..3 {assert!(to_add[i+1] == to_add[4+i]);}
		assert!(to_add[IDX_INP]==to_add[IDX_OUP]);
		(to_add[IDX_INP], to_add[IDX_OUP], to_add[IDX_DATA], 0, self.capacity.sigs)
	}

	fn est_cost(&self)->usize{
		//TODO: refine formula in real data later
		let est = self.capacity.get_pat_loc_len() * 1000;

		est
	}

	fn get_msg_size(&self) -> (usize, usize, usize, usize){
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let to_add = cfg.get_to_add_size();
		let stat_len = (IDX_WORD..IDX_SI_DATA+1).collect::<Vec<usize>>()
			.iter().map(|i| to_add[*i]).sum();
		//TODO: needs a separate container for msg3, and need to
		//determine msg2 then.
		(stat_len, 0, 2, 0)
	}

	fn gen_msg1(&self, _stmt_vec: &Vec<F>, _v_idx: &Vec<(usize,usize)>) 
		-> Vec<F>{
		vec![] // dummy
	}

	fn gen_msg3(&self, _stmt_vec: &Vec<F>, _stmt_idx: 
		&Vec<(usize,usize)>, 
		_msg1_vec: &Vec<F>, _idx_msg1: usize, _len_msg1: usize,
		_msg2_vec: &Vec<F>, _idx_msg2: usize, _len_msg2: usize) -> Vec<F>{
		vec![]
	}

	// COST (old):  31n1 + 81n2 + 8n3
	// --> 41n1 + 95n2 + 8n3
	// coz: (1) increased cost validate_synthesis_result +6n2, 
	//   (2) one more copy of validate_eval_subsib_by_sq: 10n1 + 8n2
	// using ratio below: rougly: 125n2 (number of subsigs)-> 125k (worst case)
	// 29n1+2n1 + 22n2 69n2 + 10n2 + 8n3 + 
	// where n1: scc table size (usually 20% of n2), in practice:200 
	// n2: subsigs (in practice: 1000); 
	// n3: sq_res (determined by active_pats_per_subsig * subsigs)
	//   typically 5*n2 (like 5000)
	fn assert_msg3(&self, i: usize, cs: ConstraintSystemRef<F>, 
		wtns: &WitnessSigmaIR1CSVar<F>, wtns_cfg: &WitnessSigmaIR1CSConfig) 
		-> Result<(), SynthesisError>{
		//1. retrive the statement instance and get all parts
		let cfg = self.get_container_cfg().expect("container cfg not set!");
		let stmt = Container::<FpVar<F>>::load_from(i, wtns_cfg, wtns, &cfg)?;
		let r1 = wtns.msg2[0].clone();
		let r2 = wtns.msg2[1].clone();

		//2. validate the eval of subsig based on step queue result
		//two instances (cs and igc)
		let eval_res_combo_cs = stmt.get_container("eval_res_combo_cs")?;
		self.validate_eval_subsig_by_sq_combo(&eval_res_combo_cs.borrow(), 
			r1.clone(), r2.clone(), cs.clone())?;
		let eval_res_combo_igc = stmt.get_container("eval_res_combo_igc")?;
		self.validate_eval_subsig_by_sq_combo(&eval_res_combo_igc.borrow(), 
			r1.clone(), r2.clone(), cs.clone())?;

		//TODO: 
		//3. follow the logic of accepts_approx_pm_bounds in clamav.rs
		// compute (1) res for gen_regex, (2) res for counter_constraint
		// (3) result for subsig_count_constraint. Note that
		// SubsigInfoStore has the related info such as subsig_type, comp_op
		// comp_num and component_subsigs they are already in
		// lkup e.g., using (ID_MIN_REQUIRED, ID_COMP_NUM) we can
		// retrieve the related info. We handle the results in three 
		// separate tables. (as the last one has dynamic size).
		let synthesis_res_combo= stmt
			.get_container("synthesis_res_combo")?;
		self.validate_synthesis_subsig_combo(
			&eval_res_combo_cs.borrow(),
			&eval_res_combo_igc.borrow(),
			&synthesis_res_combo.borrow(), 
			r1.clone(), r2.clone(), cs.clone()
		)?;

		//4. now evaluate all sigs and generate the list of sigs
		//which are DISCHARGED.
		let sig_res_combo= stmt.get_container("sig_res_combo")?;
		self.validate_discharge_sig_combo(
			&eval_res_combo_cs, 
			&synthesis_res_combo, 
			&sig_res_combo, 
			r1.clone(), r2.clone(), cs.clone())?;

		Ok(())
	}

}

impl ComputeSigAdvCapacity{
	/// same as the function of DischargeAdvCapacity - looks like
	/// no better way of refactoring. Just dupplicate it here.
	pub fn get_pat_loc_len(&self)->usize{
		let pats_len = self.basis_pats_in_trace 
			* self.max_nibble_len/10000;
		pats_len
	}

	/// compute the buffer size of subsig count constraint proof
	pub fn get_scc_prf_size(&self)->usize{
		self.perc_comp_subsigs * self.subsigs / 100
	}
}

// --------------------------------------------------------
//	Unit Test
// --------------------------------------------------------

#[cfg(test)]
pub mod tests_compute_sig_adv{
	use ark_ff::{Zero};
	use std::{rc::Rc};
	use ark_bn254::{Fr};
	use utils::{data::{pack_nibbles}, os::{read_nibbles,proj_root,write_to_file}};
	use crate::gadgets::{
		word_extract::{
			LEGS,
			tests_word_extract_gadget::{test_gadget_adv},
		},
		fsm_adv::{FsmAdvAdvice,FsmAdvCapacity},
		word_extract_adv::{WordExtractAdvAdvice},
		discharge_adv::{DischargeAdvAdvice,
			DischargeAdvCapacity,StepQueueItem,StepQueue, StepQueueType},
		compute_sig_adv::{ComputeSigAdvAdvice,ComputeSigAdvGadget,
			ComputeSigAdvCapacity},
		traits::{Container,Col,IDX_DATA},
	};
	use data_processor::{clam_db::{ClamavDB,RANGE2_BIT}, 
		type_def::{ClamavApproxConfig,SubsigStepStore,SubsigStepStoreItem,
			ClamavSig},
		clamav::{default_clamav_cfg, quick_discharge_file_adv}};
	use folding_schemes::folding::foldpot::sigma_ir1cs::{SigmaGadget,
		WordInfo, DischargeSigInfo};
	use folding_schemes::folding::foldpot::container_config::ContainerConfig;
	use std::{collections::{HashMap}, sync::Arc};

	/// a test case for discharge_test_case	
	struct Tcase{//test case
		pub file_content: String,
		pub sig_to_discharge: String, //the signatures to be discharged
			//NOTE: the sig should be INCLUDED in the discharge list
			//of the quick_discharge result's WordInfo. The motivation
			//is to restrict the testing to the original test case,
			//had other cases been added which causes expansion of the
			//list of sigs to discharge.
	}

	impl Tcase{
		pub fn new(file_content: &str, sig_to_disc: &str)->Self{
			Self{file_content: file_content.to_string(),
				sig_to_discharge: sig_to_disc.to_string()
			}
		}
	}


	/// MAINLY for testing the discharge (sed) component.
	///
	/// discharge each test case (mainly running through 
	/// all components from fsm_adv to discharge_adv and then compute_subsig
	/// we expect circuit is satisfiable and all SPECIFIED
	/// sigs in the test case are discharged.
	fn discharge_test_case(
		word_dir: &str,
		db: &ClamavDB<Fr>,
		tcase: &Tcase,
		cfg: &ClamavApproxConfig,
	){
		//1 data preparation
		//1.1. write the tcase file contents to the file
		//then do a quick discharge to retrieve the discharge info.
		let zero = Fr::zero();
		let path = format!("{}/data/{}/word.txt", proj_root(), word_dir);
		write_to_file(&path, &tcase.file_content);
		let nibbles_raw = read_nibbles(&path);
		let f_nibbles = nibbles_raw.iter().map(|x| Fr::from(*x as u32))
			.collect::<Vec<Fr>>();
		let sig_to_discharge = tcase.sig_to_discharge.clone();
		let sig = &db.vec_sigs.iter().filter(|s| s.name==sig_to_discharge)
			.map(|s| s.clone())
			.collect::<Vec<Arc<ClamavSig>>>()[0];
		let v_sig_obj = vec![sig.clone()];
		let wi: WordInfo = quick_discharge_file_adv(
			"word.txt", 
			&nibbles_raw,
			&db.vec_sigs,
			&db.vec_sigs_no_critical_pat,
			&db.map_crit_pat, 
			&db.map_crit_pat_igc, 
			&db.dfa_crit, 
			&db.bundle_subsig.vec_acdfa[0], //dfa_patterns, 
			&db.dfa_crit_igc,
			&db.bundle_subsig_igc.vec_acdfa[0], //dfa_patterns_igc,
			cfg, 
			&db.sig_to_id
		); //use optimize mode

		//1.2 verify the sig_to_discharge is in the word info.
		// NOTE that here we essentially require that sig_to_discharge
		// be IN the required discharge_list (sed/ised). This helps
		// to handle the case more signatures are added which complicates
		// the original test case. (so that we do not pay extra cost)
		let sigs_info = &wi.vec_sed_sigs_info;
		let infos = sigs_info.iter().filter(|i| i.sig_name==sig_to_discharge)
			.map(|i| i.clone()).collect::<Vec<DischargeSigInfo>>();
		assert!(infos.len()==1, "ERR in idnetifying: {}, infos.len: {}",
			sig_to_discharge, infos.len());

		//1.3 set data of acdfa, input_sigs, and bundle info related to the sig.
		let info = infos[0].clone();
		let discharge_infos = vec![info.clone()]; //only one sig to discharge
		let bundle_cs = &db.bundle_subsig;
		let bundle_igc = &db.bundle_subsig_igc;
		let acdfa_cs = &bundle_cs.vec_acdfa[0];
		let acdfa_igc = &bundle_igc.vec_acdfa[0];
		let sig_id = *(db.sig_to_id.get(&sig_to_discharge).unwrap());
		let input_subsigs_cs = info.subsig_ids.iter().map(|i|
			Fr::from(acdfa_cs.gen_subsig_id(sig_id, *i+1) as u32)
		).collect::<Vec<Fr>>();
		let input_subsigs_igc = info.subsig_ids.iter().map(|i|
			Fr::from(acdfa_igc.gen_subsig_id(sig_id, *i+1) as u32)
		).collect::<Vec<Fr>>();

		let store_id = 0;
		let fsm_id_cs = ClamavDB::<Fr>::pm_acdfa_id(store_id, false);
		let fsm_id_igc= ClamavDB::<Fr>::pm_acdfa_id(store_id, true);

		let steps_store_cs = &bundle_cs.vec_subsig_step_stores[store_id]; 
		let steps_store_igc = &bundle_igc.vec_subsig_step_stores[store_id]; 

		let steps_extra_store_cs = &bundle_cs.vec_subsig_info_stores[store_id]; 
		let steps_extra_store_igc=&bundle_igc.vec_subsig_info_stores[store_id]; 

		//1.4 capacilities of fsm and discharge components
		let wlen = 2usize;
		let (nibble_len, state_bits) = (wlen*LEGS, acdfa_cs.state_part_bits);
		let cap = FsmAdvCapacity{
			max_nibble_len: nibble_len, 
			acdfa_state_part_bits: state_bits, 
			subsigs: 5,
			avg_pats_per_subsig: 4,
			basis_pats_in_trace: 27*100, 
			basis_unique_states: 20*100,
		};
		let cap_disc = DischargeAdvCapacity{//capaciity of discharge comopnent
			max_nibble_len: nibble_len, 
			subsigs: cap.subsigs,
			avg_active_pats_per_subsig: 2,
			basis_pats_in_trace: cap.basis_pats_in_trace,
		};
		let cap_sig= ComputeSigAdvCapacity{//capaciity of compute sig adv comp 
			max_nibble_len: nibble_len, 
			sigs: 1, 
			subsigs: cap.subsigs,
			basis_pats_in_trace: cap.basis_pats_in_trace,
			perc_comp_subsigs: 80, //real data will be much lower like 17 at most
		};

		//2. create advice for word_extract_adv, fsm_adv, and discharge_adv
		// both advices are needed for producing related container_config
		// with external col referece.
		let all_word = pack_nibbles(&f_nibbles);
		let alen = all_word.len();
		let n_cycles = if alen%wlen==0 {alen/wlen} else {alen/wlen+1};

		//2.0 input that needs to be fed to advice. update it at end of loop
		let mut inp_state_cs = Fr::from((acdfa_cs.init_state + 1) as u32);
		let mut inp_loc_cs = Fr::from(1u32);
		let mut inp_steps_queue_cs = DischargeAdvAdvice::gen_empty_steps_queue_serialized(&input_subsigs_cs, &steps_store_cs, fsm_id_cs, &cap_disc);  

		let mut inp_state_igc = Fr::from((acdfa_igc.init_state + 1) as u32);
		let mut inp_loc_igc = Fr::from(1u32);
		let mut inp_steps_queue_igc = DischargeAdvAdvice::gen_empty_steps_queue_serialized(&input_subsigs_igc, &steps_store_igc, fsm_id_igc, &cap_disc);  

		for i in 0..n_cycles{
			//2.1 the word_extract_adv
			let end = if wlen*(i+1)>alen {alen} else {wlen*(i+1)};
			let word = all_word[wlen*i..end].to_vec();
			let word = if word.len()==wlen {word} else
				{vec![word.clone(), vec![zero; wlen-word.len()]].concat()};	
			let act_size = word.len();
			let adv_wea = WordExtractAdvAdvice::new(&word, act_size,false);
			let stmt_wea = adv_wea.stmt_container;
			let cfg_wea = stmt_wea.borrow().get_cfg(); 

			//2.2 the fsm_adv (SED approach, two gadgets)
			let nibbles = stmt_wea.borrow().get_container("nibbles").unwrap()
				.borrow().to_vec();
			assert!(nibbles.len()==nibble_len);

		 	let adv_faa_cs = FsmAdvAdvice::new(
				false, //case sensitive
				1, //dist to wea 
				&nibbles, &acdfa_cs, inp_state_cs, 
				inp_loc_cs, &input_subsigs_cs, &cap, fsm_id_cs, 
				&bundle_cs.vec_subsig_stores[store_id]); 
			let stmt_faa_cs = adv_faa_cs.stmt_container;
			let cfg_faa_cs = stmt_faa_cs.borrow().get_cfg(); 

		 	let adv_faa_igc = FsmAdvAdvice::new(
				true, //igc
				2, //dist to wea
				&nibbles, &acdfa_igc, inp_state_igc, 
				inp_loc_igc, &input_subsigs_igc, &cap, fsm_id_igc, 
				&bundle_igc.vec_subsig_stores[store_id]); 
			let stmt_faa_igc = adv_faa_igc.stmt_container;
			let cfg_faa_igc = stmt_faa_igc.borrow().get_cfg(); 

			//2.3 the discharge_adv (2 gadgets)
			let pat_loc_cs = stmt_faa_cs.borrow().search_container("fsm_adv_stmt_cs packed_trace pat_loc sorted_tbl").unwrap();
			let adv_disc_cs= DischargeAdvAdvice::new(
				false, //case sensitive
				2, //dist to fsm_cs
				&pat_loc_cs,
				&input_subsigs_cs,
				fsm_id_cs, steps_store_cs, &cap_disc, &inp_steps_queue_cs
			);
			let oup_queue_cs = adv_disc_cs.get_output_steps_queue();
			let stmt_disc_cs= adv_disc_cs.stmt_container;
			let cfg_disc_cs= stmt_disc_cs.borrow().get_cfg(); 

			let pat_loc_igc = stmt_faa_igc.borrow().search_container("fsm_adv_stmt_igc packed_trace pat_loc sorted_tbl").unwrap();
			let adv_disc_igc= DischargeAdvAdvice::new(
				true, //igc
				2, //dist to fsm_adv_igc
				&pat_loc_igc,
				&input_subsigs_igc,
				fsm_id_igc, steps_store_igc, &cap_disc, &inp_steps_queue_igc
			);
			let oup_queue_igc = adv_disc_igc.get_output_steps_queue();
			let stmt_disc_igc= adv_disc_igc.stmt_container;
			let cfg_disc_igc= stmt_disc_igc.borrow().get_cfg(); 

			if i==n_cycles-1{//last cycle for subsig
				//2.3.5 generate the info for the compute_sig_adv gadget
				let inp_sigs: Vec<Fr> = vec![Fr::from(sig_id as u64)];
				let sq_res_cs = stmt_disc_cs.borrow().search_container("discharge_adv_stmt_cs bwd_steps_queue sq_res2").expect("sq_res err");
				let sq_res_igc = stmt_disc_igc.borrow().search_container("discharge_adv_stmt_igc bwd_steps_queue sq_res2").expect("sq_res err");
				let adv_sig= ComputeSigAdvAdvice::new(
					fsm_id_cs, 
					fsm_id_igc, 
					&inp_sigs, 
					&input_subsigs_cs, 
					&input_subsigs_igc, 
					&discharge_infos, 
					&sq_res_cs, 
					&sq_res_igc, 
					&cap_sig, 
					steps_store_cs, 
					steps_store_igc, 
					steps_extra_store_cs, 
					steps_extra_store_igc, 
					&v_sig_obj, 
					&db.sig_to_id
				);
				let stmt_sig = adv_sig.stmt_container;
				let cfg_sig = stmt_sig.borrow().get_cfg();

				//2.4 given cfgs, set up the positions
				let mut vec_cfg = vec![
					cfg_wea.clone(), 
					cfg_faa_cs.clone(),  cfg_faa_igc.clone(),
					cfg_disc_cs.clone(), cfg_disc_igc.clone(),
					cfg_sig.clone()
				];
				ContainerConfig::adjust_locations(&mut vec_cfg); //resolve

				//2.6. generate the 9 segments of output for building statment
				//from inp to si_data
				let cps1 = stmt_wea.borrow().gen_stmt_components(); 
				let cps2 = stmt_faa_cs.borrow().gen_stmt_components(); 
				let cps3 = stmt_faa_igc.borrow().gen_stmt_components(); 
				let cps4 = stmt_disc_cs.borrow().gen_stmt_components(); 
				let cps5 = stmt_disc_igc.borrow().gen_stmt_components(); 
				let cps6 = stmt_sig.borrow().gen_stmt_components(); 
				let cps = cps1.0.into_iter().zip(cps2.0.into_iter()).map(|(a,b)|
					vec![a,b].concat()).collect::<Vec<Vec<Fr>>>();
				let cps = cps.into_iter().zip(cps3.0.into_iter()).map(|(a,b)|
					vec![a,b].concat()).collect::<Vec<Vec<Fr>>>();
				let cps = cps.into_iter().zip(cps4.0.into_iter()).map(|(a,b)|
					vec![a,b].concat()).collect::<Vec<Vec<Fr>>>();
				let cps = cps.into_iter().zip(cps5.0.into_iter()).map(|(a,b)|
					vec![a,b].concat()).collect::<Vec<Vec<Fr>>>();
				let cps = cps.into_iter().zip(cps6.0.into_iter()).map(|(a,b)|
					vec![a,b].concat()).collect::<Vec<Vec<Fr>>>();

				//2.7 create the discharge gadget
				let lkup_share_size = 4usize;
				let mut dcg = ComputeSigAdvGadget::<Fr>::new(
					fsm_id_cs,
					fsm_id_igc,
					&cap_sig, 
					&vec![
						cfg_wea.clone(), 
						cfg_faa_cs.clone(), cfg_faa_igc.clone(),
						cfg_disc_cs.clone(), cfg_disc_igc.clone(),
					],
					&bundle_cs.vec_subsig_step_stores[0], //store_steps for sed
					&bundle_igc.vec_subsig_step_stores[0], //store_steps for sed
					&bundle_cs.vec_subsig_info_stores[0], //extra info
					&bundle_igc.vec_subsig_info_stores[0], //extra info
				);
				dcg.set_container_cfg(vec_cfg.clone().into(),5); //6'th comp
				let rg = Rc::new(dcg);

				//3. test it
				test_gadget_adv::<Fr>(rg, &word, &cps[0], &cps[1], &cps[2],
					&cps[6],
					&cps[7],
					&vec![//subtbl_id (concats of si_inp, si_oup, si_data)
						cps[3].clone(), 
						cps[4].clone(), 
						cps[5].clone(),
					].concat(),
					lkup_share_size,
					false, //not legacy mode
					Some(vec_cfg),
				);
			}

			//4. reset the inputs for the next cycle
			let states_cs = stmt_faa_cs.borrow()
				.search_container("fsm_adv_stmt_cs fsm_acc states")
				.expect("no states")
				.borrow().to_vec();
			let states_igc = stmt_faa_igc.borrow()
				.search_container("fsm_adv_stmt_igc fsm_acc states")
				.expect("no states")
				.borrow().to_vec();
			inp_state_cs = states_cs[states_cs.len()-1];
			inp_state_igc = states_igc[states_igc.len()-1];
			let locs_cs = stmt_faa_cs.borrow()
				.search_container("fsm_adv_stmt_cs fsm_acc locs")
				.expect("no locs")
				.borrow().to_vec();
			let locs_igc = stmt_faa_igc.borrow()
				.search_container("fsm_adv_stmt_igc fsm_acc locs")
				.expect("no locs")
				.borrow().to_vec();
			inp_loc_cs = locs_cs[locs_cs.len()-1];
			inp_loc_igc = locs_igc[locs_igc.len()-1];
			inp_steps_queue_cs = StepQueue::parse_from(&oup_queue_cs,&cap_disc);
			inp_steps_queue_igc = StepQueue::parse_from(&oup_queue_igc,
				&cap_disc);
		}

		//4. verify the sigs_to_discharge have been discharged
		//manually checked.
	}

	#[test]
	fn test_compute_sig_adv(){
		//1. define the sigs
		let sigs = vec![
			/* RECOVER LATER
			"sig1;Engine:51-255,Target:0;0&1;/abc..123/;/123....abc/",
			"sig2;Engine:51-255,Target:0;0&1;/def.*234.*567/;/234....def/",
			"sig3;Engine:51-255,Target:0;0&1;/fgh.*1234......56...78/;/56......fgh/",
			//sig4: counter constraint
			"sig4;Engine:51-255,Target:0;0>2;/abc..123/",
			*/
			// /* RECOVER LATER
			//sig5: subsig counter constraint (here min req is 2)
			"sig5;Engine:51-255,Target:1;(0|1)>1,2;/abc..123/i;/56...fgh/",
			// */

		].iter().map(|x| x.to_string()).collect::<Vec<String>>();
		let needs_dfa = vec![];
		let needs_ised= vec![];
		let needs_ised_igc = vec![];
		let sigs_dir = "debug/sed/workdir";
		let cfg = default_clamav_cfg();
		let db = ClamavDB::<Fr>::build_test_db(&cfg, &sigs_dir, &sigs, 
			&needs_dfa, &needs_ised, &needs_ised_igc);

		//2. define the test cases
		let testcases = vec![
			/* RECOVER LATER
			//1. fails sig1 coz gap len incorrect
			Tcase::new("abcddd123", "sig1", false, false), //b_ised=F, igc=F
			//2. fails sig2 coz 3rd pattern missing
			Tcase::new("defxx234xx56", "sig2", false, false),
			//3. similar to test2 for longer string (2 cycles)
			// debug to verify that location 193 (corresponding to
			// 234 is added to "to_add" and in "res". "56" is not identified
			Tcase::new(
				&format!("def{}234xx56","x".repeat(90)), 
				"sig2", false, false),
			//4. a case where only one patterns occur at all, and across 3 cyles
			Tcase::new(
				&format!("ddd{}234xx{}56","x".repeat(90), "u".repeat(90)), 
				"sig2", false, false),
			//5. a case which has both fwd and backward elimination.
			//manually check debug messages of backward and forward proofs
			//baseically: the last 78 is not added, but the
			//first 78 kills the 1st 56, which then kills the first three
			//1234
			Tcase::new("fghxx1234xx1234xx1234x1234x56xxx56xxx78xx78xx", "sig3", false, false), 
			//5. fails sig4 coz gap because missing one appearance
			Tcase::new("abcdd123xabcxx123xxabcxx333", "sig4", false, false), //b_ised=F, igc=F
			*/ 
			// /* RECOVER LATER
			//6. fails sig5 coz because it needs to have two distinnct
			// matches but only matches 56...fgh (missing abc...123)
			Tcase::new("aBcdd122xabx56xxxfghxxabcdd122", "sig5"), 
				//changing to aBcdd123 should fail test as
				//it cannot discharge sig5
				// the unit test will report that sig5 not found in
				// set of discharge because it cannot be discharged.
			// */
		];

		for tc in testcases{
			discharge_test_case(&sigs_dir, &db, &tc, &cfg);
		}
	}

	#[allow(dead_code)]
	fn to_vf(vec: Vec<u32>)->Vec<Fr>{
		vec.iter().map(|x| Fr::from(*x)).collect()
	}

	// #[test]
	#[allow(dead_code)]
	fn test_compute_sig_advice(){
		//0. create a subsig step store
		let item1 = SubsigStepStoreItem::new(100, false, //case sensitive
			vec![	
				(2, (10, 100)),
				(3, (20,30)),
			]);
		let item2 = SubsigStepStoreItem::new(200, false, //case sensitive
			vec![	
				(20, (10,120)),
				(30, (10,20)),
			]);
		let mut steps_info = SubsigStepStore::new();
		steps_info.add(&item1);
		steps_info.add(&item2);
		steps_info.finalize();

		//1. test the serialization
		let max :u32= (1<<RANGE2_BIT) - 1;
		let subsig100_steps = vec![
			StepQueueItem::new2( 
				// subsig, id, pat, rg_start, rg_end
				to_vf(vec![100u32, 0, 0, 0, 0]), to_vf(vec![1u32])),
			StepQueueItem::new2( 
				to_vf(vec![100u32, 1, 2, 10, 100]), to_vf(vec![11u32, 12])),
			StepQueueItem::new2( 
				to_vf(vec![100u32, 2, 3, 20, 30]), to_vf(vec![16u32, 22])),
			StepQueueItem::new2( 
				to_vf(vec![100u32, 3, max, 0, 0]), to_vf(vec![])),
		];
		let subsig200_steps = vec![
			StepQueueItem::new2( 
				to_vf(vec![200u32, 0, 0, 0, 0]), to_vf(vec![1u32])),
			StepQueueItem::new2( 
				to_vf(vec![200u32, 1, 20, 20, 120]), to_vf(vec![22u32, 30])),
			StepQueueItem::new2( 
				to_vf(vec![200u32, 2, 30, 10, 20]), to_vf(vec![31u32, 32])),
			StepQueueItem::new2( 
				to_vf(vec![200u32, 3, max, 0, 0]), to_vf(vec![])),
		];
		let subsigs = to_vf(vec![100,200]);
		let mut store_items = HashMap::new();
		store_items.insert(Fr::from(100u32), subsig100_steps);
		store_items.insert(Fr::from(200u32), subsig200_steps);
		let capacity= DischargeAdvCapacity{
			max_nibble_len: 62, 
			subsigs: 4,
			avg_active_pats_per_subsig: 2,
			basis_pats_in_trace: 48*100, //48 percent
		};
		let sq = StepQueue{subsigs, store_items, capacity: capacity.clone(),
			q_type: StepQueueType::Res};
		let ct = sq.to_container("ct", true, false, false, false, &steps_info);
		let pat = ct.borrow().get_container("encoded")
			.unwrap().borrow().to_vec();
		let loc = ct.borrow().get_container("locs").unwrap().borrow().to_vec();
		let vec = vec![pat, loc].concat();
		let sq2 = StepQueue::parse_from(&vec, &capacity);
		assert!(sq == sq2);

		//2. test the forward proof
		let pat_loc = Container::new("pat_loc"); 
		pat_loc.borrow_mut().add_col(Col::new(
			to_vf(vec![2, 2, 2, 2,   3,3,3,3,3,   20,20,20,   30,30,30,30,30]), 
				"sorted_key", IDX_DATA)); 
		pat_loc.borrow_mut().add_col(Col::new(
		  to_vf(vec![0, 1, 2, 3,   0,1,2,3,4,    0,1,2,     0,1,2,3,4]), 
				"sorted_id", IDX_DATA)); 
		pat_loc.borrow_mut().add_col(Col::new(
	   	   to_vf(vec![0, 63,102,max,  0,65,93,94,max,  0,51,max, 0,60,61,72,max ]), "sorted_val", IDX_DATA)); 
		let (to_add, res, prf) = sq.gen_forward_prf(&pat_loc, &steps_info);

		let b_details = false;
		if b_details{
			println!("DEBUG USE 50001: to_add");
			to_add.dump();
			println!("DEBUG USE 50002: res");
			res.dump();
			println!("DEBUG USE 50003: proof");
			prf.dump();
		}

		let vec100 = res.store_items.get(&Fr::from(100)).unwrap(); 
		let vec200 = res.store_items.get(&Fr::from(200)).unwrap();
		assert!(vec100[1].pat==Fr::from(2u32));
		assert!(vec100[1].locs==to_vf(vec![11,12,63]));
		assert!(vec100[2].pat==Fr::from(3u32) && 
			vec100[2].locs==to_vf(vec![16,22,93]));
		assert!(vec200[1].pat==Fr::from(20u32) && 
			vec200[1].locs==to_vf(vec![22,30,51]));
		assert!(vec200[2].pat==Fr::from(30u32));
		assert!(vec200[2].locs==to_vf(vec![31,32,61]));
	}


}



