#!/usr/bin/env python3
# -------------------------------------------
# Creator:   BORA Author
# Date:      05/25/2026
#
#   This converts chr17_samples/NC_000017.11.fasta into a pure-ACGT byte
#   string acceptable as a Reef DNA document:
#     - drops FASTA header line(s) ('>' lines)
#     - strips ALL whitespace/newlines
#     - uppercases soft-masked lowercase a/c/g/t -> A/C/G/T
#     - maps every remaining non-ACGT base (N + IUPAC ambiguity) -> 'A'
#     - writes NO trailing newline
#
#   Caveat: chr17's  long 'N' runs -> become 'A'
#   runs. Unavoidable (Reef has no 'N' symbol) and harmless: no pathogenic
#   variant lives in a gap, and coordinates are preserved.
#
# NOTE: code partly generated by Claude Code; audited by the author.
#   The correctness is verified via the following approach:
#       sample n variants from the variants/ folder,
#       these variants has coordinate spot references (e.g., at
#          xxx location we are expecting sequence yyy).
#       run these spot checks to verify the conversion is correct.
# -------------------------------------------
import os
import hashlib
import datetime

IN_FASTA       = "chr17_samples/NC_000017.11.fasta"
OUT_STR        = "chr17_samples/NC_000017.11.reef.txt"
LOG_FILE       = "docs/nc_00017.convert.log"
VARIANTS_DIR   = "variants"
SUB_BASE       = b"A"          # non-ACGT bases (N, IUPAC) map here
ACGT           = b"ACGT"
EXPECTED_BASES = 83257441      # NC_000017.11 length, from docs/chr17_sample.log


def build_translation_table(sub_base=SUB_BASE):
    """256-byte table: A/C/G/T -> self, a/c/g/t -> upper, all else -> sub_base.
    bytes.translate(table) maps each input byte through table[byte] in one
    C-level pass, so every non-ACGT byte collapses to sub_base automatically;
    we only override the 8 ACGT/acgt slots, leaving the other 248 -> sub_base."""
    table = bytearray([sub_base[0]] * 256)
    for b in ACGT:
        table[b] = b
    for low, up in zip(b"acgt", ACGT):
        table[low] = up
    return bytes(table)


def read_sequence_bytes(in_path):
    """Read FASTA, drop '>' header lines, strip whitespace; return the raw
    concatenated sequence bytes (still containing N / lowercase / etc.).
    translate(None, delete=...) does no mapping, only DELETES the listed bytes,
    so whitespace/newlines vanish here -- bases (incl. N) are untouched and
    get mapped later, keeping this step purely about removing non-sequence."""
    chunks = []
    with open(in_path, "rb") as f:
        for line in f:
            if line.startswith(b">"):
                continue
            chunks.append(line.translate(None, delete=b" \t\r\n"))
    return b"".join(chunks)


def to_reef_acgt(raw, table):
    """Translate raw sequence bytes into a pure-ACGT byte string."""
    return raw.translate(table)


def compute_stats(raw):
    """Counts describing what the conversion changed.
    Trick: translate(None, delete=KEEP) removes the KEEP bytes and returns the
    REST, so len(rest) counts everything NOT in KEEP -- e.g. delete 'ACGTacgt'
    leaves only the non-ACGT bases, whose length is the substitution count."""
    total = len(raw)
    return {
        "total_bases":     total,
        "lowercase_fixed": total - len(raw.translate(None, delete=b"acgt")),
        "non_acgt_subbed": len(raw.translate(None, delete=b"ACGTacgt")),
        "of_which_N":      raw.count(b"N") + raw.count(b"n"),
    }


def md5_bytes(b):
    return hashlib.md5(b).hexdigest()


def md5_file(path, chunk=1 << 20):
    """Stream the file in 1 MiB blocks so an 84 MB input never loads at once.
    iter(callable, sentinel) calls f.read(chunk) repeatedly until it returns
    b"" (EOF), feeding each block to the running md5."""
    h = hashlib.md5()
    with open(path, "rb") as f:
        for blk in iter(lambda: f.read(chunk), b""):
            h.update(blk)
    return h.hexdigest()


def verify_output(out_bytes, expected_len):
    """Hard self-tests -- Reef will panic unless both hold.
    Deleting ACGT from a valid document leaves the empty string; any 'leftover'
    bytes are exactly the illegal ones that would crash Reef, so we report them."""
    leftover = out_bytes.translate(None, delete=ACGT)
    assert not leftover, ("output has non-ACGT byte(s): "
                          + ", ".join(hex(b) for b in sorted(set(leftover))))
    assert len(out_bytes) == expected_len, (
        f"length {len(out_bytes)} != expected {expected_len} (coordinate drift!)")


def _parse_variant(path):
    """Parse a 'KEY: VALUE' variant file into a dict (used only by the
    coordinate spot-check, to read POS/REF)."""
    d = {}
    with open(path) as f:
        for line in f:
            if ":" in line:
                k, _, v = line.partition(":")
                d[k.strip()] = v.strip()
    return d


def spot_check_coordinates(out_bytes, variants_dir, n=100):
    """Independent coordinate check: for a few variants the reference allele
    REF must appear at output[POS-1 : POS-1+len(REF)]. Proves the converted
    document agrees with ClinVar's genomic coordinates."""
    checked = 0
    for name in sorted(os.listdir(variants_dir)):
        if checked >= n:
            break
        v = _parse_variant(os.path.join(variants_dir, name))
        ref = v.get("REF", "").upper().encode()
        pos = v.get("POS", "")
        if not pos.isdigit() or not ref or any(c not in ACGT for c in ref):
            continue  # skip malformed / non-ACGT REF (e.g. N regions)
        i = int(pos) - 1
        got = out_bytes[i:i + len(ref)]
        assert got == ref, f"{name}: POS {pos} expected REF {ref!r}, doc has {got!r}"
        checked += 1
    return checked


def write_output(out_path, out_bytes):
    """Write the pure-ACGT document with NO trailing newline."""
    with open(out_path, "wb") as f:
        f.write(out_bytes)


def write_convert_log(log_path, stats, in_path, out_path,
                      in_md5, out_md5, out_len, checked):
    lines = [
        f"generator:         {os.path.basename(__file__)}",
        f"date:              {datetime.date.today().isoformat()}",
        f"input:             {in_path}",
        f"input_md5:         {in_md5}",
        f"output:            {out_path}",
        f"output_md5:        {out_md5}",
        f"output_length:     {out_len}",
        f"coord_spotchecks:  {checked} variant(s) verified (REF matches doc)",
        "",
        "changes made (FASTA -> pure-ACGT Reef document):",
        "  - dropped FASTA header line(s) ('>' lines)",
        "  - stripped all whitespace/newlines (Reef reads raw bytes; a newline",
        "    0x0a would abort the run -- not in the {A,C,G,T} alphabet)",
        f"  - uppercased soft-masked lowercase a/c/g/t -> A/C/G/T  (count: {stats['lowercase_fixed']})",
        f"  - substituted non-ACGT bases (N + IUPAC) -> 'A'  (count: {stats['non_acgt_subbed']}, of which N: {stats['of_which_N']})",
        "  - wrote NO trailing newline",
        "  - LENGTH-PRESERVING over bases: output_length == input base count,",
        "    so a variant at 1-based POS lands at output index POS-1 (no drift)",
    ]
    with open(log_path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    # this script lives in scripts/, one level below the project root where the
    # data dirs are; anchor cwd to that root so the relative paths below resolve
    # (works regardless of where the script is invoked from; no absolute paths).
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))

    table = build_translation_table()
    raw   = read_sequence_bytes(IN_FASTA)
    stats = compute_stats(raw)
    out   = to_reef_acgt(raw, table)

    verify_output(out, EXPECTED_BASES)          # fail before writing a bad file
    checked = spot_check_coordinates(out, VARIANTS_DIR)
    write_output(OUT_STR, out)

    write_convert_log(LOG_FILE, stats, IN_FASTA, OUT_STR,
                      md5_file(IN_FASTA), md5_bytes(out), len(out), checked)

    print(f"[convert] wrote {OUT_STR} ({len(out)} bases)")
    print(f"[convert] lowercase_fixed={stats['lowercase_fixed']} "
          f"non_acgt->A={stats['non_acgt_subbed']} (N={stats['of_which_N']})")
    print(f"[convert] coord spot-checks passed: {checked}")
    print(f"[convert] md5={md5_bytes(out)}  log -> {LOG_FILE}")


if __name__ == "__main__":
    main()
