# -----------------------------------------
# Reads the variants/ folder and for each variant generate a corresponding
# regex (accepted by Reef) and save it in the reef_regex/ folder.
#
# We process the NC_000017.11 sample only.
#
# NOTE: code mostly generated by Claude Code 4.7 and reviewed/audited by the
#       BORA author. Uses external tools samtools (faidx slicing) + bcftools
#       (consensus);
# NOTE: the correctness is verified by the following for each variant
#		(1) apply the variant to the NC_000017.11 to generate
#				a varied document. Verify that the varied doc is
#				a MATCH of the generated regex.
#		(2) verify that the original NC_000017.11 is NOT a match
#				of the generated regex.A
#		(3) sample and manually verify the generated regex.
#
# NOTE: each regex is emitted as "^.{N}LITERAL.*" WITH a leading '^'. Reef
#       needs the '^' to (a) anchor the match at the document start so LITERAL
#       is pinned to offset N (without '^' Reef runs UNANCHORED and matches
#       LITERAL anywhere >= N), and (b) enable '-p' document projections, which
#       are a no-op for an unanchored regex. test_variant verifies the match
#       with re.fullmatch (whole-string).
#
# NOTE: LITERAL-LENGTH HEURISTIC -- the literal normally spans bp_len bases,
#		In those cases the
#       literal is EXTENDED to cover the ENTIRE changed allele (ALT) plus
#       bp_len, so it stays unique to the mutated doc -- large structural
#       variants thus get long literals. docs/reef_regex.log records the
#       count, average and max regex length (no per-variant list).
#		Note that the average length of the generated regex is not long
#		around 50 (most variants are small changes, but there are few
#		with long edit distance resulting in max regex of length around 8k).
#
# NOTE: SKIPPED variants -- a variant is skipped (no regex produced)
#       when its allele cannot become a deterministic ACGT
#       literal: an ambiguous base that our processing code is not
#		sure. In this case, for convenience, we simply skip it.
#		We skipped about 60 out of 22k variants in total.
# -----------------------------------------

import os
import re
import time
import datetime
import subprocess
from concurrent.futures import ProcessPoolExecutor

# --- configuration ---------------------------------------------------------
# All data paths are relative to the project root; main() chdir's there so the
# script can be launched from anywhere (no absolute paths).
ACC = "NC_000017.11"  # FASTA sequence name / accession
REF_FASTA = "chr17_samples/NC_000017.11.fasta"  # real reference (REF intact)
REEF_STR = "chr17_samples/NC_000017.11.reef.txt"  # reef doc (N->A, ACGT)
VARIANTS_DIR = "variants"
VARIANTS_VCF_DIR = "variants_vcf"  # per-variant <name>.vcf.gz (+ .tbi)
REEF_REGEX_DIR = "reef_regex"
TMP_DIR = "/tmp/bcftemp"  # scratch for the reference .fai
DEFAULT_BP_LEN = 32

# Run mode. b_real_run False: process SAMPLE_N variants serially, time each
# stage and refresh the "Performance:" comments. True: generate + write + test
# ALL variants in parallel, and do NOT touch the Performance comments.
b_real_run = True 
SAMPLE_N = 10  # variants processed when not a real run
N_WORKERS = os.cpu_count() or 4  # parallel workers for the real run

# non-ACGT byte -> 'A' (the same N->A folding convert_nc_to_str.py applied to
# build reef.txt), so literals taken from the real FASTA share reef's alphabet.
_REEF_TABLE = bytes((c if c in b"ACGT" else ord("A")) for c in range(256))
_FAI = None  # reference .fai path, set by setup()
_REEF_DOC = None  # reef doc bytes, loaded once per process


# --- external-tool wrappers (samtools / bcftools) --------------------------
# Project rule: one verify_* and one run_<tool> per external binary, all
# invoked with an args LIST (never shell=True) to avoid command injection.
def verify_tool_existence(tool):
    """Return the resolved path of an external tool, or abort if missing."""
    import shutil
    path = shutil.which(tool)
    if path is None:
        raise RuntimeError(f"required external tool not on PATH: {tool}")
    return path


def run_samtools_faidx_build(ref, fai):
    """Build the .fai index for `ref` at path `fai` (args list; no shell)."""
    subprocess.run(["samtools", "faidx", "--fai-idx", fai, ref], check=True)
    return fai


def run_samtools_faidx(ref, region, fai):
    """Open `samtools faidx <ref> <region>` streaming a FASTA on stdout, using
    the index at `fai`. Returns the Popen (args list; no shell)."""
    return subprocess.Popen(
        ["samtools", "faidx", "--fai-idx", fai, ref, region],
        stdout=subprocess.PIPE)


def run_bcftools_consensus(vcf_gz, fasta_stream):
    """Apply a single-variant VCF to a FASTA arriving on stdin; return the
    mutated FASTA bytes (args list; no shell)."""
    return subprocess.run(["bcftools", "consensus", vcf_gz],
                          stdin=fasta_stream, capture_output=True,
                          check=True).stdout


# --- helpers ---------------------------------------------------------------
def _strip_fasta(fasta_bytes):
    """Drop FASTA header line(s) + newlines, return bare uppercase sequence."""
    out = bytearray()
    for line in fasta_bytes.split(b"\n"):
        if line and not line.startswith(b">"):
            out += line
    return bytes(out).upper()


def _to_reef_alphabet(seq):
    """Fold any non-ACGT byte to 'A' (reef.txt's alphabet)."""
    return seq.translate(_REEF_TABLE)


def _parse_variant(variant_name):
    """Read variants/<name>.txt 'KEY: VALUE' lines into a dict (split on 1st
    ':', so SPDI's embedded colons survive)."""
    path = os.path.join(VARIANTS_DIR, variant_name + ".txt")
    d = {}
    with open(path) as f:
        for line in f:
            if ":" in line:
                k, v = line.split(":", 1)
                d[k.strip()] = v.strip()
    return d


def _is_acgt(s):
    """True iff s is a non-empty plain-ACGT allele (no symbolic / '.')."""
    return len(s) > 0 and all(c in "ACGT" for c in s)


def _regex_lengths(regex):
    """(literal_len, full_regex_len) for a '^.{N}LITERAL.*' regex string
    (leading '^' optional, for back-compat)."""
    m = re.fullmatch(r"\^?\.\{\d+\}(.*)\.\*", regex)
    return (len(m.group(1)) if m else -1, len(regex))


def _skip_reason(variant_name):
    """Concise reason a variant's allele cannot become an ACGT literal."""
    v = _parse_variant(variant_name)
    r, a = v.get("REF", "").upper(), v.get("ALT", "").upper()
    if a in (".", ""):
        return "no ALT (identity record)"
    if "N" in r or "N" in a:
        return "ambiguous base (N) in allele"
    return "non-ACGT allele"


def mutated_sequence(ref, region, vcf_gz, fai):
    """Stream `region` of `ref` through `bcftools consensus <vcf_gz>` and
    return the mutated sequence as bare uppercase bytes (header + newlines
    stripped). bcftools reads the 'chr:beg-end' header samtools writes and
    shifts variant positions into the window, so a few-kb slice never reads
    the whole 83 MB."""
    p = run_samtools_faidx(ref, region, fai)
    raw = run_bcftools_consensus(vcf_gz, p.stdout)
    p.stdout.close()
    if p.wait() != 0:
        raise RuntimeError(f"samtools faidx failed for region {region}")
    return _strip_fasta(raw)


def reference_sequence(ref, region, fai):
    """Return the reference `region` as bare uppercase bytes (no variant
    applied), via `samtools faidx` only."""
    p = run_samtools_faidx(ref, region, fai)
    raw = p.stdout.read()
    p.stdout.close()
    if p.wait() != 0:
        raise RuntimeError(f"samtools faidx failed for region {region}")
    return _strip_fasta(raw)


# read NC_000017.11 (reef string) fully into memory as bytes.
# Performance: 29.1 ms/call (sample)
def read_nc17_reef():
    """Return the reef doc (pure-ACGT, N->A, no newlines) as bytes."""
    with open(REEF_STR, "rb") as f:
        return f.read()


# set up the cache for samtools/bcftools: create /tmp/bcftemp and build the
# reference .fai there, so windowed slices avoid reading the entire file.
# Performance: 1.8 ms/call (sample)
def setup():
    """Verify tools, create TMP_DIR, build the reference .fai. Sets _FAI."""
    global _FAI
    verify_tool_existence("samtools")
    verify_tool_existence("bcftools")
    os.makedirs(TMP_DIR, exist_ok=True)
    fai = os.path.join(TMP_DIR, os.path.basename(REF_FASTA) + ".fai")
    if not os.path.exists(fai):
        run_samtools_faidx_build(REF_FASTA, fai)
    _FAI = fai
    return fai


# read the variant from variants/, apply its edit over NC_000017.11, take the
# resulting sequence at the variant's start index, and generate a Reef regex
# like "^.{111222}ACGTAGGT.*". Default bp_len is 32: average gene length is at
# least 1kb so a fragment this short is unlikely to stretch into another gene
# (even exon size is ~120bp, so 32 is regarded as small enough). Fast: it
# leverages the samtools+bcftools windowed slice rather than the whole 83 MB.
# Performance: 2.6 ms/call (sample)
def gen_regex(variant_name, bp_len=DEFAULT_BP_LEN):
    """Return the Reef regex string '^.{N}LITERAL.*' for one variant.

    N = POS-1 (0-based start). Mutated and reference can be IDENTICAL for a
    stretch after POS (a tandem dup looks unchanged until the repeat tract
    ends; a left-anchored del until the deleted span begins), so a fixed-length
    literal there would also match the reference. We find the first offset d
    where mutated diverges from reference and take the literal as the mutated
    bytes [0 : max(d, |ALT|-1) + bp_len] -- anchored at POS, covering the
    ENTIRE changed allele (ALT) and reaching bp_len past the divergence, so it
    IS in the mutated doc and is NOT in the reference. For a SNV d=0 and
    |ALT|=1, giving the usual bp_len literal."""
    v = _parse_variant(variant_name)
    pos, ref, alt = int(v["POS"]), v["REF"].upper(), v["ALT"].upper()
    if not (_is_acgt(ref) and _is_acgt(alt)):
        raise ValueError(f"{variant_name}: non-ACGT allele REF={ref} ALT={alt}")
    n = pos - 1  # 0-based offset before POS
    vcf_gz = os.path.join(VARIANTS_VCF_DIR, variant_name + ".vcf.gz")
    # grow the window until the divergence is found (handles long repeat tracts)
    reach = max(len(ref), len(alt)) + 4 * bp_len + 16
    for _ in range(6):
        region = f"{ACC}:{pos}-{pos + reach}"
        mut = _to_reef_alphabet(mutated_sequence(REF_FASTA, region, vcf_gz,
                                                 _FAI))
        refw = _to_reef_alphabet(reference_sequence(REF_FASTA, region, _FAI))
        lo = min(len(mut), len(refw))
        d = next((i for i in range(lo) if mut[i] != refw[i]), -1)
        if 0 <= d:
            # cover the ENTIRE changed allele (ALT) and reach past the first
            # divergence, so the literal is unique to the mutated doc
            end = min(max(d, len(alt) - 1) + bp_len, len(mut))
            return f"^.{{{n}}}{mut[:end].decode()}.*"
        reach *= 2
    raise ValueError(f"{variant_name}: mutated == reference within window")


# write the regex into the target dir reef_regex/ as <name>.txt (bare string).
# Performance: 0.2 ms/call (sample)
def write_reef_regex(variant_name, s_regex):
    """Write s_regex to reef_regex/<name>.txt with no trailing newline."""
    os.makedirs(REEF_REGEX_DIR, exist_ok=True)
    path = os.path.join(REEF_REGEX_DIR, variant_name + ".txt")
    with open(path, "w") as f:
        f.write(s_regex)
    return path


# apply the variant to NC_000017.11 and return the resulting mutated sequence
# (the full ~83 MB doc) as bytes, via the samtools|bcftools process pipe.
# Performance: 857.2 ms/call (sample)
def apply_variant(variant_name):
    """Return the whole mutated chromosome (reef alphabet) as bytes."""
    vcf_gz = os.path.join(VARIANTS_VCF_DIR, variant_name + ".vcf.gz")
    return _to_reef_alphabet(mutated_sequence(REF_FASTA, ACC, vcf_gz, _FAI))


# verify the regex is NOT a match of the (reference) reef_doc, then apply the
# variant to build the mutated reef_doc and verify the regex IS a match of it.
# Performance: 896.0 ms/call (sample)
def test_variant(variant_name, reef_doc, generated_regex):
    """Whole-string check (fullmatch = beginning-to-end): the regex must NOT
    match the reference doc and MUST fully match the mutated doc. fullmatch
    mirrors Reef's whole-document semantics; the written '.{N}LITERAL.*' form
    is for a full match, not a substring search."""
    pat = re.compile(generated_regex.encode())
    if pat.fullmatch(reef_doc) is not None:
        raise AssertionError(
            f"{variant_name}: regex unexpectedly MATCHES reference reef_doc")
    mutated = apply_variant(variant_name)
    if pat.fullmatch(mutated) is None:
        raise AssertionError(
            f"{variant_name}: regex does NOT match the mutated reef_doc")
    return True


# --- per-variant processing (parallel unit of work) ------------------------
# generate the regex for one variant, write it, and verify it. This is the
# unit of work for a real (parallel) run. Returns (name, status, detail) with
# status in {"ok","skip","fail"}; reads module globals _FAI and _REEF_DOC so
# the 83 MB reef doc is never pickled per task.
def process_variant(variant_name):
    """gen_regex -> write_reef_regex -> test_variant for one variant.
    Returns (name, status, detail, literal_len, regex_len); lengths are -1
    when no regex was generated."""
    vcf_gz = os.path.join(VARIANTS_VCF_DIR, variant_name + ".vcf.gz")
    if not os.path.exists(vcf_gz):
        return (variant_name, "skip", "missing .vcf.gz", -1, -1)
    try:
        rgx = gen_regex(variant_name)
        write_reef_regex(variant_name, rgx)
        test_variant(variant_name, _REEF_DOC, rgx)
        lit, rlen = _regex_lengths(rgx)
        return (variant_name, "ok", "", lit, rlen)
    except ValueError:                 # non-ACGT / unrepresentable allele
        return (variant_name, "skip", _skip_reason(variant_name), -1, -1)
    except Exception as e:             # AssertionError, tool failure, ...
        return (variant_name, "fail", f"{type(e).__name__}: {e}", -1, -1)


# per-process initializer for the parallel pool: anchor cwd, set _FAI (main
# already built the .fai) and load the reef doc once, so it is not pickled
# per task.
def _init_worker():
    global _REEF_DOC
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          os.pardir))
    setup()
    _REEF_DOC = read_nc17_reef()


# --- bookkeeping -----------------------------------------------------------
def _sample_variant_names(limit):
    """First `limit` variant stems with plain-ACGT alleles AND a .vcf.gz."""
    names = []
    for fn in sorted(os.listdir(VARIANTS_DIR)):
        if not fn.endswith(".txt"):
            continue
        name = fn[:-4]
        if not os.path.exists(os.path.join(VARIANTS_VCF_DIR, name + ".vcf.gz")):
            continue
        v = _parse_variant(name)
        if _is_acgt(v.get("REF", "").upper()) and _is_acgt(v.get("ALT", "")
                                                            .upper()):
            names.append(name)
        if len(names) >= limit:
            break
    return names


def _all_variant_names():
    """All variant stems in variants/ (the full universe), sorted."""
    return sorted(fn[:-4] for fn in os.listdir(VARIANTS_DIR)
                  if fn.endswith(".txt"))


def _timed(acc, cnt, key, fn, *args):
    """Time fn(*args) into acc[key], bump cnt[key], return its result."""
    t = time.time()
    out = fn(*args)
    acc[key] += time.time() - t
    cnt[key] += 1
    return out


def _update_perf_comments(timings):
    """Best-effort: rewrite the '# Performance: ...' line above each timed def
    with its measured per-call average. Never fatal."""
    try:
        src = os.path.abspath(__file__)
        with open(src) as f:
            lines = f.readlines()
        for i, line in enumerate(lines):
            s = line.strip()
            if s.startswith("def ") and s[4:].split("(")[0] in timings:
                fn = s[4:].split("(")[0]
                for j in range(i - 1, max(i - 6, -1), -1):
                    if lines[j].lstrip().startswith("# Performance:"):
                        pad = lines[j][:len(lines[j]) - len(lines[j].lstrip())]
                        val = f"{timings[fn] * 1000:.1f} ms/call (sample)"
                        lines[j] = f"{pad}# Performance: {val}\n"
                        break
        with open(src, "w") as f:
            f.writelines(lines)
        print(f"[perf] updated Performance comments in {os.path.basename(src)}")
    except Exception as e:
        print(f"[perf] could not update Performance comments: {e}")


# --- log -------------------------------------------------------------------
# notes written verbatim into docs/reef_regex.log
_FULLMATCH_NOTE = (
    "NOTE: each regex is '^.{N}LITERAL.*'. The leading '^' is REQUIRED -- it\n"
    "      anchors LITERAL at offset N (Reef runs unanchored without it) and\n"
    "      enables '-p' projection. test_variant verifies via re.fullmatch.\n")
_EXTENDED_NOTE = (
    "NOTE: LITERAL-LENGTH HEURISTIC -- the literal usually spans bp_len\n"
    "      bases from POS. When reference and mutated stay identical for a\n"
    "      while after POS (tandem dup until the repeat tract ends; left-\n"
    "      anchored del until the deleted span begins), the literal is\n"
    "      EXTENDED to cover the ENTIRE changed allele (ALT) plus bp_len, so\n"
    "      it stays unique to the mutated doc. Large structural variants thus\n"
    "      get long literals (see the avg/max regex length below).\n")
_SKIPPED_NOTE = (
    "NOTE: SKIPPED variants -- a variant is skipped (NO regex produced, \n"
    "      ) when its allele cannot become a deterministic ACGT\n"
    "      literal, i.e., some aibiguity that our code cannot handle easily.\n"
    "      In this case we sipmly skip. Around 60 variants skipped.\n")


def write_reef_regex_log(tally, extended, skipped, n_total, wall=None,
                         regex_sum=0):
    """Write docs/reef_regex.log: provenance, the full-match / extended-literal
    / skipped NOTEs, the run tally, regex-size stats (avg + max), and the FULL
    list of SKIPPED variants (name + reason). `extended` is used only for the
    summary stats (count/avg/max), not enumerated. `regex_sum` is the total
    generated-regex length over all 'ok' variants (for the average)."""
    ext = sorted(extended, key=lambda t: -t[1])
    n_ok = tally.get("ok", 0)
    avg_all = regex_sum / n_ok if n_ok else 0.0
    avg_ext = (sum(t[1] for t in ext) / len(ext)) if ext else 0.0
    os.makedirs("docs", exist_ok=True)
    with open(os.path.join("docs", "reef_regex.log"), "w") as f:
        f.write("generator:         gen_reef_regex.py\n")
        f.write(f"date:              {datetime.date.today().isoformat()}\n")
        f.write(f"reference:         {REF_FASTA}\n")
        f.write(f"reef_doc:          {REEF_STR}\n")
        f.write("regex_form:        ^.{N}LITERAL.*   (N = POS-1)\n")
        f.write(f"default_bp_len:    {DEFAULT_BP_LEN}\n\n")
        f.write(_FULLMATCH_NOTE + "\n")
        f.write(_EXTENDED_NOTE + "\n")
        f.write(_SKIPPED_NOTE + "\n")
        f.write(f"total_processed:   {n_total}\n")
        f.write(f"tally:             ok={tally.get('ok', 0)} "
                f"skip={tally.get('skip', 0)} fail={tally.get('fail', 0)}\n")
        if wall is not None:
            f.write(f"wall_time:         {wall:.1f} s ({N_WORKERS} workers)\n")
        f.write(f"avg_regex_len:     {avg_all:.1f} chars (over {n_ok} ok)\n")
        if ext:
            f.write(f"max_regex_len:     {ext[0][1]} chars  ({ext[0][0]})\n")
        f.write(f"extended_literals: {len(ext)} variant(s) with literal > "
                f"bp_len={DEFAULT_BP_LEN}\n")
        f.write(f"avg_regex_len_ext: {avg_ext:.1f} chars (over {len(ext)} "
                f"extended)\n")
        f.write(f"skipped:           {len(skipped)} variant(s)\n")
        f.write("\n--- skipped variants (name<TAB>reason) ---\n")
        for name, reason in sorted(skipped):
            f.write(f"{name}\t{reason}\n")


# --- run modes -------------------------------------------------------------
# sample mode: serial, time each stage on a few variants, print a table, and
# refresh the "Performance:" comments above each function.
def run_sample(names):
    stages = ("setup", "read_nc17_reef", "gen_regex", "write_reef_regex",
              "apply_variant", "test_variant")
    acc = {k: 0.0 for k in stages}
    cnt = {k: 0 for k in stages}
    _timed(acc, cnt, "setup", setup)
    reef_doc = _timed(acc, cnt, "read_nc17_reef", read_nc17_reef)
    print(f"[sample] timing {len(names)} variant(s), bp_len={DEFAULT_BP_LEN}")
    passed = 0
    for name in names:
        try:
            rgx = _timed(acc, cnt, "gen_regex", gen_regex, name)
            _timed(acc, cnt, "write_reef_regex", write_reef_regex, name, rgx)
            _timed(acc, cnt, "apply_variant", apply_variant, name)
            _timed(acc, cnt, "test_variant", test_variant, name, reef_doc, rgx)
            passed += 1
        except Exception as e:
            print(f"  [skip] {name}: {type(e).__name__}: {e}")
    timings = {k: acc[k] / max(cnt[k], 1) for k in stages}
    print(f"[sample] {passed}/{len(names)} passed test_variant")
    print("[sample] per-call timings (ms):")
    for k in stages:
        print(f"    {k:18} {timings[k] * 1000:10.1f}")
    _update_perf_comments(timings)


# real mode: build the .fai once, then run process_variant across ALL variants
# in parallel. Does NOT update the Performance comments.
def run_real(names):
    setup()  # build the .fai once, before fanning out (avoids an index race)
    print(f"[real] {len(names)} variants on {N_WORKERS} workers")
    tally = {"ok": 0, "skip": 0, "fail": 0}
    extended = []   # (name, regex_len, literal_len) for literal_len > bp_len
    skipped = []    # (name, reason)
    regex_sum = 0   # total generated-regex length over 'ok' variants
    done = 0
    t0 = time.time()
    with ProcessPoolExecutor(max_workers=N_WORKERS,
                             initializer=_init_worker) as ex:
        for name, status, detail, lit, rlen in ex.map(process_variant, names):
            tally[status] += 1
            done += 1
            if status == "ok":
                regex_sum += rlen
                if lit > DEFAULT_BP_LEN:
                    extended.append((name, rlen, lit))
            elif status == "skip":
                skipped.append((name, detail))
            elif status == "fail":
                print(f"  [fail] {name}: {detail}")
            if done % 500 == 0:
                print(f"  [progress] {done}/{len(names)} {tally}")
    wall = time.time() - t0
    avg = regex_sum / tally["ok"] if tally["ok"] else 0.0
    mx = max(extended, key=lambda t: t[1]) if extended else (None, 0, 0)
    print(f"[real] done: {tally}  extended_literals={len(extended)}  "
          f"avg_regex_len={avg:.1f}  max_regex_len={mx[1]} ({mx[0]})")
    write_reef_regex_log(tally, extended, skipped, len(names), wall, regex_sum)


def main():
    # anchor cwd to the project root (one level above scripts/); no abs paths
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          os.pardir))
    all_names = _all_variant_names()
    print(f"[main] total variants: {len(all_names)}  b_real_run={b_real_run}")
    if b_real_run:
        run_real(all_names)
    else:
        run_sample(_sample_variant_names(SAMPLE_N))


if __name__ == "__main__":
    main()
