# -------------------------------------------
# Creator: BORA Author
# Date: 05/25/2026
# Purpose: retrieve all disease-related (Pathogenic / Likely pathogenic)
#          variants for one chromosome from the NCBI ClinVar bulk VCF.
#
# Download a pinned, dated ~250MB clinvar_<release>.vcf.gz once, verify it
# against the published MD5, and record full provenance in docs/retrieve_log.txt.
#
# This script ONLY retrieves + filters + stores variant info. 
# NOTE: parser code partly generated by Claude Code. Results verified
#   manually. All audited by author.
# -------------------------------------------

import os
import gzip
import shutil
import hashlib
import datetime
import subprocess
import urllib.request

# --- configuration ---------------------------------------------------------
# SNAPSHOT PIN: this run is locked to the ClinVar release that was current on
# SNAPSHOT_DATE. Running this script on ANY later date downloads and verifies
# the EXACT SAME FILE (enforced by EXPECTED_MD5 below) -- not a newer release.
#
#   SNAPSHOT_DATE   the day the pin was taken ("today")
#   CLINVAR_RELEASE the weekly release current on that day (immutable, dated)
#   EXPECTED_MD5    md5 of that exact .vcf.gz; the download is rejected unless
#                   it matches, so success <=> byte-identical to the snapshot.
SNAPSHOT_DATE = "2026-05-25"
CLINVAR_RELEASE = "20260523"
EXPECTED_MD5 = "f56bc2236287e25e472fda9bda9d7551"

_VCF_BASE = "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38"
# Candidate URLs tried in order. A release lives in weekly/ while current, then
# NCBI rotates it into the permanent archive_2.0/<year>/ dir. Trying both keeps
# the same dated file retrievable now AND after rotation.
CLINVAR_URLS = [
    f"{_VCF_BASE}/weekly/clinvar_{CLINVAR_RELEASE}.vcf.gz",
    f"{_VCF_BASE}/archive_2.0/{CLINVAR_RELEASE[:4]}/clinvar_{CLINVAR_RELEASE}.vcf.gz",
]
GZ_FILE = f"clinvar_{CLINVAR_RELEASE}.vcf.gz"
DOCS_DIR = "docs"
VARIANTS_DIR = "variants"
VARIANTS_VCF_DIR = "variants_vcf"
PROGRESS_EVERY = 500  # progress_report cadence (one line per this many variants)
LIST_FILE = os.path.join(DOCS_DIR, "variants.list.txt")
LOG_FILE = os.path.join(DOCS_DIR, "retrieve_log.txt")
TARGET_CLNSIG = {"Pathogenic", "Likely_pathogenic", 
	"Pathogenic/Likely_pathogenic"}

# Fallback chrom -> RefSeq accession (GRCh38.p14). Normally taken from CLNHGVS.
ACC_FALLBACK = {"17": "NC_000017.11", "21": "NC_000021.9"}

# --- helpers ---------------------------------------------------------------
def parse_info(info):
    """Parse a VCF INFO column 'k=v;k=v;flag' into a dict (flags -> True)."""
    d = {}
    for field in info.split(";"):
        if "=" in field:
            k, v = field.split("=", 1)
            d[k] = v
        elif field:
            d[field] = True
    return d


def clnsig_keep(clnsig):
    """True if any '|'-separated component of CLNSIG is in TARGET_CLNSIG."""
    if not clnsig:
        return False
    return any(part in TARGET_CLNSIG for part in clnsig.split("|"))


def accession_from(clnhgvs, chrom):
    """RefSeq accession for the SPDI sequence part.
    Prefer the accession embedded in CLNHGVS (e.g. 'NC_000017.11:g....');
    fall back to the hardcoded map keyed by chromosome string.
    """
    if clnhgvs:
        first = clnhgvs.split("|")[0]
        if ":" in first:
            return first.split(":", 1)[0]
    return ACC_FALLBACK.get(str(chrom))


def compute_md5(path, chunk=1024 * 1024):
    """Streaming MD5 of a local file (handles the ~250MB gz without loading it)."""
    h = hashlib.md5()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(chunk), b""):
            h.update(block)
    return h.hexdigest()


def canonical_name(vid, alleleid, spdi):
    """Short, stable, canonical filename stem for a ClinVar record.
    Preference: VCV accession (VCV + zero-padded VariationID) -> AID<ALLELEID>
    -> a short SPDI hash. SPDI itself is unusable as a filename because large
    indels carry multi-kb REF/ALT and blow past the 255-byte limit."""
    if vid.isdigit():
        return "VCV" + vid.zfill(9)
    if alleleid.isdigit():
        return "AID" + alleleid
    return "SPDI_" + hashlib.sha1(spdi.encode()).hexdigest()[:16]


def write_variant_file(variants_dir, name, rec):
    """Write one 'key: value' detail file named <name>.txt."""
    path = os.path.join(variants_dir, name + ".txt")
    with open(path, "w") as f:
        for k, v in rec:
            f.write(f"{k}: {v}\n")
    return path

# --- external-tool wrappers (bgzip / tabix) --------------------------------
# Project rule: one verify_* and one run_<tool> per external binary, all
# invoked with an args LIST (never shell=True) to avoid command injection.
def verify_tool_existence(tool):
    """Return the resolved path of an external tool, or abort if it is missing."""
    path = shutil.which(tool)
    if path is None:
        raise RuntimeError(f"required external tool not on PATH: {tool}")
    return path


def run_bgzip(vcf_path):
    """bgzip a plaintext VCF in place -> <vcf_path>.gz (removes the plaintext)."""
    subprocess.run(["bgzip", "-f", vcf_path], check=True)
    return vcf_path + ".gz"


def run_tabix(gz_path):
    """tabix-index a bgzipped VCF -> <gz_path>.tbi (needed by bcftools consensus)."""
    subprocess.run(["tabix", "-p", "vcf", "-f", gz_path], check=True)
    return gz_path + ".tbi"


# from record, generate the vcf specification and convert to .gz format so it
# can be applied to the reference FASTA by the `bcftools consensus` command.
def write_variant_as_vcf(variants_dir, name, rec):
    """Write one variant as a minimal bgzipped + tabix-indexed VCF.

    CHROM is the RefSeq accession taken from SPDI (e.g. NC_000017.11) so it
    matches the reference FASTA header consensus is applied to -- NOT bare '17'.
    A FORMAT=GT column with a hom-alt sample (1/1) is required: `bcftools
    consensus` applies a variant ONLY if it carries a sample genotype; a
    sites-only VCF would apply nothing ("Applied 0 variants").
    Produces <name>.vcf.gz (+ .tbi) under variants_dir; returns the .gz path.
    """
    d = dict(rec)
    acc = d["SPDI"].split(":", 1)[0]
    pos, ref, alt = d["POS"], d["REF"], d["ALT"]
    vcf_path = os.path.join(variants_dir, name + ".vcf")
    with open(vcf_path, "w") as f:
        f.write("##fileformat=VCFv4.2\n")
        f.write(f"##contig=<ID={acc}>\n")
        f.write('##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">\n')
        f.write("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n")
        f.write(f"{acc}\t{pos}\t{name}\t{ref}\t{alt}\t.\t.\t.\tGT\t1/1\n")
    gz_path = run_bgzip(vcf_path)
    run_tabix(gz_path)
    return gz_path


# print a progress line every PROGRESS_EVERY items and on the final item, so the
# slow per-variant write loop (bgzip+tabix) does not run silently.
def progress_report(cur_id, total):
    """Emit '[progress] cur/total (pct%)' at a fixed cadence and at completion."""
    if cur_id % PROGRESS_EVERY == 0 or cur_id == total:
        pct = (100.0 * cur_id / total) if total else 100.0
        print(f"[progress] {cur_id}/{total} variants ({pct:.1f}%)")

def write_retrieve_log(version, chrom, total, chrom_total, kept, prov):
    """Write run date + snapshot provenance (pinned release, expected/actual
    checksum, server metadata) + counts.
    prov keys: snapshot_date, release, source_url, file_bytes, last_modified,
    md5_expected, md5_local, md5_verified."""
    os.makedirs(DOCS_DIR, exist_ok=True)
    with open(LOG_FILE, "w") as f:
        f.write(f"date:              {datetime.date.today().isoformat()}\n")
        f.write(f"snapshot_date:     {prov['snapshot_date']}\n")
        f.write(f"clinvar_release:   {prov['release']}\n")
        f.write(f"clinvar_version:   {version}\n")
        f.write(f"source_url:        {prov['source_url']}\n")
        f.write(f"file_bytes:        {prov['file_bytes']}\n")
        f.write(f"last_modified:     {prov['last_modified']}\n")
        f.write(f"md5_expected:      {prov['md5_expected']}\n")
        f.write(f"md5_local:         {prov['md5_local']}\n")
        f.write(f"md5_verified:      {prov['md5_verified']}\n")
        f.write(f"chromosome:        {chrom}\n")
        f.write(f"clnsig_kept:       {' | '.join(sorted(TARGET_CLNSIG))}\n")
        f.write(f"total_records:     {total}\n")
        f.write(f"chr{chrom}_records:     {chrom_total}\n")
        f.write(f"chr{chrom}_pl_kept:     {kept}\n")
        f.write(f"variants_txt_dir:  {VARIANTS_DIR}\n")
        f.write(f"variants_vcf_dir:  {VARIANTS_VCF_DIR}\n")


# --- pipeline steps --------------------------------------------------------
# download the pinned dated ~250MB ClinVar VCF to local dir, trying each
# candidate URL (weekly/ then archive_2.0/) until one succeeds.
def download_all(urls, dest):
    """Stream-download the pinned VCF from the first working URL; skip if a
    complete file already exists. Downloads to <dest>.part then atomically
    renames, so a present final file is always complete (idempotent re-runs).
    Returns (source_url, last_modified); source_url is None if skipped."""
    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        print(f"[download] {dest} already present ({os.path.getsize(dest)} bytes); skipping")
        return None, ""
    part = dest + ".part"
    last_err = None
    for url in urls:
        try:
            print(f"[download] trying {url}")
            with urllib.request.urlopen(url, timeout=120) as resp, open(part, "wb") as out:
                last_modified = resp.headers.get("Last-Modified", "")
                shutil.copyfileobj(resp, out, length=1024 * 1024)
            os.replace(part, dest)
            print(f"[download] saved {dest} ({os.path.getsize(dest)} bytes)")
            return url, last_modified
        except Exception as e:
            last_err = e
            print(f"[download] failed: {e}")
    if os.path.exists(part):
        os.remove(part)
    raise RuntimeError(f"all candidate URLs failed; last error: {last_err}")


# given the chromosome id (e.g. 17 or 21) and the path to clinvar.vcf.gz,
# stream the gz and filter on:  chromosome_id + (Pathogenic | Likely pathogenic)
# Recreates 1 file and 2 dirs (removing them first if present):
#   (1) docs/variants.list.txt   (2) variants/   (3) variants_vcf/
# For each kept variant:
#   (1) append its canonical name (VCV accession) to docs/variants.list.txt
#   (2) write its full info (incl. SPDI) to variants/<VCV>.txt
#   (3) write a bgzipped+indexed single-variant VCF to variants_vcf/<VCV>.vcf.gz
def filter_data(gz_file, chromosome_id):
    chrom_str = str(chromosome_id)

    # fresh outputs
    if os.path.exists(LIST_FILE):
        os.remove(LIST_FILE)
    if os.path.isdir(VARIANTS_DIR):
        shutil.rmtree(VARIANTS_DIR)
    if os.path.isdir(VARIANTS_VCF_DIR):
        shutil.rmtree(VARIANTS_VCF_DIR)
    os.makedirs(VARIANTS_DIR, exist_ok=True)
    os.makedirs(VARIANTS_VCF_DIR, exist_ok=True)
    os.makedirs(DOCS_DIR, exist_ok=True)

    clinvar_version = "unknown"
    total = chrom_total = 0
    seen = set()  # dedupe canonical names so list <-> files stay 1:1
    kept_recs = []  # (name, rec) per kept variant, in stream order

    # pass 1: stream the gz once and collect kept variants (cheap, no writes)
    with gzip.open(gz_file, "rt") as fh:
        for line in fh:
            if line.startswith("#"):
                if line.startswith("##fileDate="):
                    clinvar_version = line.strip().split("=", 1)[1]
                continue
            total += 1
            cols = line.rstrip("\n").split("\t")
            if len(cols) < 8:
                continue
            chrom, pos, vid, ref, alt = cols[0], cols[1], cols[2], cols[3], cols[4]
            if chrom != chrom_str:
                continue
            chrom_total += 1
            info = parse_info(cols[7])
            clnsig = info.get("CLNSIG", "")
            if not clnsig_keep(clnsig):
                continue

            acc = accession_from(info.get("CLNHGVS", ""), chrom)
            spdi = f"{acc}:{int(pos) - 1}:{ref}:{alt}"
            alleleid = info.get("ALLELEID", "")
            name = canonical_name(vid, alleleid, spdi)  # filename / list entry
            if name in seen:
                continue
            seen.add(name)

            vcv = "VCV" + vid.zfill(9) if vid.isdigit() else ""
            rec = [
                ("SPDI", spdi),
                ("CHROM", chrom),
                ("POS", pos),
                ("REF", ref),
                ("ALT", alt),
                ("CLNSIG", clnsig),
                ("CLNDN", info.get("CLNDN", "")),
                ("GENEINFO", info.get("GENEINFO", "")),
                ("CLNHGVS", info.get("CLNHGVS", "")),
                ("RS", ("rs" + info["RS"]) if "RS" in info else ""),
                ("ALLELEID", info.get("ALLELEID", "")),
                ("VARIATION_ID", vid),
                ("VCV", vcv),
            ]
            kept_recs.append((name, rec))

    # pass 2: write outputs now that the total is known, reporting progress
    # (per-variant bgzip+tabix dominates the runtime).
    kept = len(kept_recs)
    with open(LIST_FILE, "w") as lst:
        for i, (name, rec) in enumerate(kept_recs, 1):
            write_variant_file(VARIANTS_DIR, name, rec)
            write_variant_as_vcf(VARIANTS_VCF_DIR, name, rec)
            lst.write(name + "\n")
            progress_report(i, kept)

    print(f"[filter] clinvar_version={clinvar_version} "
          f"total={total} chr{chrom_str}={chrom_total} kept={kept}")
    return clinvar_version, total, chrom_total, kept


# read the list; for each variant verify the corresponding file exists in
# variants/. Verify the list count matches the number of files. REPORT total.
def test_variants(list_path, variants_dir):
    with open(list_path) as f:
        spdis = [l.strip() for l in f if l.strip()]
    n_list = len(spdis)
    missing = [s for s in spdis
               if not os.path.isfile(os.path.join(variants_dir, s + ".txt"))]
    n_files = len([n for n in os.listdir(variants_dir) if n.endswith(".txt")])
    ok = (not missing) and (n_list == n_files)
    print(f"[test] list={n_list} files={n_files} missing={len(missing)} "
          f"-> {'PASS' if ok else 'FAIL'}")
    for s in missing[:10]:
        print(f"  missing file for: {s}")
    print(f"[test] TOTAL VARIANTS: {n_list}")
    return ok


# remove the clinvar.vcf.gz
def remove_vcf_gz(gz_path):
    if os.path.exists(gz_path):
        os.remove(gz_path)
        print(f"[cleanup] removed {gz_path}")
    else:
        print(f"[cleanup] {gz_path} not present")


# -------------------------------------------
# MAIN
# -------------------------------------------
def main():
    # this script lives in scripts/, one level below the project root where the
    # data dirs are; anchor cwd to that root so the relative paths below resolve
    # (works regardless of where the script is invoked from; no absolute paths).
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))
    chrom_id = 17

    # 0. fail fast if the external tools used for the per-variant VCFs are absent
    verify_tool_existence("bgzip")
    verify_tool_existence("tabix")

    # 1. download the pinned dated ClinVar VCF (skips if already present),
    #    trying weekly/ then archive_2.0/
    source_url, last_modified = download_all(CLINVAR_URLS, GZ_FILE)
    if source_url is None:
        source_url = "(local cache; not re-downloaded)"

    # 1b. GUARANTEE same-file-as-snapshot: verify against the HARDCODED md5.
    #     Any byte difference (newer release, truncation, tampering) aborts.
    md5_local = compute_md5(GZ_FILE)
    md5_verified = (md5_local == EXPECTED_MD5)
    print(f"[verify] md5_local={md5_local} expected={EXPECTED_MD5} "
          f"-> {'OK' if md5_verified else 'MISMATCH'}")
    if not md5_verified:
        raise SystemExit(
            f"[verify] ABORT: file does not match the pinned {SNAPSHOT_DATE} snapshot "
            f"(release {CLINVAR_RELEASE}); refusing to proceed with a different file.")

    # 2. filter chr17 disease-related variants (Pathogenic | Likely pathogenic)
    version, total, chrom_total, kept = filter_data(GZ_FILE, chrom_id)

    # 2b. record date + full snapshot provenance + counts
    prov = {
        "snapshot_date": SNAPSHOT_DATE,
        "release": CLINVAR_RELEASE,
        "source_url": source_url,
        "file_bytes": os.path.getsize(GZ_FILE),
        "last_modified": last_modified,
        "md5_expected": EXPECTED_MD5,
        "md5_local": md5_local,
        "md5_verified": md5_verified,
    }
    write_retrieve_log(version, str(chrom_id), total, chrom_total, kept, prov)

    # 3. test that the extraction is consistent
    test_variants(LIST_FILE, VARIANTS_DIR)

    # 4. clean up the big download
    remove_vcf_gz(GZ_FILE)


if __name__ == "__main__":
    main()
