# ---------------------------------------------------------------------------
# Generate ClamAV-compatible logical signatures (chr17variants.ldb) accepted
# by ZkregPlus from the reef_regex/ folder, and validate end-to-end with
# real clamscan invocations on packed-binary chr17 inputs.
# Author: BORA paper author; function bodies generated by Claude Code 4.7
#   code audited, and test plan developed and the paper author.
# ---------------------------------------------------------------------------
#
# Encodin DNA -> 4-bit nibble: A=0xa, C=0xc, G=0xe, T=0xf; two
#   nucleotides packed into one byte; odd-length sequences pad the trailing
#   low nibble with 'a'.
#
# Hex translation: each reef regex `^.{N}LITERAL.*` is mapped to a single
#   ClamAV hex subsig on the packed byte stream at offset N//2 (no PCRE, no
#   trigger). Four cases on (parity of N, parity of L); odd boundaries use
#   a nibble wildcard (`?a` / `a?`). On strictly-ACGT input every byte is
#   in {a,c,e,f}^2, so `?a` matches exactly the 4 alphabet bytes
#   {aa, ca, ea, fa} -- equivalent to the explicit alphabet class but
#   shorter and natively SDE-able by ZkregPlus.
#
# Tests: sample a number of variants
#   (1) for each variant:
#      generate the mutated sequence by applying the vairant to NC00017.01
#      using the bcfotools.
#      then verify this mutated sequence does FAIL the logical sig
#        of the variant (i.e., it does contain the variant's regex)
#   (2) verify that the NC00017.01 is FREE OF all sigs 

import os
import random
import re
import shutil
import subprocess
import sys
import time

# Import the bcftools/samtools setup + apply_variant from the sibling script,
# rather than re-implementing the mutation path.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_reef_regex  # noqa: E402

from eval_reef import gen_machine_config  # noqa: E402


# --- paths & constants -----------------------------------------------------
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGEX_DIR = os.path.join(ROOT, "reef_regex")
CLAMAV_REGEX_DIR = os.path.join(ROOT, "clamav_regex")
CHR17_DIR = os.path.join(ROOT, "chr17_samples")
DOCS_DIR = os.path.join(ROOT, "docs")
REEF_TXT = os.path.join(CHR17_DIR, "NC_000017.11.reef.txt")
REF_BIN = os.path.join(CHR17_DIR, "NC_000017.11.reef.bin")
LDB_PATH = os.path.join(CLAMAV_REGEX_DIR, "chr17variants.ldb")
LOG_PATH = os.path.join(DOCS_DIR, "gen_bora_regex.log")
STAGE_DIR = "/tmp/test_regex_bora"
STAGE_LDB = os.path.join(STAGE_DIR, "test_sample.ldb")
STAGE_MUT = os.path.join(STAGE_DIR, "mut.bin")

# Reproducible sampling (matches eval_reef.py).
RANDOM_SEED = 20260527

# SAMPLE-1 alphabet-padding sig. Original spec's hex subsigs had odd lengths
# (33 and 19) which ClamAV rejects (`cli_mpool_hex2ui` malformed hexstring);
# trailing odd char dropped per user instruction to produce valid 32/18-char
# hex. Intent (broad AC-trie alphabet coverage) preserved.
SAMPLE1_LINE = ("Win.Alphabet.SAMPLE-1;Engine:51-255,Target:1;0|1;"
                "09afcdeb1928374650123457890abcde;"
                "0123498765423afedc")
SAMPLE1_NAME = "Win.Alphabet.SAMPLE-1"


# --- nibble / packing helpers ----------------------------------------------
# Nibble values for the 4 reef-alphabet bases (Q1).
_NIBBLE = {ord('A'): 0xa, ord('C'): 0xc, ord('G'): 0xe, ord('T'): 0xf}
# A 256-entry translate table mapping each ACGT byte to its nibble value;
# non-ACGT bytes map to 0 (input is assumed pre-folded by convert_nc_to_str).
_TO_NIBBLE_TABLE = bytes((_NIBBLE.get(b, 0)) for b in range(256))
# Lookup table to shift a byte left by 4 (mask to 8 bits) via translate.
_SHIFT4_TABLE = bytes(((b << 4) & 0xff) for b in range(256))


def seq_to_bin(seq):
    """Pack reef-alphabet bytes (ACGT) into packed bytes, 2 nt/byte.
    Trailing odd nucleotide padded with low nibble = 'a' (per Q2)."""
    if isinstance(seq, str):
        seq = seq.encode("ascii")
    nibbles = seq.translate(_TO_NIBBLE_TABLE)
    n = len(nibbles)
    if n & 1:
        nibbles = nibbles + bytes([0xa])
        n += 1
    hi = nibbles[0::2].translate(_SHIFT4_TABLE)
    lo = nibbles[1::2]
    # Bignum OR runs in C; much faster than a Python pair-loop for ~83 MB.
    big_hi = int.from_bytes(hi, "big")
    big_lo = int.from_bytes(lo, "big")
    return (big_hi | big_lo).to_bytes(len(hi), "big")


def write_bin(seq, dst_path):
    """seq_to_bin(seq) -> dst_path. Returns dst_path."""
    data = seq_to_bin(seq)
    with open(dst_path, "wb") as f:
        f.write(data)
    return dst_path


# --- hex-line construction (the 4-case parity dispatch) --------------------
def _pack_lit_aligned_hex(lit, start, end):
    """Pack lit[start:end] (byte-aligned, even length) -> raw hex like
    'ac32ef...' (no `\\x` escapes). lit is bytes of ACGT chars."""
    n = end - start
    if n & 1:
        raise ValueError("internal: aligned-pack slice length must be even")
    out = []
    for i in range(start, end, 2):
        h = _NIBBLE[lit[i]]
        l = _NIBBLE[lit[i + 1]]
        out.append("%02x" % ((h << 4) | l))
    return "".join(out)


def _build_hex_body(lit, n_odd, l_odd):
    """Return ClamAV hex body for the literal at offset N//2. Edges use
    nibble wildcards (`?<n>` / `<n>?`); on strictly-ACGT input this matches
    only the 4 alphabet bytes."""
    L = len(lit)
    parts = []
    if not n_odd:
        if not l_odd:
            # Case 1: N even, L even -> L/2 packed bytes, no wildcards.
            parts.append(_pack_lit_aligned_hex(lit, 0, L))
        else:
            # Case 2: N even, L odd -> (L-1)/2 packed + trailing low-nibble wildcard.
            parts.append(_pack_lit_aligned_hex(lit, 0, L - 1))
            parts.append("%x?" % _NIBBLE[lit[L - 1]])
    else:
        # Cases 3 & 4: N odd -> leading high-nibble wildcard.
        parts.append("?%x" % _NIBBLE[lit[0]])
        if l_odd:
            # Case 3: N odd, L odd -> leading wildcard + (L-1)/2 packed.
            parts.append(_pack_lit_aligned_hex(lit, 1, L))
        else:
            # Case 4: N odd, L even -> leading + (L-2)/2 packed + trailing wildcard.
            parts.append(_pack_lit_aligned_hex(lit, 1, L - 1))
            parts.append("%x?" % _NIBBLE[lit[L - 1]])
    return "".join(parts)


_REGEX_RE = re.compile(r"^\^\.\{(\d+)\}([ACGT]+)\.\*$")


def reef_regex_to_clamav(regex_name, regex_str):
    """Convert one '^.{N}LITERAL.*' regex into a ClamAV LDB hex-subsig line
    in offset-prefix form: anchor in the subsig `<offset>:` prefix; body is
    a packed-byte hex run with at most two nibble wildcards on the edges.
    No PCRE, no trigger. Feeds ZkregPlus PMRegItem `Wildcard((N,N))` +
    `Literal(bytes)` natively. Returns (line, None) or (None, reason)."""
    s = regex_str.strip()
    m = _REGEX_RE.match(s)
    if not m:
        return None, "regex shape != '^.{N}LITERAL.*'"
    n_anchor = int(m.group(1))
    lit = m.group(2).encode("ascii")
    n_odd = bool(n_anchor & 1)
    l_odd = bool(len(lit) & 1)

    hex_body = _build_hex_body(lit, n_odd, l_odd)
    off = n_anchor // 2

    sig_name = "Bora.Chr17." + regex_name
    return ("%s;Engine:81-255,Target:0;0;%d:%s"
            % (sig_name, off, hex_body)), None


# --- whole-corpus LDB generation -------------------------------------------
def gen_chr17variants_ldb(regex_dir=REGEX_DIR, ldb_path=LDB_PATH):
    """Serial loop over reef_regex/: convert each to LDB line, prepend
    SAMPLE-1, write a single .ldb file. Returns (n_written, n_skipped,
    skipped_by_reason)."""
    files = sorted(f for f in os.listdir(regex_dir) if f.endswith(".txt"))
    lines = [SAMPLE1_LINE]
    skipped = {}
    for fn in files:
        name = fn[:-4]
        with open(os.path.join(regex_dir, fn)) as f:
            rgx = f.read().strip()
        line, reason = reef_regex_to_clamav(name, rgx)
        if line is None:
            skipped.setdefault(reason, []).append(name)
            continue
        lines.append(line)
    os.makedirs(os.path.dirname(ldb_path), exist_ok=True)
    with open(ldb_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return len(lines) - 1, sum(len(v) for v in skipped.values()), skipped


# --- clamscan external-tool wrapper (project rule: verify_ + run_) ---------
def verify_tool_existence(tool="clamscan"):
    """Resolve `tool` on PATH or raise. Mirrors gen_reef_regex's convention."""
    path = shutil.which(tool)
    if path is None:
        raise RuntimeError("required tool not on PATH: %s" % tool)
    return path


_CLAMSCAN_HIT_RE = re.compile(r"^(.+):\s+(\S+)\s+FOUND$")


def run_clamscan(ldb_path, target_path):
    """Invoke `clamscan -d <ldb> --no-summary <target>` via argv list (no
    shell). Returns the set of matched signature names. clamscan exit codes:
    0 = clean, 1 = found, 2 = error (raises)."""
    res = subprocess.run(
        ["clamscan", "-d", ldb_path, "--no-summary", target_path],
        capture_output=True, text=True, check=False)
    if res.returncode == 2:
        raise RuntimeError("clamscan error (exit 2): %s"
                           % res.stderr.strip())
    hits = set()
    for line in res.stdout.splitlines():
        m = _CLAMSCAN_HIT_RE.match(line)
        if m:
            sig = m.group(2)
            # clamscan appends `.UNOFFICIAL` to user-loaded sigs (anything
            # not from the official ClamAV DB). Strip so callers compare
            # against the sig name as written in the .ldb.
            if sig.endswith(".UNOFFICIAL"):
                sig = sig[:-len(".UNOFFICIAL")]
            hits.add(sig)
    return hits


# --- sampling + staging ----------------------------------------------------
def _all_variant_names(regex_dir=REGEX_DIR):
    """Sorted list of variant names (reef_regex/<name>.txt -> name)."""
    return sorted(f[:-4] for f in os.listdir(regex_dir)
                  if f.endswith(".txt"))


def sample_variants(n, seed=RANDOM_SEED, regex_dir=REGEX_DIR):
    """Draw n variant names with a seeded RNG over sorted reef_regex/. The
    RNG state is left consumed (rng object not returned); for reproducible
    'pick first 5' beyond SAMPLE_SIZE, use sample_with_extras() below."""
    pop = _all_variant_names(regex_dir)
    return random.Random(seed).sample(pop, n)


def sample_with_extras(n, extras, seed=RANDOM_SEED, regex_dir=REGEX_DIR):
    """Return (sample_of_n, extras_appended) where the n+extras draws come
    from a single rng stream over the sorted population. Used to materialize
    5 variant bins even when SAMPLE_SIZE < 5: first n go to the test loop,
    the next `extras` extend the materialization list."""
    pop = _all_variant_names(regex_dir)
    big = random.Random(seed).sample(pop, n + extras)
    return big[:n], big[n:]


def prepare_stage(sample_names, full_ldb_path=LDB_PATH,
                  stage_dir=STAGE_DIR):
    """Build a subset .ldb at <stage_dir>/test_sample.ldb containing only
    Bora.Chr17.<v> for v in sample_names plus the SAMPLE-1 line. Returns
    the staged .ldb path."""
    os.makedirs(stage_dir, exist_ok=True)
    want = set("Bora.Chr17." + v for v in sample_names)
    want.add(SAMPLE1_NAME)
    kept = []
    with open(full_ldb_path) as f:
        for line in f:
            name = line.split(";", 1)[0]
            if name in want:
                kept.append(line.rstrip("\n"))
    with open(STAGE_LDB, "w") as f:
        f.write("\n".join(kept) + "\n")
    return STAGE_LDB


# --- mutation + bin materialization ----------------------------------------
def gen_mutant_bin(variant_name, dst_path):
    """apply_variant (whole-chromosome bcftools consensus) -> pack -> write.
    Returns (bytes_written, t_apply, t_pack, t_write)."""
    t0 = time.time()
    seq = gen_reef_regex.apply_variant(variant_name)
    t_apply = time.time() - t0
    t1 = time.time()
    data = seq_to_bin(seq)
    t_pack = time.time() - t1
    t2 = time.time()
    with open(dst_path, "wb") as f:
        f.write(data)
    t_write = time.time() - t2
    return len(data), t_apply, t_pack, t_write


# --- the two test primitives -----------------------------------------------
def test_one_variant(sample_names, idx, ldb_path=STAGE_LDB,
                     stage_dir=STAGE_DIR, persist_path=None):
    """For sample_names[idx]: apply mutation, pack, write to stage_dir/mut.bin
    (overwriting prior iteration), run clamscan, assert the variant's sig
    appears in the match set. Returns a result dict with per-stage timings.
    If persist_path is given, also write a copy of the mut bin there (used
    to materialize the chr17_samples/ artifacts without recomputing)."""
    variant = sample_names[idx]
    mut_path = os.path.join(stage_dir, "mut.bin")
    expected = "Bora.Chr17." + variant

    bytes_written, t_apply, t_pack, t_write = gen_mutant_bin(variant,
                                                             mut_path)
    if persist_path is not None:
        shutil.copyfile(mut_path, persist_path)

    t3 = time.time()
    hits = run_clamscan(ldb_path, mut_path)
    t_scan = time.time() - t3

    return {
        "idx": idx,
        "variant": variant,
        "expected_sig": expected,
        "hit": expected in hits,
        "all_hits": hits,
        "extra_hits": hits - {expected, SAMPLE1_NAME},
        "bytes": bytes_written,
        "t_apply": t_apply,
        "t_pack": t_pack,
        "t_write": t_write,
        "t_scan": t_scan,
        "wall_s": t_apply + t_pack + t_write + t_scan,
        "persisted_to": persist_path,
    }


def test_ref_free_of_sample(sample_names, ref_bin_path=REF_BIN,
                            ldb_path=STAGE_LDB):
    """Run clamscan against ref_bin (the un-mutated chr17.bin). Assert no
    Bora.Chr17.<v> for v in sample_names appears. SAMPLE-1 hits are
    ignored (alphabet sig may always match). Returns result dict."""
    t0 = time.time()
    hits = run_clamscan(ldb_path, ref_bin_path)
    t_scan = time.time() - t0
    # Names of sigs that MUST NOT fire on the un-mutated reference bin.
    # Each variant's literal is in the mutant, never in the reference.
    # (SAMPLE-1 is not in this set, so it's allowed to fire harmlessly.)
    forbidden_sigs = {"Bora.Chr17." + v for v in sample_names}
    # Any sig that BOTH fired AND is in `forbidden_sigs` is a leak --
    # i.e. it falsely flagged a variant that isn't actually there.
    leaked = hits.intersection(forbidden_sigs)
    return {
        "ref_bin": ref_bin_path,
        "ldb": ldb_path,
        "all_hits": hits,
        "leaked": leaked,
        "hit": len(leaked) == 0,
        "wall_s": t_scan,
    }


# --- log writer ------------------------------------------------------------
def _fmt_bytes(n):
    if n >= (1 << 30):
        return "%.2f GiB" % (n / (1 << 30))
    if n >= (1 << 20):
        return "%.2f MiB" % (n / (1 << 20))
    if n >= (1 << 10):
        return "%.2f KiB" % (n / (1 << 10))
    return "%d B" % n


def write_log(timings, ldb_stats, ref_bin_size,
              sample_names, per_variant_results, ref_result,
              materialize_results, sample_size,
              log_path=LOG_PATH):
    """Compose docs/gen_bora_regex.log from all stages' captured state."""
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    n_written, n_skipped, skip_by_reason = ldb_stats
    total_wall = sum(timings.values())
    passed = sum(1 for r in per_variant_results if r["hit"])
    failed = len(per_variant_results) - passed

    lines = []
    lines.append("gen_bora_regex.log")
    lines.append("==================")
    lines.append("")
    lines.append("# generated by scripts/gen_bora_regex.py")
    lines.append("# total wall time: %.1f s (%.2f min)"
                 % (total_wall, total_wall / 60.0))
    lines.append("# how generated: gen_bora_regex.py (1) converts each")
    lines.append("#   reef_regex/*.txt -> a ClamAV LDB hex-subsig line")
    lines.append("#   in offset-prefix form (`<N//2>:<hex>`), with nibble")
    lines.append("#   wildcards on parity edges.")
    lines.append("#   (2) packs NC_000017.11.reef.txt into NC_000017.11.reef.bin")
    lines.append("#   (A=0xa, C=0xc, G=0xe, T=0xf; 2 nt/byte; tail-pad 'a');")
    lines.append("#   (3) test by asserting: for each variant: if applying ")
    lines.append("#      variant to dna document, and run clamav over it, the sig ")
    lines.append("#      for the variant does appear; then run clamav over benign dna doc ")
    lines.append("#      using all sigs, none is flagged")
    lines.append("#   (4) sampled 4 variants and generated the mutated seq ")
    lines.append("#      and saved in chr17_samples dir/ ")
    lines.append("")
    lines.append("[machine config]")
    lines.append(gen_machine_config())
    lines.append("")
    lines.append("[invocation]")
    lines.append("SAMPLE_SIZE:   %d" % sample_size)
    lines.append("RANDOM_SEED:   %d" % RANDOM_SEED)
    lines.append("")
    lines.append("[stage timings (s)]")
    for k, v in timings.items():
        lines.append("  %-22s %.2f" % (k, v))
    lines.append("  %-22s %.2f" % ("TOTAL", total_wall))
    lines.append("")

    lines.append("[step 1: generate chr17variants.ldb]")
    lines.append("input dir:    %s" % os.path.relpath(REGEX_DIR, ROOT))
    lines.append("output:       %s" % os.path.relpath(LDB_PATH, ROOT))
    lines.append("sigs written: %d  (incl. 1 SAMPLE-1 = %d Bora.Chr17.*)"
                 % (n_written + 1, n_written))
    lines.append("skipped:      %d" % n_skipped)
    for reason, names in skip_by_reason.items():
        lines.append("  %d  reason: %s" % (len(names), reason))
        for name in names[:5]:
            lines.append("    %s" % name)
        if len(names) > 5:
            lines.append("    ... (+%d more)" % (len(names) - 5))
    lines.append("")

    lines.append("[step 2: pack ref bin]")
    lines.append("input:  %s (%s)"
                 % (os.path.relpath(REEF_TXT, ROOT),
                    _fmt_bytes(os.path.getsize(REEF_TXT))))
    lines.append("output: %s (%s)"
                 % (os.path.relpath(REF_BIN, ROOT),
                    _fmt_bytes(ref_bin_size)))
    lines.append("")

    lines.append("[step 3: stage subset .ldb]")
    lines.append("stage_dir:   %s" % STAGE_DIR)
    lines.append("subset_ldb:  %s" % STAGE_LDB)
    lines.append("sample(%d):" % sample_size)
    for v in sample_names:
        lines.append("  %s" % v)
    lines.append("")

    lines.append("[step 4: per-variant clamscan tests (positive)]")
    lines.append("  idx  variant         hit  wall(s)  apply  pack  write   scan"
                 "   extra_hits")
    for r in per_variant_results:
        lines.append(
            "  %-4d %-15s %-4s %7.2f %6.2f %5.2f %6.2f %6.2f   %s"
            % (r["idx"], r["variant"], "YES" if r["hit"] else "NO",
               r["wall_s"], r["t_apply"], r["t_pack"], r["t_write"],
               r["t_scan"],
               sorted(r["extra_hits"]) if r["extra_hits"] else "{}"))
    lines.append("")
    lines.append("  passed: %d / %d" % (passed, passed + failed))
    lines.append("")

    lines.append("[step 5: ref-bin clamscan test (negative)]")
    lines.append("ref_bin: %s" % os.path.relpath(REF_BIN, ROOT))
    lines.append("sigs:    %d (SAMPLE_SIZE + SAMPLE-1)" % (sample_size + 1))
    lines.append("scan wall: %.2f s" % ref_result["wall_s"])
    lines.append("all_hits (incl. SAMPLE-1): %s"
                 % sorted(ref_result["all_hits"]))
    lines.append("leaked Bora.Chr17.*: %s"
                 % (sorted(ref_result["leaked"])
                    if ref_result["leaked"] else "{}"))
    lines.append("verdict: %s" % ("PASS" if ref_result["hit"] else "FAIL"))
    lines.append("")

    lines.append("[step 6: materialize first 5 mutant bins to chr17_samples/]")
    for m in materialize_results:
        lines.append("  %s -> %s  (%s, %.2f s)"
                     % (m["variant"],
                        os.path.relpath(m["path"], ROOT),
                        _fmt_bytes(m["bytes"]), m["wall_s"]))
    lines.append("")

    lines.append("[summary]")
    all_pos_ok = (passed == sample_size)
    neg_ok = ref_result["hit"]
    lines.append("per-variant positive:    %s  (%d/%d)"
                 % ("PASS" if all_pos_ok else "FAIL",
                    passed, sample_size))
    lines.append("ref-bin negative:        %s"
                 % ("PASS" if neg_ok else "FAIL"))
    lines.append("")

    if per_variant_results:
        mean_pv = sum(r["wall_s"] for r in per_variant_results) \
            / len(per_variant_results)
        lines.append("[extrapolation to SAMPLE_SIZE=100]")
        floor_keys = ("gen_ldb", "pack_ref", "stage_prep",
                      "ref_scan", "log_write")
        floor = sum(timings.get(k, 0.0) for k in floor_keys)
        est_pv_100 = mean_pv * 100
        # materialize: an extra (5 - SAMPLE_SIZE) if SAMPLE_SIZE < 5 else 0
        mat_extra = max(0, 5 - sample_size)
        if materialize_results:
            mat_mean = (sum(m["wall_s"] for m in materialize_results)
                        / len(materialize_results))
        else:
            mat_mean = mean_pv
        est_mat_100 = mat_mean * max(0, 5 - 100)  # 0 (always)
        est_total_100 = floor + est_pv_100 + est_mat_100
        lines.append("mean per-variant test:  %.2f s" % mean_pv)
        lines.append("fixed floor (other):    %.2f s" % floor)
        lines.append("est. 100 per-variant:   %.1f s" % est_pv_100)
        lines.append("est. TOTAL @ 100:       %.1f s (%.2f min)"
                     % (est_total_100, est_total_100 / 60.0))

    with open(log_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return log_path


# --- main ------------------------------------------------------------------
SAMPLE_SIZE = 1000  # bump here to scale the test loop


def main():
    # chdir to project root (matches gen_reef_regex's convention so its
    # relative paths resolve correctly).
    os.chdir(ROOT)

    print("[main] SAMPLE_SIZE=%d" % SAMPLE_SIZE)
    timings = {}

    # External tools.
    gen_reef_regex.setup()
    verify_tool_existence("clamscan")

    # Step 1 -- regenerate chr17variants.ldb.
    t = time.time()
    ldb_stats = gen_chr17variants_ldb()
    timings["gen_ldb"] = time.time() - t
    print("[step1] ldb sigs=%d skipped=%d  wall=%.2fs"
          % (ldb_stats[0], ldb_stats[1], timings["gen_ldb"]))

    # Step 2 -- pack reference into .bin.
    t = time.time()
    with open(REEF_TXT, "rb") as f:
        ref_seq = f.read()
    write_bin(ref_seq, REF_BIN)
    ref_bin_size = os.path.getsize(REF_BIN)
    timings["pack_ref"] = time.time() - t
    print("[step2] ref bin size=%d  wall=%.2fs"
          % (ref_bin_size, timings["pack_ref"]))

    # Step 3 -- sample + stage subset .ldb.
    t = time.time()
    extras = max(0, 5 - SAMPLE_SIZE)
    sample, materialize_extras = sample_with_extras(SAMPLE_SIZE, extras)
    stage_ldb = prepare_stage(sample)
    timings["stage_prep"] = time.time() - t
    print("[step3] sample=%s extras=%s ldb=%s  wall=%.2fs"
          % (sample, materialize_extras, stage_ldb, timings["stage_prep"]))

    # Step 4 -- per-variant clamscan tests (also materialize sample[:5]).
    t = time.time()
    per_variant_results = []
    materialize_results = []
    for idx in range(SAMPLE_SIZE):
        # If this variant will be materialized too (idx < 5), persist a copy.
        persist = None
        if idx < 5:
            persist = os.path.join(CHR17_DIR,
                                   "NC_000017.11.reef.%s.bin" % sample[idx])
        r = test_one_variant(sample, idx, stage_ldb, STAGE_DIR,
                             persist_path=persist)
        per_variant_results.append(r)
        print("[step4 %d/%d] %s hit=%s wall=%.2fs"
              % (idx + 1, SAMPLE_SIZE, r["variant"],
                 "YES" if r["hit"] else "NO", r["wall_s"]))
        if persist is not None:
            materialize_results.append({
                "variant": r["variant"],
                "path": persist,
                "bytes": r["bytes"],
                "wall_s": r["t_apply"] + r["t_pack"] + r["t_write"],
            })
    timings["per_variant_tests"] = time.time() - t

    # Step 5 -- ref-bin negative clamscan.
    t = time.time()
    ref_result = test_ref_free_of_sample(sample)
    timings["ref_scan"] = time.time() - t
    print("[step5] ref scan hits=%s leaked=%s verdict=%s wall=%.2fs"
          % (sorted(ref_result["all_hits"]),
             sorted(ref_result["leaked"]),
             "PASS" if ref_result["hit"] else "FAIL",
             timings["ref_scan"]))
    if not ref_result["hit"]:
        raise RuntimeError("ref-bin negative test FAILED: leaked %s"
                           % ref_result["leaked"])

    # Step 6 -- materialize remaining variants (if SAMPLE_SIZE < 5).
    t = time.time()
    for v in materialize_extras:
        dst = os.path.join(CHR17_DIR,
                           "NC_000017.11.reef.%s.bin" % v)
        nb, ta, tp, tw = gen_mutant_bin(v, dst)
        materialize_results.append({
            "variant": v, "path": dst, "bytes": nb,
            "wall_s": ta + tp + tw,
        })
        print("[step6 extra] %s -> %s (%.1fMB) wall=%.2fs"
              % (v, os.path.relpath(dst, ROOT), nb / (1 << 20),
                 ta + tp + tw))
    timings["materialize_extras"] = time.time() - t

    # Step 7 -- log.
    t = time.time()
    write_log(timings, ldb_stats, ref_bin_size,
              sample, per_variant_results, ref_result,
              materialize_results, SAMPLE_SIZE)
    timings["log_write"] = time.time() - t
    print("[step7] log -> %s wall=%.2fs"
          % (LOG_PATH, timings["log_write"]))

    # Final summary line for the user.
    total = sum(timings.values())
    print("[done] total wall = %.1f s (%.2f min)" % (total, total / 60.0))


if __name__ == "__main__":
    main()
