# -------------------------------------------
# Creator: BORA Author
# Date: 06/04/2026
# Purpose: shared provenance helpers for the ms_dlp retrieval scripts.
#          Reports the running-machine config, the run date, and the exact
#          command that produced a report, so every generated log/record is
#          self-documenting and replayable.
#
# NOTE: gen_machine_config() is adapted from chr17_variants/scripts/eval_reef.py
#   (same key: value format) minus the eval-specific document line.
# NOTE: code partly generated by Claude Code. Audited by author.
# -------------------------------------------

import os
import sys
import shlex
import platform
import datetime
from pathlib import Path


# --- project path resolvers -------------------------------------------------
# Resolve every project path from the location of THIS file, never from the cwd
# or a hardcoded absolute path. common.py lives at
#   <bora>/data/src_sig/ms_dlp/scripts/common.py
# so the bora project root is parents[4]:
#   [0]=scripts [1]=ms_dlp [2]=src_sig [3]=data [4]=bora
def get_proj_root():
    """Absolute path of the bora project root (holds data/)."""
    return Path(__file__).resolve().parents[4]


def get_ms_dlp_dir():
    """Absolute path of the ms_dlp directory (parent of scripts/)."""
    return Path(__file__).resolve().parents[1]


def get_samples_dir():
    """Absolute path of data/samples/ (the document corpora live here)."""
    return get_proj_root() / "data" / "samples"


def get_docs_dir():
    """Absolute path of ms_dlp/docs/ (generated logs/reports)."""
    return get_ms_dlp_dir() / "docs"


# generate a string (multi-line key: val format) describing the running
# machine: os, cores, cpu model/speed, RAM. Linux /proc based; fields that
# cannot be read fall back to "unknown" rather than aborting.
def gen_machine_config():
    lines = []
    uname = platform.uname()
    lines.append("os:              %s %s" % (uname.system, uname.release))
    lines.append("logical_cores:   %s" % (os.cpu_count() or "unknown"))

    # CPU model + max MHz from /proc/cpuinfo (Linux).
    model, mhz, physical = "unknown", "unknown", 0
    try:
        with open("/proc/cpuinfo") as f:
            for ln in f:
                if ln.startswith("model name") and model == "unknown":
                    model = ln.split(":", 1)[1].strip()
                elif ln.startswith("cpu MHz") and mhz == "unknown":
                    mhz = ln.split(":", 1)[1].strip()
                elif ln.startswith("processor"):
                    physical += 1
    except OSError:
        pass
    lines.append("cpu_model:       %s" % model)
    lines.append("cpu_mhz:         %s" % mhz)
    lines.append("cpu_count_proc:  %d" % physical)

    # Total RAM from /proc/meminfo (Linux).
    mem = "unknown"
    try:
        with open("/proc/meminfo") as f:
            for ln in f:
                if ln.startswith("MemTotal"):
                    kb = int(ln.split()[1])
                    mem = "%.1f GiB" % (kb / (1024.0 * 1024.0))
                    break
    except OSError:
        pass
    lines.append("ram_total:       %s" % mem)
    return "\n".join(lines)


# the exact command that produced the report (interpreter + argv), shell-quoted
# so it can be pasted back to reproduce the run.
def gen_run_command():
    return shlex.join([sys.executable] + sys.argv)


# today's date, ISO 8601.
def gen_run_date():
    return datetime.date.today().isoformat()


# header block for a generated report/log: title, date, the reproducing
# command, then the machine config. `title` names the report; the rest is
# filled in automatically.
def gen_report_header(title):
    lines = []
    lines.append("# %s" % title)
    lines.append("date:    %s" % gen_run_date())
    lines.append("command: %s" % gen_run_command())
    lines.append("")
    lines.append("[machine config]")
    lines.append(gen_machine_config())
    return "\n".join(lines)
