# -------------------------------------------
# Creator: BORA Author
# Date: 06/05/2026
# Purpose: retrieve the Zombie source (NSDI'24) from GitHub into ms_dlp/zombie/
#          so we can study its regexp + proximity pipeline (cf. zombie paper
#          sec 4.7). Full clone, .git retained, so the exact commit is pinned
#          and the snapshot is re-fetchable.
#
#          If zombie/ already exists it is wiped and re-cloned. A self-
#          documenting zombie/UPSTREAM.txt travels with the clone, and a
#          provenance log is written to docs/download_zombie.log.
#
# LICENSE NOTE: the upstream repo states NO license (all rights reserved). The
#   clone is for local research/benchmarking only and must NOT be redistributed;
#   zombie/ is git-ignored in this tree on purpose.
#
# NOTE: code partly generated by Claude Code. Audited by author.
# -------------------------------------------

import os
import sys
import shutil
import tempfile
import subprocess

# common.py lives beside this script (scripts/); import provenance helpers.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import gen_report_header, gen_run_date, get_ms_dlp_dir  # noqa: E402

# --- configuration ---------------------------------------------------------
ZOMBIE_URL = "https://github.com/PepperSieve/Zombie"
DEST = "zombie"                                 # clone target, under ms_dlp/
DOCS_DIR = "docs"
LOG_FILE = os.path.join(DOCS_DIR, "download_zombie.log")
CLONE_TIMEOUT = 300                             # seconds; abort a stalled clone
BUILD_TIMEOUT = 1800                            # seconds; first CirC build is slow
LICENSE_NOTE = ("NONE (all rights reserved) -- local research use only, "
                "do not redistribute")

# Full-repo build dependencies. Each entry: (label, kind, probe, hint,
# needed_for). kind drives how we test for it (see check_one). This is a
# REPORT-ONLY check -- nothing is installed; missing items just get a hint.
RUST_NIGHTLY = "nightly-2023-02-01"             # pinned in circ/rust-toolchain.toml
DEPS = [
    ("git",            "bin", "git",     "apt install git",
     "clone the repo"),
    ("g++",            "bin", "g++",     "apt install build-essential",
     "build regex/TestRegex and CirC native bits"),
    ("make",           "bin", "make",    "apt install build-essential",
     "build regex/TestRegex"),
    ("gmpxx.h (GMP)",  "hdr", "gmpxx.h", "apt install libgmp-dev",
     "TestRegex links -lgmpxx -lgmp"),
    ("mpfr.h (MPFR)",  "hdr", "mpfr.h",  "apt install libmpfr-dev",
     "CirC gmp-mpfr-sys system-libs build (avoids bundled MPFR make-check fail)"),
    ("mpc.h (MPC)",    "hdr", "mpc.h",   "apt install libmpc-dev",
     "CirC gmp-mpfr-sys system-libs build (avoids bundled MPFR make-check fail)"),
    ("cargo",          "bin", "cargo",   "install rustup (https://rustup.rs)",
     "build circ / middlebox"),
    ("rustc",          "bin", "rustc",   "install rustup (https://rustup.rs)",
     "build circ / middlebox"),
    ("rust " + RUST_NIGHTLY, "rustn", None,
     "rustup toolchain install " + RUST_NIGHTLY,
     "circ pins this nightly in rust-toolchain.toml"),
    ("cvc4",           "bin", "cvc4",    "apt install cvc4",
     "CirC SMT backend"),
    ("cbc (coinor)",   "bin", "cbc",     "apt install coinor-cbc coinor-libcbc-dev",
     "CirC ILP backend"),
    ("python3",        "bin", "python3", "apt install python3",
     "circ driver.py"),
    ("tqdm==4.63.0",   "py",  "tqdm",    "pip install tqdm==4.63.0",
     "circ driver.py"),
]


# --- helpers ---------------------------------------------------------------
# total file count and byte size of a directory tree (stdlib; no `du`).
def tree_size(root):
    nfiles, nbytes = 0, 0
    for dirpath, _dirs, names in os.walk(root):
        for name in names:
            try:
                nbytes += os.path.getsize(os.path.join(dirpath, name))
                nfiles += 1
            except OSError:
                pass
    return nfiles, nbytes


# run a command, returning (rc, stdout, stderr); rc=-1 if git is absent,
# rc=-2 on timeout. Never raises.
def run(cmd, timeout=None):
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return p.returncode, p.stdout.strip(), p.stderr.strip()
    except FileNotFoundError:
        return -1, "", "`git` not found on PATH"
    except subprocess.TimeoutExpired:
        return -2, "", "clone timed out after %ds" % timeout


# probe for a C/C++ header via a no-output g++ syntax check (no temp file).
def have_header(header):
    if shutil.which("g++") is None:
        return False, "g++ absent"
    src = "#include <%s>\nint main(){ return 0; }\n" % header
    try:
        p = subprocess.run(["g++", "-x", "c++", "-fsyntax-only", "-"],
                           input=src, capture_output=True, text=True, timeout=30)
        return (p.returncode == 0,
                "ok" if p.returncode == 0 else "%s not found" % header)
    except (OSError, subprocess.TimeoutExpired) as e:
        return False, str(e)


# is the pinned rust nightly installed (via rustup)?
def have_rust_nightly():
    if shutil.which("rustup") is None:
        return False, "rustup absent"
    rc, out, _err = run(["rustup", "toolchain", "list"])
    if rc != 0:
        return False, "rustup query failed"
    return (RUST_NIGHTLY in out,
            "installed" if RUST_NIGHTLY in out else "toolchain missing")


# test one dependency; returns (ok, detail).
def check_one(kind, probe):
    if kind == "bin":
        path = shutil.which(probe)
        return (path is not None, path or "not on PATH")
    if kind == "py":
        rc, _o, _e = run(["python3", "-c", "import %s" % probe])
        return (rc == 0, "import ok" if rc == 0 else "import failed")
    if kind == "hdr":
        return have_header(probe)
    if kind == "rustn":
        return have_rust_nightly()
    return False, "unknown probe"


# run the whole dependency table; returns list of dicts.
def check_dependencies():
    results = []
    for label, kind, probe, hint, need in DEPS:
        ok, detail = check_one(kind, probe)
        results.append({"label": label, "ok": ok, "detail": detail,
                        "hint": hint, "need": need})
    return results


# build a consolidated, copy-pasteable list of commands that installs every
# MISSING dependency: all `apt install` hints are merged into one line; other
# hints (rustup, pip, ...) are emitted as their own deduplicated lines.
def install_commands(deps):
    apt_pkgs, other = [], []
    for d in deps:
        if d["ok"]:
            continue
        hint = d["hint"]
        if hint.startswith("apt install "):
            for pkg in hint[len("apt install "):].split():
                if pkg not in apt_pkgs:
                    apt_pkgs.append(pkg)
        elif hint not in other:
            other.append(hint)
    cmds = []
    if apt_pkgs:
        cmds.append("sudo apt install -y " + " ".join(apt_pkgs))
    cmds.extend(other)
    return cmds


def write_log(status, commit, nfiles, nbytes, error, deps, patches=None,
              builds=None):
    lines = [gen_report_header("zombie source retrieval"), ""]
    lines.append("repo:    %s" % ZOMBIE_URL)
    lines.append("dest:    %s/   (full clone, .git retained)" % DEST)
    lines.append("status:  %s" % status)
    lines.append("commit:  %s" % (commit or "n/a"))
    lines.append("license: %s" % LICENSE_NOTE)
    if status == "OK":
        lines.append("size:    %d files, %.1f MiB"
                     % (nfiles, nbytes / (1024.0 * 1024.0)))
    if error:
        lines.append("error:   %s" % error)

    if patches:
        lines.append("")
        lines.append("[patches]  (applied to make the clone build standalone)")
        for p in patches:
            lines.append("  %s" % p)

    if builds:
        n_ok = sum(1 for (_c, ok, _d) in builds if ok)
        lines.append("")
        lines.append("[build verification]  %d/%d components compiled"
                     % (n_ok, len(builds)))
        for comp, ok, detail in builds:
            lines.append("  [%s] %-44s %s"
                         % ("OK  " if ok else "FAIL", comp, detail))

    if deps:
        n_ok = sum(1 for d in deps if d["ok"])
        lines.append("")
        lines.append("[dependencies]  %d/%d present (report only, nothing installed)"
                     % (n_ok, len(deps)))
        for d in deps:
            mark = "OK  " if d["ok"] else "MISS"
            lines.append("  [%s] %-18s %s" % (mark, d["label"], d["detail"]))
            lines.append("         needed for: %s" % d["need"])
            if not d["ok"]:
                lines.append("         install:    %s" % d["hint"])

        cmds = install_commands(deps)
        if cmds:
            lines.append("")
            lines.append("  to install the missing dependencies, run:")
            for c in cmds:
                lines.append("    %s" % c)

    os.makedirs(DOCS_DIR, exist_ok=True)
    with open(LOG_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")


# --- post-clone patches ----------------------------------------------------
# Make the freshly-cloned Zombie tree build standalone in this environment.
# Every patch is idempotent and recorded in the log; the upstream clone is
# otherwise untouched. These were derived empirically while building the
# regexp -> ZoKrates -> CirC (R1CS) pipeline for the BORA experiments.
def apply_patches():
    applied = []

    # P1: provide the `../curve-constraint-tests` path-dependency that the
    # vendored circ/third_party/curve25519 expects; the actual crate lives in
    # the curves submodule, so we symlink it (relative link, stays portable).
    tp = os.path.join(DEST, "circ", "third_party")
    link = os.path.join(tp, "curve-constraint-tests")
    rel_target = os.path.join("curves", "curve-constraint-tests")
    if not os.path.isdir(tp):
        applied.append("P1 WARN: circ/third_party not found")
    elif os.path.lexists(link):
        applied.append("P1 curve-constraint-tests: already present (skip)")
    elif os.path.isdir(os.path.join(tp, rel_target)):
        os.symlink(rel_target, link)
        applied.append("P1 circ/third_party/curve-constraint-tests -> %s (symlink)"
                       % rel_target)
    else:
        applied.append("P1 WARN: %s missing; cannot link curve-constraint-tests"
                       % rel_target)

    # P2: drop the dangling `pub mod tmp;` in circ/src/witnesses/mod.rs. The
    # tmp.rs file matches circ's own .gitignore ("tmp*") so it was never
    # committed; a clean clone can't resolve the module. It is unused
    # everywhere, so we comment the declaration out.
    wmod = os.path.join(DEST, "circ", "src", "witnesses", "mod.rs")
    if os.path.isfile(wmod):
        with open(wmod) as f:
            txt = f.read()
        if "pub mod tmp;" in txt:
            txt = txt.replace(
                "pub mod tmp;",
                "// pub mod tmp;  // download_zombie.py: gitignored, "
                "uncommitted, unused")
            with open(wmod, "w") as f:
                f.write(txt)
            applied.append("P2 circ/src/witnesses/mod.rs: commented dangling "
                           "`pub mod tmp;`")
        else:
            applied.append("P2 witnesses/mod.rs: no `pub mod tmp;` (skip)")
    else:
        applied.append("P2 WARN: circ/src/witnesses/mod.rs not found")

    # P3: the package is `circ` but the fork overrode [lib] to name
    # "circ_zkmb"; every example (circ.rs, run_zok.rs) does `use circ::`, so
    # they cannot resolve the lib. Internal code uses `crate::`, so renaming the
    # lib target back to "circ" fixes the examples without affecting anything
    # else. (The cdylib is only consumed by the middlebox/TLS side we don't use.)
    cargo = os.path.join(DEST, "circ", "Cargo.toml")
    if os.path.isfile(cargo):
        with open(cargo) as f:
            txt = f.read()
        if 'name = "circ_zkmb"' in txt:
            txt = txt.replace('name = "circ_zkmb"', 'name = "circ"')
            with open(cargo, "w") as f:
                f.write(txt)
            applied.append('P3 circ/Cargo.toml: [lib] name "circ_zkmb" -> "circ"')
        else:
            applied.append("P3 circ/Cargo.toml: lib already named circ (skip)")
    else:
        applied.append("P3 WARN: circ/Cargo.toml not found")

    # P4: fix the stale Spartan NIZK::prove / verify call sites in
    # circ/examples/run_zok.rs. Upstream still calls an older batched API
    #   NIZK::prove(&inst, &vec![vars], &vec![input], &gens, &mut tr)
    # but the vendored Spartan submodule's NIZK (third_party/Spartan, src/lib.rs)
    # takes the vars assignment BY VALUE and the input BY REFERENCE:
    #   NIZK::prove(&inst, vars, &input, &gens, &mut tr)
    #   proof.verify(&inst, &input, &mut tr, &gens)
    # Without this the run_zok example does not compile (the `circ` example,
    # which verify_build compiles, is unaffected and already builds). We rewrite
    # only ACTIVE lines -- any line whose first non-space char is `//` is a
    # comment and is left untouched, since run_zok.rs keeps several commented
    # variants (including an already-correct one) we must not disturb.
    rzok = os.path.join(DEST, "circ", "examples", "run_zok.rs")
    spartan_subs = [
        ("&vec![var_assignment]", "var_assignment"),                # vars by value
        ("&vec![input_assignment.clone()]", "&input_assignment"),   # input by ref
        ("&vars_list", "var_assignment.clone()"),                   # batch -> single
        ("&inputs_list", "&input_assignment"),                      # batch -> single
    ]
    if os.path.isfile(rzok):
        with open(rzok) as f:
            src_lines = f.readlines()
        out_lines, nfixed = [], 0
        for ln in src_lines:
            if ln.lstrip().startswith("//"):       # never touch comments
                out_lines.append(ln)
                continue
            new = ln
            for old, rep in spartan_subs:
                new = new.replace(old, rep)
            if new != ln:
                nfixed += 1
            out_lines.append(new)
        if nfixed:
            with open(rzok, "w") as f:
                f.writelines(out_lines)
            applied.append("P4 circ/examples/run_zok.rs: rewrote %d line(s) to the "
                           "single-assignment Spartan NIZK prove/verify API" % nfixed)
        else:
            applied.append("P4 run_zok.rs: Spartan NIZK calls already current (skip)")
    else:
        applied.append("P4 WARN: circ/examples/run_zok.rs not found")

    # NOTE (no file patch): circ/ must NOT be built in place if it sits inside
    # an enclosing Cargo workspace -- adding a local [workspace] re-resolves the
    # lockfile and pulls MSRV-incompatible crates (syn/quote needing rustc 1.71
    # vs the pinned 1.69 nightly). The verified recipe builds a COPY of circ/
    # outside any workspace with the committed Cargo.lock and `--locked`
    # (see build_circ / verify_build).
    applied.append("note: build circ OUT of any parent Cargo workspace "
                   "(--locked, committed lock); see verify_build")

    return applied


# run a command in a given directory with optional extra env; never raises.
def run_in(cmd, cwd, timeout=None, extra_env=None):
    env = dict(os.environ)
    if extra_env:
        env.update(extra_env)
    try:
        p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True,
                           timeout=timeout, env=env)
        return p.returncode, p.stdout, p.stderr
    except FileNotFoundError as e:
        return -1, "", str(e)
    except subprocess.TimeoutExpired:
        return -2, "", "timed out after %ds" % timeout


# Verify the cloned Zombie actually COMPILES (regexp pipeline). Returns a list
# of (component, ok, detail). This is the verified build recipe derived for the
# BORA experiments:
#   - regex/TestRegex: plain `make` in place (no workspace issue).
#   - circ (zokrates -> R1CS): build a COPY of circ/ in a temp dir OUTSIDE any
#     enclosing Cargo workspace, with the committed Cargo.lock and `--locked`
#     (so the MSRV-incompatible re-resolution never happens) and system
#     GMP/MPFR/MPC via CARGO_FEATURE_USE_SYSTEM_LIBS=1 (so gmp-mpfr-sys links
#     the system libs instead of building+`make check`-ing a bundled MPFR,
#     which fails its tsprintf test on modern glibc).
# The temp build dir is removed afterwards; this confirms compilation, it does
# not leave an in-tree circ binary (the parent workspace prevents that).
def verify_build():
    results = []
    abs_dest = os.path.abspath(DEST)

    # 1. regex/TestRegex via make (in place).
    regex_dir = os.path.join(abs_dest, "regex")
    if os.path.isdir(regex_dir):
        rc, _o, err = run_in(["make"], regex_dir, BUILD_TIMEOUT)
        ok = rc == 0 and os.path.isfile(os.path.join(regex_dir, "bin", "TestRegex"))
        results.append(("regex/TestRegex (make)", ok,
                        "built bin/TestRegex" if ok
                        else "FAILED: %s" % (err.strip()[-200:] or "rc=%d" % rc)))
    else:
        results.append(("regex/TestRegex (make)", False, "regex/ not found"))

    # 2. circ example via cargo, in a temp copy outside any workspace.
    circ_src = os.path.join(abs_dest, "circ")
    if not os.path.isdir(circ_src):
        results.append(("circ (cargo)", False, "circ/ not found"))
        return results
    tmp = tempfile.mkdtemp(prefix="zombie_circ_build_")
    try:
        circ_build = os.path.join(tmp, "circ")

        # Ignore ONLY the top-level cargo build dir and .git -- anchored to the
        # circ root, so we do NOT also drop the source module circ/src/target/
        # (an unanchored "target" pattern would, breaking the build).
        def _root_ignore(dirpath, names):
            if os.path.abspath(dirpath) == os.path.abspath(circ_src):
                return {n for n in names if n in ("target", ".git")}
            return set()

        shutil.copytree(circ_src, circ_build, symlinks=True, ignore=_root_ignore)
        rc, _o, err = run_in(
            ["cargo", "build", "--release", "--example", "circ", "--locked"],
            circ_build, BUILD_TIMEOUT,
            extra_env={"CARGO_FEATURE_USE_SYSTEM_LIBS": "1"})
        circ_bin = os.path.join(circ_build, "target", "release", "examples", "circ")
        ok = rc == 0 and os.path.isfile(circ_bin)
        results.append(("circ (cargo, out-of-workspace --locked, system-libs)", ok,
                        "compiled circ example" if ok
                        else "FAILED: %s" % (err.strip()[-300:] or "rc=%d" % rc)))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return results


def write_upstream(commit):
    lines = [
        "repo:      %s" % ZOMBIE_URL,
        "commit:    %s" % commit,
        "retrieved: %s" % gen_run_date(),
        "license:   %s" % LICENSE_NOTE,
    ]
    with open(os.path.join(DEST, "UPSTREAM.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")


# -------------------------------------------
# MAIN
# -------------------------------------------
def main():
    # --verify-build: also compile the regexp -> R1CS pipeline and confirm it
    # builds (slow: first CirC build takes minutes). Default off (clone + patch
    # + dependency report only).
    do_build = "--verify-build" in sys.argv or "--build" in sys.argv

    # resolve all relative paths against the ms_dlp dir (never cwd / hardcoded).
    os.chdir(get_ms_dlp_dir())

    # wipe any prior clone so we always get a clean snapshot.
    if os.path.exists(DEST):
        print("[wipe] removing existing %s/" % DEST)
        shutil.rmtree(DEST)

    # full clone (no --depth); keep .git so the commit is pinned and re-fetchable.
    print("[clone] %s -> %s/" % (ZOMBIE_URL, DEST))
    rc, _out, err = run(["git", "clone", ZOMBIE_URL, DEST], timeout=CLONE_TIMEOUT)
    if rc != 0:
        # leave no partial tree behind on failure.
        if os.path.exists(DEST):
            shutil.rmtree(DEST)
        write_log("FAIL", "", 0, 0, err, None)
        print("[fail] %s" % err)
        print("[log]  %s" % LOG_FILE)
        raise SystemExit(1)

    # pin the commit.
    rc, commit, err = run(["git", "-C", DEST, "rev-parse", "HEAD"])
    if rc != 0:
        commit = ""

    write_upstream(commit)

    # apply standalone-build patches to the fresh clone.
    print("[patch] applying build patches to the clone...")
    patches = apply_patches()
    for p in patches:
        print("  %s" % p)

    nfiles, nbytes = tree_size(DEST)

    # report (do not install) the full-repo build dependencies.
    print("[deps] checking build dependencies (report only)...")
    deps = check_dependencies()
    for d in deps:
        print("  [%s] %-18s %s" % ("OK  " if d["ok"] else "MISS",
                                   d["label"], d["detail"]))

    # optionally verify the clone actually compiles.
    builds = None
    if do_build:
        print("[build] verifying compilation (this can take several minutes)...")
        builds = verify_build()
        for comp, ok, detail in builds:
            print("  [%s] %s -- %s" % ("OK  " if ok else "FAIL", comp, detail))
    else:
        print("[build] skipped (pass --verify-build to compile and verify)")

    write_log("OK", commit, nfiles, nbytes, "", deps, patches, builds)

    n_ok = sum(1 for d in deps if d["ok"])
    print("[ok]   commit %s" % (commit or "unknown"))
    print("[ok]   %d files, %.1f MiB" % (nfiles, nbytes / (1024.0 * 1024.0)))
    print("[deps] %d/%d present" % (n_ok, len(deps)))
    cmds = install_commands(deps)
    if cmds:
        print("[deps] to install the %d missing dependencies, run:" % (len(deps) - n_ok))
        for c in cmds:
            print("         %s" % c)
    if builds is not None:
        b_ok = sum(1 for (_c, ok, _d) in builds if ok)
        print("[build] %d/%d components compiled" % (b_ok, len(builds)))
    print("[log]  %s" % LOG_FILE)

    # final completeness check: when a build was requested, fail loudly (and
    # with a non-zero exit) unless every Zombie component compiled.
    if builds is not None:
        failed = [comp for (comp, ok, _d) in builds if not ok]
        if failed:
            print("[done] Zombie build INCOMPLETE -- did not compile: %s"
                  % ", ".join(failed))
            raise SystemExit(2)
        print("[done] Zombie build COMPLETE: all %d components compiled." % len(builds))


if __name__ == "__main__":
    main()
