# -------------------------------------------
# SUPERSEDED -- use measure_v2.py instead.  This script's cost model is
# known to be wrong (it under-measured the corpus worst case by ~16x); the
# header of measure_v2.py explains the three specific errors.  Kept only so
# the earlier numbers remain reproducible.  Nothing in the pipeline runs it.
# -------------------------------------------
# Creator: BORA Author
# Date: 06/04/2026
# Purpose: measure how densely the in-force MS-DLP policy keywords occur in the
#          CLEAN (unflagged) Enron emails -- the documents eval_dlp.py found match
#          NO regex_zombie policy.
#
#          Step 1: parse every regex_zombie/<slug>.regex, pull the keyword
#                  alternatives out of its KWS group (post gen_zombie_regex
#                  filtering: whitespace-delimiting, short-keyword drop,
#                  connection-string rewrite), de-duplicate into one vocabulary.
#          Step 2: in parallel, scan each CLEAN email (docs/clean_email_list.txt)
#                  and, for every keyword, count how many times it occurs; from
#                  that derive, per file, the number of DISTINCT keywords present
#                  and the TOTAL keyword occurrences.
#          Step 3: summarize over the corpus -- file count, vocabulary size,
#                  distinct-keywords-per-file (avg/min/max),
#                  total-occurrences-per-file (avg/min/max), and
#                  max_occ_per_chunk: split each file into chunk_size-byte chunks
#                  (a main() parameter, default 64 KB), sum keyword occurrences
#                  per chunk, take the file's MAX -- then summarize that across
#                  files (avg/min/max).
#
# WHY max_occ_per_chunk MATTERS:
#   BORA proves regex non-membership chunk by chunk (one folding step per
#   chunk_size-byte window). Within a chunk the circuit does NOT pay for the raw
#   byte length -- it pays for each KEYWORD occurrence, because every keyword hit
#   anchors one proximity-window obligation (prove no PAT lies within .{0,N} of
#   it). So a chunk's per-step proving cost scales with its keyword-occurrence
#   count, not its size, and the file's max_occ_per_chunk is its heaviest single
#   folding step -- the one that sets peak witness/constraint count and memory.
#   The corpus-wide max over clean docs therefore bounds the worst single step
#   BORA must absorb on legitimately-passing mail; a long tail here (not the
#   average) is what drives the §7.6 cost. We measure it on the CLEAN subset
#   precisely because those are the documents that must still be proven
#   non-matching -- their density, not the flagged docs', is the cost we pay.
#
# MATCH SEMANTICS (documented so the numbers are reproducible):
#   - case-insensitive;
#   - a match may not be flanked by an alphanumeric char (so "aba" is NOT
#     counted inside "database"; punctuated keywords like "aba#" still match);
#   - internal whitespace in a keyword matches any whitespace run (\s+);
#   - matches are NON-OVERLAPPING, longest-keyword-first: a span is counted once,
#     as the longest keyword that matches it (so "routing number" is one hit, not
#     also a separate "routing").
#
# NOTE: code partly generated by Claude Code. Audited by author.
# -------------------------------------------

import os
import re
import sys
import collections
from concurrent.futures import ProcessPoolExecutor

# common.py / run_zombie.py live beside this script (scripts/).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import (gen_report_header, get_ms_dlp_dir,  # noqa: E402
                    get_samples_dir)
import run_zombie as rz               # noqa: E402  (extract_parts for KWS parsing)

# --- configuration ---------------------------------------------------------
DOCS_DIR = "docs"
# The measurement MATRIX: every (DATASET corpus) x (RULESET regex folder), matching
# eval_dlp.py. Edit these two arrays to add corpora or rule sets -- the main loop
# scales automatically. For each combination, vocab comes from the ruleset folder
# and the scan is restricted to that combination's CLEAN (unflagged) subset, i.e.
# docs/clean_email_list_<dataset>_<ruleset>.txt (produced by eval_dlp.py, which
# MUST run first). Output: docs/measure_report_<dataset>_<ruleset>.txt.
DATASETS = [
    ("email_merged128k", get_samples_dir() / "email_merged128k"),
    ("email",            get_samples_dir() / "email"),
]
RULESETS = ["regex_zombie", "regex_zombie_international"]

N_WORKERS = os.cpu_count() or 8
CHUNKSIZE = 16                          # files per task dispatched to a worker

_WS = re.compile(r"\s+")


# whitespace-delimiter class that gen_zombie_regex.sit_to_regex wraps around each
# keyword (connection-string SITs are NOT wrapped).
WS_CLASS = r"[\x20\x09\x0A\x0D]"


def _decode_esc(s):
    """Decode \\xHH escapes in a regex literal back to characters."""
    return re.sub(r"\\x([0-9A-Fa-f]{2})",
                  lambda m: chr(int(m.group(1), 16)), s)


def _strip_ws_wrap(alt):
    """Strip the optional whitespace-delimiter class wrapping a keyword."""
    if alt.startswith(WS_CLASS):
        alt = alt[len(WS_CLASS):]
    if alt.endswith(WS_CLASS):
        alt = alt[:-len(WS_CLASS)]
    return alt


# --- step 1: collect the keyword vocabulary from the baked policies ---------
# parse every regex_zombie/<slug>.regex into (PAT, KWS, prox) via run_zombie's
# extract_parts, take the keyword alternatives out of KWS (stripping the
# whitespace-delimiter wrappers and decoding \xHH escapes), normalize (lower +
# single-spaced) and de-duplicate into one vocabulary. This reflects the keywords
# ACTUALLY in force after gen_zombie_regex's filtering (short-keyword drop,
# connection-string rewrite) -- not the raw raw_data_records/ lists.
def collect_vocab(regex_dir):
    vocab = set()      # distinct keywords (deduped across all SITs)
    total = 0          # total keyword entries (a keyword shared by N SITs counts N)
    # ONE policy per SIT (all combos of an expanded SIT share the same KWS, so
    # iterating per-combo would count its keywords C times).
    for name in rz.list_sit_reps(regex_dir):
        full = open(os.path.join(regex_dir, name + ".regex"),
                    encoding="utf-8").read().strip()
        try:
            _pat, kws, _prox = rz.extract_parts(full)
        except Exception:
            continue                       # non-standard structure -> skip
        for alt in kws[1:-1].split("|"):   # strip outer parens, split alternatives
            kw = _WS.sub(" ", _decode_esc(_strip_ws_wrap(alt)).strip().lower())
            if kw:
                total += 1
                vocab.add(kw)
    return vocab, total


# read a clean_email_list_<...>.txt (paths relative to its dataset dir; '#' header
# lines ignored) -> sorted absolute paths that exist. These are the unflagged emails
# for one (dataset, ruleset) combination.
def read_clean_list(clean_list, samples_dir):
    if not os.path.isfile(clean_list):
        raise SystemExit("[corpus] %s not found; run eval_dlp.py first" % clean_list)
    files = []
    with open(clean_list, encoding="utf-8") as f:
        for ln in f:
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            p = os.path.join(samples_dir, ln)
            if os.path.isfile(p):
                files.append(p)
    return sorted(files)


# build one case-insensitive regex matching any vocabulary keyword. Alternatives
# are ordered longest-first so the engine prefers the longest keyword at a given
# position; internal spaces become \s+; matches may not be flanked by an
# alphanumeric char (word-boundary-ish, but tolerant of punctuated keywords).
def build_pattern(vocab):
    kws = sorted(vocab, key=len, reverse=True)
    alts = []
    for kw in kws:
        esc = r"\s+".join(re.escape(tok) for tok in kw.split(" ") if tok)
        if esc:
            alts.append(esc)
    body = "|".join(alts)
    return re.compile(r"(?<![0-9A-Za-z])(?:" + body + r")(?![0-9A-Za-z])",
                      re.IGNORECASE)


# --- step 2: per-file scan (runs in worker processes) ----------------------
# the compiled pattern is large; compile it ONCE per worker via the pool
# initializer and stash it in a module global, rather than pickling it per task.
_PATTERN = None
_CHUNK_SIZE = None      # file-split chunk size in characters (~bytes for ASCII)


def _init_worker(vocab_list, chunk_size):
    global _PATTERN, _CHUNK_SIZE
    _PATTERN = build_pattern(vocab_list)
    _CHUNK_SIZE = chunk_size


# scan one email file. Splits it into _CHUNK_SIZE-char chunks and, for each
# chunk, sums the keyword occurrences whose match STARTS in that chunk (so every
# occurrence is counted once, in exactly one chunk -- no boundary double-count).
# Returns (distinct_keywords_present, total_occurrences, max_occ_per_chunk,
# top_kw); max_occ_per_chunk = the largest per-chunk occurrence sum over the
# file's chunks, top_kw = the (keyword, count) breakdown of that densest chunk.
# Returns None if the file cannot be read.
def _scan_file(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return None
    counts = {}
    chunk_occ = {}            # chunk index -> total keyword occurrences starting in it
    chunk_kw = {}             # chunk index -> Counter(keyword -> occ)
    for m in _PATTERN.finditer(text):
        key = _WS.sub(" ", m.group(0).lower())
        counts[key] = counts.get(key, 0) + 1
        ci = m.start() // _CHUNK_SIZE
        chunk_occ[ci] = chunk_occ.get(ci, 0) + 1
        kc = chunk_kw.get(ci)
        if kc is None:
            kc = chunk_kw[ci] = collections.Counter()
        kc[key] += 1
    if chunk_occ:
        max_ci = max(chunk_occ, key=lambda c: chunk_occ[c])
        max_occ_per_chunk = chunk_occ[max_ci]
        top_kw = chunk_kw[max_ci].most_common(5)   # picklable list of (kw, count)
    else:
        max_occ_per_chunk = 0
        top_kw = []
    return len(counts), sum(counts.values()), max_occ_per_chunk, top_kw


# --- step 3: summary -------------------------------------------------------
# render the distribution of a per-file integer metric (used for
# max_occ_per_chunk): exact rows for values 0..max_exact, a bucketed tail above
# that, then median/p90/p99/max. Returns a list of report lines.
def format_distribution(values, max_exact=10):
    n = len(values)
    if not n:
        return ["  (no files)"]
    c = collections.Counter(values)
    out = ["  %5s  %8s  %8s  %10s" % ("value", "files", "share", "cum.share")]
    cum = 0
    for v in range(0, max_exact + 1):
        if v not in c:
            continue
        cum += c[v]
        out.append("  %5d  %8d  %7.1f%%  %9.1f%%"
                   % (v, c[v], 100.0 * c[v] / n, 100.0 * cum / n))
    tail = sorted(v for v in c if v > max_exact)
    if tail:
        tc = sum(c[v] for v in tail); cum += tc
        out.append("  %5s  %8d  %7.1f%%  %9.1f%%   (range %d..%d)"
                   % (">%d" % max_exact, tc, 100.0 * tc / n, 100.0 * cum / n,
                      tail[0], tail[-1]))
    s = sorted(values)
    def pct(p):
        return s[min(n - 1, int(p * n))]
    out.append("")
    out.append("  median=%d  p90=%d  p99=%d  max=%d   (0 occ: %d files, %.1f%%)"
               % (pct(0.50), pct(0.90), pct(0.99), s[-1], c[0],
                  100.0 * c[0] / n))
    return out


# list the N "worst" files: those with the largest max_occ_per_chunk (densest
# chunk drives BORA's per-chunk proving cost). Ties broken by total occurrences.
# All candidates are clean (unflagged) by construction -- read_clean_list() is the
# only corpus source. Shows the keywords dominating each file's densest chunk.
def format_worst(maxocc, total, distinct, topkws, files, n=10):
    order = sorted(range(len(maxocc)),
                   key=lambda i: (maxocc[i], total[i]), reverse=True)[:n]
    # first the ranked table ...
    out = ["  %4s  %8s  %7s  %8s  %s"
           % ("rank", "max_occ", "total", "distinct", "file")]
    for r, i in enumerate(order, 1):
        out.append("  %4d  %8d  %7d  %8d  %s"
                   % (r, maxocc[i], total[i], distinct[i],
                      os.path.basename(files[i])))
    # ... then the densest-chunk keyword breakdown per file.
    out.append("")
    out.append("  densest-chunk keyword breakdown:")
    for r, i in enumerate(order, 1):
        kw = (", ".join("%s (%d)" % (k, c) for k, c in topkws[i])
              if topkws[i] else "(none)")
        out.append("  %4d  %s: %s" % (r, os.path.basename(files[i]), kw))
    return out


def _stats(values):
    """(avg, min, max) for a non-empty list; (0,0,0) if empty."""
    if not values:
        return 0.0, 0, 0
    return sum(values) / len(values), min(values), max(values)


def write_report(tag, ruleset_dir, dataset_dir, clean_list, report_file,
                 n_files, vocab_size, vocab_total, distinct, total, maxocc,
                 topkws, chunk_size, files):
    # argmin/argmax (by total occurrences) for a little context in the report.
    lo_i = min(range(len(total)), key=lambda i: total[i]) if total else None
    hi_i = max(range(len(total)), key=lambda i: total[i]) if total else None
    d_avg, d_min, d_max = _stats(distinct)
    t_avg, t_min, t_max = _stats(total)
    mo_avg, mo_min, mo_max = _stats(maxocc)
    # the single file with the largest max_occ_per_chunk (the densest 64KB window).
    mo_hi_i = max(range(len(maxocc)), key=lambda i: maxocc[i]) if maxocc else None

    lines = []
    lines.append(gen_report_header("ms_dlp keyword-density measurement"))
    lines.append("")
    lines.append("keywords:    parsed from %s/ KWS groups (post-filter)" % ruleset_dir)
    lines.append("dataset:     %s" % dataset_dir)
    lines.append("corpus:      clean (unflagged) subset -- %s" % clean_list)
    lines.append("chunk_size:  %d bytes (%d KB)" % (chunk_size, chunk_size // 1024))
    lines.append("")
    lines.append("match: case-insensitive, non-alphanumeric-flanked, "
                 "non-overlapping longest-first")
    lines.append("")
    lines.append("== SUMMARY ==")
    lines.append("(1) files scanned:                       %d" % n_files)
    lines.append("(2) keywords collected   total/distinct: %d / %d"
                 % (vocab_total, vocab_size))
    lines.append("(3) distinct keywords per file   avg/min/max: "
                 "%.2f / %d / %d" % (d_avg, d_min, d_max))
    lines.append("(4) total keyword occ. per file  avg/min/max: "
                 "%.2f / %d / %d" % (t_avg, t_min, t_max))
    lines.append("(5) max_occ_per_chunk (densest %dKB chunk, occ) avg/min/max: "
                 "%.2f / %d / %d" % (chunk_size // 1024, mo_avg, mo_min, mo_max))
    if hi_i is not None:
        lines.append("")
        lines.append("    busiest file: %s (%d occ, %d distinct)"
                     % (os.path.basename(files[hi_i]), total[hi_i],
                        distinct[hi_i]))
        lines.append("    emptiest file: %s (%d occ, %d distinct)"
                     % (os.path.basename(files[lo_i]), total[lo_i],
                        distinct[lo_i]))
        lines.append("    densest chunk: %s (max_occ_per_chunk=%d, %d total occ)"
                     % (os.path.basename(files[mo_hi_i]), maxocc[mo_hi_i],
                        total[mo_hi_i]))
    lines.append("")
    lines.append("== WHY max_occ_per_chunk MATTERS ==")
    lines.append("BORA proves regex non-membership chunk by chunk (one folding")
    lines.append("step per %dKB window). A chunk's circuit pays NOT for its byte"
                 % (chunk_size // 1024))
    lines.append("length but for each KEYWORD occurrence -- every hit anchors one")
    lines.append("proximity obligation (prove no pattern lies within .{0,N} of it).")
    lines.append("So max_occ_per_chunk is the file's heaviest single folding step,")
    lines.append("setting its peak witness/constraint count and memory. Measured on")
    lines.append("the CLEAN subset because those docs must still be proven non-")
    lines.append("matching -- their density, not the flagged docs', is the cost we pay.")
    lines.append("")
    lines.append("== max_occ_per_chunk DISTRIBUTION (%dKB chunks) =="
                 % (chunk_size // 1024))
    lines.extend(format_distribution(maxocc))
    lines.append("")
    lines.append("== 10 WORST FILES by max_occ_per_chunk (%dKB chunks) =="
                 % (chunk_size // 1024))
    lines.extend(format_worst(maxocc, total, distinct, topkws, files))
    report = "\n".join(lines)

    os.makedirs(DOCS_DIR, exist_ok=True)
    with open(report_file, "w") as f:
        f.write(report + "\n")
    return report


# -------------------------------------------
# MAIN
# -------------------------------------------
def measure_combo(tag, ds_name, ds_dir, rs_dir, chunk_size):
    """Measure one (dataset, ruleset) combination: vocab from rs_dir, scan that
    combination's clean subset under ds_dir, write measure_report_<tag>.txt.
    Returns a one-line summary dict (or None if skipped)."""
    if not os.path.isdir(rs_dir):
        print("[measure] ruleset %s/ absent -- skipping %s" % (rs_dir, tag)); return None
    clean_list = os.path.join(DOCS_DIR, "clean_email_list_%s.txt" % tag)
    report_file = os.path.join(DOCS_DIR, "measure_report_%s.txt" % tag)

    vocab, vocab_total = collect_vocab(rs_dir)
    vocab_list = sorted(vocab)
    print("[vocab] %s : %d keywords (%d distinct) from %s/"
          % (tag, vocab_total, len(vocab), rs_dir))
    if not vocab:
        print("[measure] no keywords in %s/ -- run gen_zombie_regex.py" % rs_dir); return None

    files = read_clean_list(clean_list, str(ds_dir))
    print("[corpus] %s : %d clean files from %s" % (tag, len(files), clean_list))
    if not files:
        print("[measure] no clean files in %s -- run eval_dlp.py first" % clean_list)
        return None

    distinct, total, maxocc, topkws, kept_files, done = [], [], [], [], [], 0
    with ProcessPoolExecutor(max_workers=N_WORKERS, initializer=_init_worker,
                             initargs=(vocab_list, chunk_size)) as ex:
        for path, res in zip(files, ex.map(_scan_file, files, chunksize=CHUNKSIZE)):
            done += 1
            if res is not None:
                d, t, mo, tk = res
                distinct.append(d); total.append(t); maxocc.append(mo)
                topkws.append(tk); kept_files.append(path)
            if done % 5000 == 0 or done == len(files):
                print("[scan] %s : %d/%d files" % (tag, done, len(files)))

    write_report(tag, rs_dir, ds_dir, clean_list, report_file, len(kept_files),
                 len(vocab), vocab_total, distinct, total, maxocc, topkws,
                 chunk_size, kept_files)
    mo_avg = sum(maxocc) / len(maxocc) if maxocc else 0
    print("[report] %s -> %s" % (tag, report_file))
    return {"tag": tag, "files": len(kept_files), "vocab": len(vocab),
            "vocab_total": vocab_total, "maxocc_avg": mo_avg,
            "maxocc_max": max(maxocc) if maxocc else 0}


def main():
    os.chdir(get_ms_dlp_dir())          # resolve relative paths (rulesets, docs)
    chunk_size = 64 * 1024              # 64 KB; file-split for max_occ_per_chunk

    summaries = []
    for ds_name, ds_dir in DATASETS:
        for rs_dir in RULESETS:
            tag = "%s_%s" % (ds_name, rs_dir)
            print("\n=== measure %s ===" % tag)
            s = measure_combo(tag, ds_name, ds_dir, rs_dir, chunk_size)
            if s:
                summaries.append(s)

    print("\n=== measure matrix summary ===")
    for s in summaries:
        print("  %-48s files=%d vocab=%d(tot %d) max_occ_per_chunk avg/max=%.2f/%d"
              % (s["tag"], s["files"], s["vocab"], s["vocab_total"],
                 s["maxocc_avg"], s["maxocc_max"]))


if __name__ == "__main__":
    main()
