/// Data types for this crate

/* Refactored: 07/24/2024 from the original common.rs 
	Changed: 05/07/2025: added SubsigStepStore info
*/

extern crate serde;
extern crate rustomaton;

use self::serde::{Serialize,Deserialize};
use rustomaton::dfa::DFA;
use std::{ collections::{HashSet,HashMap}, sync::{Arc} };
use crate::hex_acdfa::HexACDFA;


/// M8 (2026-06-02): definition moved to utils::consts so it can be
/// embedded in GlobalConfig without a dependency cycle. This
/// re-export keeps every existing
/// `use crate::type_def::ClamavApproxConfig` / `use
/// data_processor::type_def::ClamavApproxConfig` working unchanged.
pub use utils::consts::ClamavApproxConfig;

#[derive(Copy,Clone,Debug,PartialEq,Serialize,Deserialize)]
pub enum ClamSigType{
	///general regex type
	General, 
	/// pattern-matching regex (this accounts for 97.5 of clamav logic sig), deprecated (we no longer distinguish type when building ClamavSig object). However, for those PM regex list, they can be found in <data/src_sig/clamav/categories/pm_reg.dat>. The list is generated by a separated python script gen_data.py in scripts folder.
	PM, 
}

/// information of Pcre regex in signatures (for reporting)
#[derive(Serialize,Deserialize, Clone,Debug)]
pub struct PcreInfo{
	/// if it is pcre
	pub b_pcre: bool,
	/// if it has backreference
	pub b_backref: bool,
	/// if it has zero length assertion
	pub b_zero_assert: bool,
	/// pattern starts at begin
	pub b_begin: bool,
	/// pattern must ends at the end
	pub b_end: bool,
	/// has zk-check of boundary PARTICULARLY in the current item
	pub b_boundary: bool,
	/// original_str the original string (ONLY used at TOP ROOT LEVEL)
	/// for general regex of clamav, this isthe original string
	/// WITHOUT Preprocessing (the reason) - handling repeittion
	/// directly has more effiicency (avoiding a lot of DFA concats)
	pub original_str: String,
}

/// Subsignature type
#[derive(Debug,PartialEq,Clone,Serialize,Deserialize)]
pub enum SubSigType{
	/// general regex for General
	GeneralRegex = 0,
	/// counter constraint (like 0=1, 1=0), require the subsignature
	/// involved needs to be ONE single pattern word
	CounterConstraint = 1,
	/// SubsigCountConstraint expecting the MINIMUM number of
	/// subsignatures that are met
	SubsigCountConstraint = 2,
}

/// Object for encapsulating subsignature of a ClamavSig
#[derive(Debug,Clone,Serialize,Deserialize)]
pub struct SubSigObj{
	/// the original subsig string extracted from ClamAV signature
	pub value: String,
	/// type of subsig (general regex, counter, total counter etc)
	pub subsig_type: SubSigType,
	/// converted subsig string to cater to syntax accepted by Rustomaton,
	/// or with decorator/modifier handled (e.g., ignore case, wide char etc)
	pub real_value: String, //used for CounterType
	/// whether to ignore case
	pub b_ignore_case: bool, //whether the subsignature is ignoring case
	// the folowing are for SubsigCountConstraint ONLY
	// for all other types, set to empty set and 0
	/// the set of subsignature IDs
	pub set_subsigs: HashSet<usize>, 
	/// minimum required number of SATISFIED subsigs (used for counter
	/// constraint such as `(2|3|4)>3,2` which means that out of
	/// subsigs 2,3,4, there are is at least 4 matches, that match
	/// at least 2 distinct subsignatures.
	/// See doc: https://docs.clamav.net/manual/Signatures/LogicalSignatures.html (4.7.1)
	/// ``=X,Y: If the SUB-EXPRESSION A refers to a single signature then this signature must be matched exactly X times; if it refers to a (logical) block of signatures then this block must generate X matches and at least Y different signatures must get matched. ''
	pub min_required: usize,
}

/// tri-value ''boolean logic''
#[derive(Debug,PartialEq,Copy,Clone)]
pub enum TriVal{
	False = 1, 
	True = 2, 
	Maybe = 3,
}

#[derive(Debug,PartialEq,Copy,Clone)]
pub enum TriOp{
	Not = 11, 
	BitAnd = 12, 
	BitOr = 13,
}

#[derive(Debug,Copy,Clone,PartialEq)]
pub enum CompOp{
	NONE = 0,
	GT = 1, 
	LT = 2, 
	EQ = 3,
}


#[derive(Debug,Clone)]
/// It represents the raw parsing of clamav main.ldb sig string
/// See <https://docs.clamav.net/manual/Signatures/LogicalSignatures.html>
/// for specification.
/// The eval_dnf represents a Disjunctive Normal Form (DNF)
/// that describes the execution order. The reason we use
/// DNF is that when the the formula is negated, applying
/// Demorgan's law allows to achieve a NFA with much smaller size.
#[derive(Serialize,Deserialize)]
pub struct ClamavSig{
	/// name of the clamav sig
	pub name: String,
	/// brief description 
	pub desc: String,
	/// the logical expression on subsigs, e.g., `(2|3|4)`
	pub expr: String,
	/// the first line of the clamav sig
	pub line: String,
	/// subsignature raw regex expressions
	pub vec_subsigs: Vec<String>,
	/// constructed subisg objects
	pub vec_subsig_obj: Vec<SubSigObj>,
	/// whether the subsignature needs to be negated
	pub vec_bneg: Vec<bool>,
	/// information of pcre subsig (default empty for general regex subisg)
	pub vec_pcre_info: Vec<PcreInfo>,  
	/// if the subsig is ignore-case
	pub vec_bcase_sensitive: Vec<bool>,
	/// logical expression converted to DNF format
	pub eval_dnf: EvalDNF,
	/// type of clamav sig
	pub sigtype: ClamSigType,
//	#[serde(skip_serializing)]
	/// list of automaton (only needs to build for a FEW)
	pub vec_subsig_automaton: Vec<Arc<DFA<char>>>, //each to a subsig_obj (optional)

	///(optional) for each subisg, it has a HashSet of `Vec<String>` (called Bag of Words). We require that all Bag of Words should have one of its element appear at least once (for regular constraint). Semantics is similar for counter constraint. 
	pub vec_subsig_bagwords: Vec<HashSet<Vec<String>>>, 
	///(optioal) vector of pm_bounds (works for both pm and general if 
	/// they are approximated).
	pub vec_subsig_pm_bounds: Vec<Vec<(String, (usize, usize) )>>,
	/// will fail crit_pat coz no crit_pat can be extracted
	pub b_no_crit_pat: bool,
}

#[derive(Clone,Serialize,Deserialize)]
pub struct EvalDNF{
	/// vector of vectors that represents a DNF. e.g., [ [0,1], [2,3] ] 
	/// represents (0|1) & (2|3), i.e., a CONJUNCTION of DISJUNCTIONS!
	/// IN another word, to prove "discharge" - not satisfying
	/// we only need to EITHER prove: both 0 and 1 are not matched
	/// OR both 2 and 3 are NOT matched
	pub vec_disjunc: Vec<Vec<usize>>,
}

/// One record in SubsigPattenStore
#[derive(Serialize, Deserialize,Clone,Debug)]
pub struct SubsigPatternStoreItem{
	/// the subsig ID
	pub subsig_id: usize,
	/// sorted. state id starting from 1 (adjusted by plus 1).
	pub state_ids: Vec<usize>,
	/// patten ID is adjusted patten ID in acdfa (adjusted by plus 1)
	/// the patten IDs are sorted
	pub state_to_pattern_ids: HashMap<usize, Vec<usize>>,
}

/// Store the information subsig -> acdfa states -> pattens
/// where the patterns are restricted to those related to the subsig
#[derive(Serialize, Deserialize,Clone,Debug)]
pub struct SubsigPatternStore{
	/// sorted, generated by acdfa::gen_subsig_id (note: do start from 1)
	/// it is a concat of sig_id (start from 1) || subsig_id (start from 1)
	pub subsig_ids: Vec<usize>,
	/// map from subsig_id to the record. We assume that
	/// item is small, so returning by clone is ok.
	pub subsig_to_rec: HashMap<usize, SubsigPatternStoreItem>,
}

/// One record in SubsigInfoStore
/// It contains the information of the type of subsig, 
/// and also the information for counter constraints and subsit_counter
/// constraints (if regular, related items are dummy values)
#[derive(Serialize, Deserialize,Clone,Debug)]
pub struct SubsigInfoStoreItem{
	/// the subsig ID
	pub subsig_id: usize,
	/// the subsig type converted from SubSigType (0-GeneralRegex, ...)
	pub subsig_type: u8, //converted from SubSigType
	/// the operator CompOp (default 0 - no op)
	pub comp_op: u8, 
	/// the num related to comp_op (default 0, will yield tautology)
	pub comp_num: u32,
	/// the min_required (if SubsigConounterConstraint, default 0)
	pub min_required: usize,
	/// the related subsigs (if SubsigCounterConstraint). 
	/// Note its size range from 0 to 62. So we would have to end
	/// up with a flexible size data table design.
	/// There are 383 subsigs among 2k subsigs that has SubsigCountConstraint
	/// type. The avg number of component subsigs is about 3 (including all 
	/// 2k other general subsigs)
	pub component_subsigs: Vec<usize>,
}

/// Store the information subsig -> (type, counter constraints related info)
#[derive(Serialize, Deserialize,Clone,Debug)]
pub struct SubsigInfoStore{
	/// sorted, generated by acdfa::gen_subsig_id (note: do start from 1)
	/// it is a concat of sig_id (start from 1) || subsig_id (start from 1)
	pub subsig_ids: Vec<usize>,
	/// map from subsig_id to the record. We assume that
	/// item is small, so returning by clone is ok.
	pub subsig_to_rec: HashMap<usize, SubsigInfoStoreItem>,
}

/// One record in SubsigStepStore
#[derive(Serialize, Deserialize,Clone,Debug)]
pub struct SubsigStepStoreItem{
	/// the subsig ID (which matches SubsigPatStoreItem's
	pub subsig_id: usize,
	/// whether the subsig is IGC
	/// NOTICE that this is a TRUE flag of the subsig.
	/// Even if the store is a NON-matching igc, this flag is set as it is
	/// if non-match igc, the vec_p_bounds will be set to empty.
	/// will eventually leads to FALSE for non-match igc mode (in sed),
	/// which is OK, because compute_sig_adv will pick the correct result
	/// based on IGC attribute.
	pub igc: bool,
	/// step info (this is basically retrieved from
	/// vec_subsig_pm_bounds of the Sig object
	/// NOTICE that if the b_ignore_case does not match with the store
	/// or the subsig is a composite of subsig  (TotalSubsigCount type)
	/// this vector is set to empty
	/// each element represents a step:
	/// (pat_id, (a, b))
	/// where pat_id starts from 0 (raw pattern id), 
	/// (a,b) are the ranges, a,b are included, e.g., (1,1) as a range 
	/// they represent the allowed distance of current pat from
	/// any valid word in the previous step. (read clamav.rs::
	///     approx_eval_pm_bounds_subsig).
	/// *** SPECIFIC NOTE ***: here (a,b) are the ORIGINAL vec_pm_bounds
	/// value in ClamavSig object PLUS the pattern word length (reason:
	///  the location of the acc_state is at the END of the word)
	pub vec_pm_bounds: Vec<(usize, (usize, usize))>
}


/// Store the information subsig -> steps (note that this is
/// specific to b_ignore_case. If not match then the corresponding
/// list of steps is empty because acdfa used does not match)
#[derive(Serialize, Deserialize,Clone,Debug)]
pub struct SubsigStepStore{
	/// sorted, generated by acdfa::gen_subsig_id (note: do start from 1)
	/// it is a concat of sig_id (start from 1) || subsig_id (start from 1)
	pub subsig_ids: Vec<usize>,
	/// map from subsig_id to the record. We assume that
	/// item is small, so returning by clone is ok.
	pub subsig_to_steps: HashMap<usize, SubsigStepStoreItem>,
}


/// Stores SubsigPatternStore, related Sigs, related pattern_map_to_sig
/// and related ACDFA.
/// Note "0" entry corresponds to all. and its ACDFA entry 0 is 
/// is the ACDFA bag-words (pm approach) for ALL sigs. Then after
/// entry #1, its for individual sigs. 
/// Note that the vec_sigs[0] is a vector of ALL sigs,
/// and then startging from i>=1, vec_sigs[i] is a SINGLE ELEMENT
/// vector containing one ClamavSig, whose pm_bound_vec is generated
/// using cfg (min_pm_word=0) for ISED.
#[derive(Serialize, Deserialize,Clone)]
pub struct BundleSubsigStore{
	/// whether it's for ignore case
	pub b_igc: bool,
	/// the first entry is "all". Then after 1st entry, is one individual
	/// signature name
	pub vec_sig_names: Vec<String>,
	/// the corresponding sig corresponding signame. For 0'th entry,
	/// its the collection of ALL signatures. It's >=1 entries are
	/// vector of single elements
	pub vec_sigs: Vec<Vec<Arc<ClamavSig>>>, 
	/// acdfa corresponds to vec_sigs one by one.
	pub vec_acdfa: Vec<HexACDFA>,

	// -- subsig - state - pat database
	/// encodes the subsig-state-pattern information 
	pub vec_subsig_stores: Vec<SubsigPatternStore>,
	/// map from pattern to signature names
	pub vec_map_pattern_sig: Vec<HashMap<String,Vec<String>>>,

	// -- subsig - steps (pat, allowed_range)
	pub vec_subsig_step_stores: Vec<SubsigStepStore>,

	// -- subsig - counter constraint related info
	pub vec_subsig_info_stores: Vec<SubsigInfoStore>
}


